cpp/dolfin/fem/DofMap.cpp, cpp/dolfin/fem/DofMap.h, cpp/dolfin/fem/DofMapBuilder.cpp, cpp/dolfin/fem/DofMapBuilder.h, cpp/dolfin/fem/GenericDofMap.h, python/src/fem.cpp
Will be much simpler via mesh topology/geometry.
=> Remove constrained dofmap code.

cpp/dolfin/common/MPI.cpp, cpp/dolfin/common/Variable.cpp, cpp/dolfin/common/Variable.h, cpp/dolfin/function/GenericFunction.cpp, cpp/dolfin/io/VTKFile.cpp, cpp/dolfin/log/Table.cpp, cpp/dolfin/mesh/Mesh.cpp, cpp/dolfin/mesh/MeshFunction.h, cpp/dolfin/mesh/MeshTopology.cpp, cpp/dolfin/mesh/MeshValueCollection.h, cpp/dolfin/nls/NewtonSolver.cpp, python/demo/undocumented/poisson-disc/demo_poisson-disc.py, python/dolfin/function/constant.py, python/dolfin/function/expression.py, python/dolfin/function/function.py, python/dolfin/function/specialfunctions.py, python/src/common.cpp, python/test/unit/io/test_XDMF.py
Remove Variable::label in favour of Variable::name.
=> Remove Variable::label

.gitignore, cpp/dolfin/fem/Assembler.cpp, cpp/dolfin/fem/Assembler.h, cpp/dolfin/fem/utils.cpp, cpp/dolfin/la/PETScMatrix.cpp, cpp/dolfin/la/SparsityPattern.cpp, python/test/unit/fem/test_assembler.py
More to do, but merging now to avoid conflicts later.
=> Work on block assembler

cpp/dolfin/common/IndexMap.cpp, cpp/dolfin/common/MPI.cpp, cpp/dolfin/common/MPI.h, cpp/dolfin/common/SubSystemsManager.cpp, cpp/dolfin/common/Timer.cpp, cpp/dolfin/fem/DiscreteOperators.cpp, cpp/dolfin/fem/DofMapBuilder.cpp, cpp/dolfin/fem/FiniteElement.cpp, cpp/dolfin/fem/Form.cpp, cpp/dolfin/fem/LocalAssembler.cpp, cpp/dolfin/fem/SparsityPatternBuilder.cpp, cpp/dolfin/fem/SystemAssembler.cpp, cpp/dolfin/fem/utils.cpp, cpp/dolfin/function/Constant.cpp, cpp/dolfin/function/Expression.cpp, cpp/dolfin/function/Function.cpp, cpp/dolfin/function/FunctionAXPY.cpp, cpp/dolfin/function/FunctionSpace.cpp, cpp/dolfin/generation/IntervalMesh.cpp, cpp/dolfin/la/SparsityPattern.cpp, cpp/dolfin/la/SparsityPattern.h, python/src/la.cpp
Row-oriented only again. Col-major was unlikely to work in all cases.
=> Simplification of SparsityPattern

.circleci/config.yml
=> Use ninja in place of make on circleci

cpp/dolfin/common/SubSystemsManager.cpp, cpp/dolfin/common/SubSystemsManager.h, cpp/dolfin/common/defines.cpp, cpp/dolfin/common/defines.h, cpp/dolfin/common/init.cpp, cpp/dolfin/common/types.h, cpp/dolfin/parameter/GlobalParameters.h, python/dolfin/__init__.py, python/dolfin/jit/pybind11jit.py, python/src/common.cpp, python/test/unit/parallel-assembly-solve/test_solve_result_against_reference.py
* `has_petsc()` no longer needed.
=> Delete a lot of places with "if has_petsc"

python/test/unit/fem/test_numba_assembly.py
Minor fix for numba assembly to let it work with complex numbers.
=> Adjust numba assembly to allow complex128

.circleci/config.yml, cpp/dolfin/fem/DofMap.cpp, cpp/dolfin/fem/DofMapBuilder.cpp
* need to reset circleci config before merge
=> Simplify ufc dofmap by replacing some function calls with arrays

cpp/dolfin/fem/PETScDMCollection.cpp, python/test/unit/fem/test_petsc_transfer_matrix.py
Updates to PETScDMCollection - now working again, providing useful `create_transfer_matrix` method for GMG.
=> Fix PETScDMCollection

cpp/dolfin/io/HDF5Interface.cpp, python/test/unit/io/test_HDF5.py
When addressed file is not existing create new empty one.
=> Make HDF append mode C-style

.circleci/config.yml
Proposal:
- nightly builds that run every day at 00:00 am UTC,  to test complex mode.
- reuse code (steps) for the real and complex workflows.
Real mode (default) is triggered when pushing to any branch.
=> [WIP] Set nightly builds for complex mode

cpp/dolfin/fem/Assembler.cpp, cpp/dolfin/fem/Assembler.h
Start some simplifications for zeroing rows.
=> Assembler refactoring

cpp/cmake/templates/dolfin.pc.in
=> Only gave relative path, add absolute path.

cpp/dolfin/mesh/MeshEntity.h
=> Update code for entities when same dim

cpp/dolfin/io/XDMFFile.cpp
Change the XDMF topolgy types to match the schema
https://github.com/Kitware/VTK/blob/master/ThirdParty/xdmf3/vtkxdmf3/Xdmf.dtd#L34
=> Update XDMF topolgy types with full name

cpp/dolfin/la/PETScVector.cpp, python/dolfin/fem/__init__.py, python/dolfin/fem/assemble.py, python/dolfin/fem/assembling.py
Also adds change for PETSc dev.
=> Some cleanup of Python fem.assemble

python/dolfin/__init__.py, python/dolfin/fem/__init__.py, python/dolfin/fem/coordinatemapping.py, python/dolfin/fem/dofmap.py, python/dolfin/fem/form.py, python/dolfin/function/functionspace.py, python/test/unit/la/test_sparsity_pattern.py
Wrapped `cpp.fem.dofmap` as `fem.dofmap`.
"Overloaded" constructor is solved via `@classmethod`.
=> Wrap cpp.fem.dofmap in python

python/dolfin/MPI.py, python/dolfin/common.py, python/dolfin/fem/dofmap.py, python/dolfin/function/__init__.py, python/dolfin/function/function.py, python/dolfin/function/functionspace.py, python/dolfin/generation.py, python/dolfin/geometry.py, python/dolfin/io.py, python/dolfin/jit/jit.py, python/dolfin/jit/pybind11jit.py, python/dolfin/parameter.py, python/dolfin/pkgconfig.py, python/dolfin/plotting.py, python/src/function.cpp
Substantially simplifies implementation.
There is still some shaky code that would be best fixed with a small interface change.
=> Start Python FunctionSpace simplifications

.circleci/config.yml, python/dolfin_utils/test/__init__.py, python/dolfin_utils/test/fixtures.py, python/dolfin_utils/test/skips.py, python/test/unit/fem/test_discrete_operators.py, python/test/unit/fem/test_dofmap.py, python/test/unit/fem/test_permutation.py, python/test/unit/function/test_function.py, python/test/unit/function/test_function_space.py, python/test/unit/function/test_special_functions.py, python/test/unit/geometry/test_bounding_box_tree.py, python/test/unit/io/test_HDF5.py, python/test/unit/io/test_HDF5_series.py, python/test/unit/io/test_XDMF.py, python/test/unit/io/test_XDMF_P2.py, python/test/unit/jit/test_jit.py, python/test/unit/la/test_mg_solver.py, python/test/unit/la/test_sparsity_pattern.py, python/test/unit/mesh/test_cell.py, python/test/unit/mesh/test_edge.py, python/test/unit/mesh/test_face.py, python/test/unit/mesh/test_manifold_point_search.py, python/test/unit/mesh/test_mesh.py, python/test/unit/mesh/test_mesh_editor.py, python/test/unit/mesh/test_mesh_function.py, python/test/unit/mesh/test_mesh_quality.py, python/test/unit/mesh/test_periodic_boundary_computation.py, python/test/unit/parallel-assembly-solve/test_solve_result_against_reference.py
=> Fix pytest warnings

cpp/dolfin/function/Function.h, python/demo/documented/stokes-taylor-hood/demo_stokes-taylor-hood.py.rst, python/dolfin/function/function.py, python/dolfin/plotting.py, python/src/function.cpp
Didn't require any interface updates in tests for construction.
=> Major simplification of Python Function

python/dolfin/function/jit.py, python/dolfin/function/specialfunctions.py, python/dolfin/jit/jit.py
=> Remove some old code and use more type hinting

python/dolfin/fem/form.py, python/test/unit/fem/test_assembler.py
* Fix a line in `form.py` which was not working
* Add test
=> Fix failure of Function in a form

cpp/dolfin/fem/DofMap.h, cpp/dolfin/fem/GenericDofMap.h, cpp/dolfin/fem/assemble_vector_impl.cpp, cpp/dolfin/function/FunctionSpace.cpp, cpp/dolfin/function/FunctionSpace.h, cpp/dolfin/la/PETScMatrix.cpp, cpp/dolfin/la/PETScMatrix.h, cpp/dolfin/la/PETScVector.cpp, cpp/dolfin/la/PETScVector.h, cpp/dolfin/la/utils.cpp, cpp/dolfin/nls/NewtonSolver.cpp, python/demo/documented/cahn-hilliard/demo_cahn-hilliard.py.rst, python/src/fem.cpp, python/test/unit/nls/test_newton.py
Tests a linear and nonlinear PDE.
=> Add tests for Newton solver

python/dolfin/pybind11jit.py
and add required `-undefined dynamic_lookup` to resolve the Python symbols at runtime on darwin
port of https://bitbucket.org/fenics-project/dolfin/pull-requests/507
=> avoid linking libpython when python itself is statically linked

cpp/cmake/modules/FindUFC.cmake, cpp/demo/documented/hyperelasticity/main.cpp, cpp/dolfin/fem/assemble_matrix_impl.cpp, cpp/dolfin/fem/assemble_vector_impl.cpp, cpp/dolfin/fem/assemble_vector_impl.h, cpp/dolfin/fem/assembler.cpp, python/test/unit/nls/test_newton.py
And an update for finding `ufc.h`.
=> Extra consistency for assembler with essential bcs

cpp/dolfin/fem/DirichletBC.cpp, cpp/dolfin/fem/DirichletBC.h, cpp/dolfin/fem/assemble_vector_impl.cpp, cpp/dolfin/fem/assemble_vector_impl.h, cpp/dolfin/fem/assembler.cpp, cpp/dolfin/fem/assembler.h
=> Simplify vector bc application in assembler

cpp/dolfin/fem/assembler.cpp, cpp/dolfin/fem/assembler.h, python/src/fem.cpp
Low-level option to control how nested matrices are extracted.
=> Assembler nest option

cpp/dolfin/common/IndexMap.cpp, cpp/dolfin/common/IndexMap.h, cpp/dolfin/common/MPI.h, cpp/dolfin/fem/DofMapBuilder.cpp, cpp/dolfin/fem/assemble_matrix_impl.cpp, cpp/dolfin/fem/assemble_matrix_impl.h, cpp/dolfin/fem/assembler.cpp, cpp/dolfin/fem/assembler.h, cpp/dolfin/fem/utils.cpp, cpp/dolfin/la/SparsityPattern.cpp, cpp/dolfin/la/utils.cpp, python/dolfin/fem/assembling.py, python/test/unit/fem/test_assembler.py
Add test that assembles a Stokes problem into various formats.
More to do still for vectors, and to handle more general cases with null blocks in different locations.
=> Get nested matrices working for null block, e.g. Stokes

cpp/dolfin/fem/PETScDMCollection.cpp, cpp/dolfin/fem/PETScDMCollection.h, cpp/dolfin/function/Function.cpp, cpp/dolfin/function/Function.h, cpp/dolfin/mesh/Mesh.cpp, cpp/dolfin/mesh/Mesh.h, python/dolfin/function/function.py, python/dolfin/geometry.py, python/src/fem.cpp, python/src/function.cpp, python/src/mesh.cpp, python/test/unit/fem/test_permutation.py, python/test/unit/function/test_function.py, python/test/unit/geometry/test_bounding_box_tree.py, python/test/unit/mesh/test_manifold_point_search.py
=> Remove boundary box tree as member of Mesh

python/dolfin/common.py, python/src/common.cpp
=> Import cpp attributes into Python namespace.

cpp/demo/hyperelasticity/main.cpp, cpp/demo/poisson/main.cpp, cpp/dolfin/fem/DiscreteOperators.cpp, cpp/dolfin/fem/SparsityPatternBuilder.cpp, cpp/dolfin/fem/SparsityPatternBuilder.h, cpp/dolfin/fem/utils.cpp, cpp/dolfin/fem/utils.h, cpp/dolfin/la/SparsityPattern.cpp, cpp/dolfin/la/SparsityPattern.h, python/src/fem.cpp, python/src/la.cpp, python/test/unit/la/test_sparsity_pattern.py
Removes some non-working functionality, which might come back.
=> Simplify sparsity pattern

README.rst
=> Update README.rst with Discourse page. 

.circleci/config.yml, cpp/dolfin/fem/FormIntegrals.cpp
Works with ffc branch chris/simplify-integrals
=> Use new ffc interface for integrals

Dockerfile
See https://github.com/gabime/spdlog/issues/975
=> Fix for Dockerfile 

cpp/demo/hyperelasticity/main.cpp, cpp/demo/poisson/main.cpp
Needs this first: https://github.com/FEniCS/ffcx/pull/110
=> Update for UFC name change.

cpp/demo/hyperelasticity/main.cpp, cpp/demo/poisson/main.cpp, cpp/dolfin/fem/DofMap.cpp, cpp/dolfin/fem/DofMapBuilder.cpp, cpp/dolfin/fem/DofMapBuilder.h, cpp/dolfin/fem/FiniteElement.cpp, cpp/dolfin/fem/Form.cpp
Need to use smart pointers carefully.
=> Fix memory management for objects allocated using malloc

cpp/dolfin/common/Table.cpp
=> Add missing include

cpp/CMakeLists.txt, cpp/dolfin/CMakeLists.txt, cpp/dolfin/common/defines.cpp, cpp/dolfin/graph/SCOTCH.cpp, cpp/dolfin/graph/SCOTCH.h, cpp/dolfin/mesh/MeshPartitioning.cpp, python/dolfin/__init__.py, python/dolfin/common.py, python/src/common.cpp
=> Make SCOTCH a required dependency (at least for now). Fixes #140.

cpp/dolfin/fem/FormIntegrals.cpp, cpp/dolfin/fem/assemble_matrix_impl.cpp, cpp/dolfin/fem/assemble_scalar_impl.cpp, cpp/dolfin/fem/assemble_scalar_impl.h, cpp/dolfin/fem/assemble_vector_impl.cpp, cpp/dolfin/fem/assemble_vector_impl.h, python/test/unit/fem/test_assemble_domains.py
Easy continuation of https://github.com/FEniCS/dolfinx/pull/360
After this PR all combinations of integrals on subdomains of type {cell, exterior_facet} with {matrix, vector, scalar} integrals should work.
=> More integration on subdomains

python/test/unit/fem/test_assembler.py
True reason still not found. This should at least fix the annoying failing test.
=> Fix memory error

cpp/CMakeLists.txt, cpp/dolfin/common/TimeLogger.cpp
=> Use stdout for list_timing

cpp/dolfin/common/IndexMap.cpp, cpp/dolfin/common/IndexMap.h, cpp/dolfin/fem/DofMap.cpp, cpp/dolfin/fem/DofMapBuilder.cpp, cpp/dolfin/fem/DofMapBuilder.h, cpp/dolfin/fem/ElementDofLayout.h, cpp/dolfin/fem/GenericDofMap.cpp, cpp/dolfin/fem/GenericDofMap.h
Shorter, simpler, easier to follow and should be faster.
=> Simplify dofmap construction

cpp/dolfin/fem/DofMapBuilder.cpp, cpp/dolfin/fem/FiniteElement.h, cpp/dolfin/function/FunctionSpace.cpp
Avoid unnecessary vector<vector>.
=> Flatten dofmap reordering

cpp/dolfin/fem/DirichletBC.cpp, cpp/dolfin/fem/DirichletBC.h, cpp/dolfin/fem/DofMap.cpp, cpp/dolfin/fem/DofMap.h, cpp/dolfin/fem/DofMapBuilder.cpp, cpp/dolfin/fem/DofMapBuilder.h, cpp/dolfin/fem/GenericDofMap.h
Builds on simplifications from using IndexMap for scatters.
=> Simplify DirichletBC computation

cpp/dolfin/fem/CoordinateMapping.cpp, cpp/dolfin/fem/CoordinateMapping.h, cpp/dolfin/fem/Form.cpp, cpp/dolfin/fem/utils.cpp, cpp/dolfin/fem/utils.h, python/dolfin/fem/coordinatemapping.py, python/dolfin/fem/dofmap.py, python/src/fem.cpp
* Paves the way for custom user coordinate mapping, and/or optimisation.
=> Create CoordinateMapping without direct reference to ufc_coordinate_mapping

cpp/dolfin/fem/DofMap.cpp, cpp/dolfin/fem/DofMap.h, cpp/dolfin/fem/ElementDofLayout.cpp, cpp/dolfin/fem/ElementDofLayout.h, cpp/dolfin/fem/FiniteElement.cpp, cpp/dolfin/fem/FiniteElement.h, cpp/dolfin/fem/GenericDofMap.h, cpp/dolfin/function/Function.cpp, cpp/dolfin/function/Function.h, cpp/dolfin/function/FunctionSpace.cpp, cpp/dolfin/function/FunctionSpace.h
=> Remove some old protected FunctionSpace constructors

cpp/demo/hyperelasticity/main.cpp, cpp/demo/poisson/main.cpp, cpp/dolfin/fem/Form.cpp, cpp/dolfin/fem/Form.h, cpp/dolfin/fem/FormCoefficients.h, cpp/dolfin/fem/FormIntegrals.h, cpp/dolfin/fem/utils.cpp, cpp/dolfin/fem/utils.h, python/dolfin/fem/form.py, python/src/fem.cpp
This simplifies the Form class, and reduces likelihood of bugs and inconsistencies.
=> Separate fem::From creation from processing of ufc form

cpp/dolfin/common/IndexMap.cpp, cpp/dolfin/common/IndexMap.h, cpp/dolfin/fem/DirichletBC.cpp, cpp/dolfin/fem/DiscreteOperators.cpp, cpp/dolfin/fem/DofMap.cpp, cpp/dolfin/fem/DofMap.h, cpp/dolfin/fem/DofMapBuilder.cpp, cpp/dolfin/fem/DofMapBuilder.h, cpp/dolfin/fem/ElementDofLayout.cpp, cpp/dolfin/fem/ElementDofLayout.h, cpp/dolfin/fem/PETScDMCollection.cpp, cpp/dolfin/fem/assemble_vector_impl.cpp, cpp/dolfin/fem/assembler.cpp, cpp/dolfin/fem/utils.cpp, cpp/dolfin/function/Function.cpp, cpp/dolfin/function/FunctionSpace.cpp, cpp/dolfin/function/FunctionSpace.h, cpp/dolfin/graph/GraphBuilder.cpp, cpp/dolfin/la/SparsityPattern.cpp, cpp/dolfin/la/utils.cpp, cpp/test/unit/common/IndexMap.cpp, python/dolfin/fem/dofmap.py, python/dolfin/mesh.py, python/src/common.cpp, python/src/fem.cpp, python/test/unit/fem/test_dofmap.py
=> Simplification of DofMap

Dockerfile
=> Add sudo to Dockerfile [skip ci]

cpp/dolfin/geometry/utils.cpp, cpp/dolfin/geometry/utils.h, python/dolfin/__init__.py, python/src/mesh.cpp, python/test/unit/fem/test_dofmap.py, python/test/unit/io/test_HDF5.py, python/test/unit/mesh/test_cell.py, python/test/unit/mesh/test_mesh.py
=> Remove MeshEntity shortcuts

cpp/dolfin/fem/DiscreteOperators.cpp, cpp/dolfin/fem/DofMapBuilder.cpp, cpp/dolfin/io/HDF5File.cpp, cpp/dolfin/io/HDF5Utility.cpp, cpp/dolfin/io/XDMFFile.cpp, cpp/dolfin/io/xdmf_read.h, cpp/dolfin/io/xdmf_write.cpp, cpp/dolfin/mesh/DistributedMeshTools.cpp, cpp/dolfin/mesh/MeshEntity.h, cpp/dolfin/refinement/PlazaRefinementND.cpp, python/src/mesh.cpp
Faster and clearer via Topology.
=> Remove MeshEntity::global_index

cpp/dolfin/function/Constant.cpp, cpp/dolfin/function/Constant.h, python/dolfin/function/constant.py, python/src/function.cpp, python/test/unit/function/test_constant.py
Make Python behaviour consistent for all rank.
=> Misc Constant tidy-up

cpp/dolfin/fem/DirichletBC.cpp, cpp/dolfin/fem/ElementDofLayout.cpp, cpp/dolfin/fem/Form.cpp, cpp/dolfin/fem/FormCoefficients.cpp, cpp/dolfin/fem/FormIntegrals.cpp, cpp/dolfin/fem/PETScDMCollection.cpp, cpp/dolfin/fem/SparsityPatternBuilder.cpp, cpp/dolfin/fem/assemble_vector_impl.cpp, cpp/dolfin/function/Function.cpp
Change some assertions to exceptions.
=> Add mesh connectivity checks

CODE_OF_CONDUCT.md
As suggested by github "community" insight tool.
=> Add CODE_OF_CONDUCT file to top level

cpp/dolfin/function/FunctionSpace.h
=> Minor doc fix.

python/demo/cahn-hilliard/demo_cahn-hilliard.py, python/demo/elasticity/demo_elasticity.py, python/demo/stokes-taylor-hood/demo_stokes-taylor-hood.py
Cleans up some comments and old bits of code in a few demos.
=> Miscellaneous demo cleanup

cpp/dolfin/mesh/Topology.cpp, cpp/dolfin/mesh/Topology.h, python/src/mesh.cpp, python/test/unit/mesh/test_mesh.py
Create a list of `bool` for entities which are on the surface of a mesh.
=> Topology surface entities

python/dolfin/geometry.py, python/src/geometry.cpp, python/test/unit/geometry/test_bounding_box_tree.py, python/test/unit/mesh/test_manifold_point_search.py
Support processing searches for multiple points.
=> Vectorise point searches from Python

cpp/dolfin/fem/FormIntegrals.cpp, python/test/unit/fem/test_ghost_mesh_assembly.py
Fixes problems with domain markers, issue #536
=> Restrict facet integral markers

.circleci/config.yml, python/test/unit/fem/test_assemble_domains.py
Will revert .circleci/config.yml once ufl PR has been merged.
=> Test for issue 551

python/dolfin_utils/test/fixtures.py, python/dolfin_utils/test/skips.py, python/test/unit/fem/test_dofmap.py, python/test/unit/function/test_function.py, python/test/unit/function/test_function_space.py, python/test/unit/la/test_sparsity_pattern.py, python/test/unit/mesh/test_face.py, python/test/unit/mesh/test_mesh.py, python/test/unit/mesh/test_mesh_function.py, python/test/unit/mesh/test_periodic_boundary_computation.py
=> Remove old test-related code

python/dolfin/fem/solving.py, python/dolfin/jit.py
minor fix removing some obsolete calls
=> Remove some last vestiges of cpp.dolfin_error from python

cpp/dolfin/fem/CMakeLists.txt, cpp/dolfin/fem/CoordinateElement.cpp, cpp/dolfin/fem/CoordinateElement.h, cpp/dolfin/fem/DirichletBC.cpp, cpp/dolfin/fem/Form.cpp, cpp/dolfin/fem/Form.h, cpp/dolfin/fem/PETScDMCollection.cpp, cpp/dolfin/fem/dolfin_fem.h, cpp/dolfin/fem/utils.cpp, cpp/dolfin/fem/utils.h, cpp/dolfin/function/Function.cpp, cpp/dolfin/function/FunctionSpace.cpp, cpp/dolfin/mesh/Geometry.h, python/dolfin/fem/dofmap.py, python/src/fem.cpp, python/src/mesh.cpp, python/test/unit/fem/test_dofmap.py, python/test/unit/function/test_function.py
Make purpose clearer.
Also improves some docstrings.
=> Rename CoordinateMapping -> CoordinateElement

.circleci/config.yml, python/dolfin/MPI.py, python/dolfin/__init__.py, python/dolfin/common.py, python/dolfin/constant.py, python/dolfin/fem/assemble.py, python/dolfin/function.py, python/dolfin/functionspace.py, python/dolfin/generation.py, python/dolfin/geometry.py, python/dolfin/io.py, python/dolfin/jit.py, python/dolfin/la/__init__.py, python/dolfin/la/solver.py, python/dolfin/legacy.py, python/dolfin/log.py, python/dolfin/mesh.py, python/dolfin/pkgconfig.py, python/dolfin/plotting.py, python/dolfin/specialfunctions.py, python/test/unit/fem/test_assembler.py
Use environment variable to wind back JIT optimisation level on CI system.
=> Control JIT cflags via FFC API, with option to set using environment variable

.circleci/config.yml, python/dolfin/jit.py
Cache location is now controlled by DOLFIN.
=> Updates for FFC cache change

cpp/dolfin/fem/FormCoefficients.h, cpp/dolfin/fem/assemble_matrix_impl.cpp, cpp/dolfin/fem/assemble_matrix_impl.h, cpp/dolfin/fem/assemble_scalar_impl.cpp, cpp/dolfin/fem/assemble_scalar_impl.h, cpp/dolfin/fem/assemble_vector_impl.cpp, cpp/dolfin/fem/assemble_vector_impl.h, cpp/dolfin/fem/utils.cpp, cpp/dolfin/fem/utils.h
This is a start on new handling of form coefficients. Nothing changes at the user interface level yet.
Tests for forms with a bunch of coefficients indicate the that change leads to improved assembly performance.
=> Collect coefficients outside of innermost assembly loop

.circleci/config.yml, python/dolfin/jit.py, python/test/unit/fem/test_expression_evaluation.py
Supports https://github.com/FEniCS/ffcx/pull/160.
=> Test expression evaluation

cpp/test/unit/CMakeLists.txt, cpp/test/unit/catch/catch.hpp, cpp/test/unit/common/CIFailure.cpp, cpp/test/unit/main.cpp, cpp/test/unit/mesh/DistributedMesh.cpp
- Fix tests in parallel (related to issue #576)
- Update CATCH2 to version 2.10.2 (https://github.com/catchorg/Catch2/releases)
- New versions allow parametrized test cases (`TEMPLATE_TEST_CASE`)
- Cherry pick and update test from #577 .
- Can be removed if PR is approved.
=> Fix unit cpp tests in parallel

cpp/demo/hyperelasticity/main.cpp, cpp/dolfin/fem/DirichletBC.cpp, cpp/dolfin/fem/DirichletBC.h, cpp/dolfin/fem/assembler.cpp, cpp/dolfin/fem/assembler.h, cpp/dolfin/fem/utils.cpp, cpp/dolfin/fem/utils.h, cpp/dolfin/la/utils.cpp, cpp/dolfin/la/utils.h, python/dolfin/fem/assemble.py, python/src/caster_petsc.h, python/src/fem.cpp, python/src/la.cpp, python/test/unit/fem/test_assembler.py, python/test/unit/fem/test_nonlinear_assembler.py
Unpicks different stages, and re-uses more of the non-block assembly.
=> Re-factor block matrix assembly

cpp/dolfin/function/FunctionSpace.cpp, python/dolfin/function.py, python/test/unit/function/test_function.py
=> Fixing python interface of interpolation to work with finite element functions

cpp/demo/hyperelasticity/main.cpp, cpp/demo/poisson/main.cpp, cpp/dolfin/fem/DirichletBC.cpp, cpp/dolfin/fem/DirichletBC.h, cpp/dolfin/function/FunctionSpace.cpp, cpp/dolfin/function/FunctionSpace.h, python/demo/cahn-hilliard/demo_cahn-hilliard.py, python/demo/elasticity/demo_elasticity.py, python/demo/helmholtz2D/demo_helmholtz_2d.py, python/demo/mixed-elasticity-sc/static-condensation-elasticity.py, python/demo/poisson/demo_poisson.py, python/demo/stokes-taylor-hood/demo_stokes-taylor-hood.py, python/src/fem.cpp, python/test/unit/fem/test_assembler.py, python/test/unit/fem/test_complex_assembler.py, python/test/unit/fem/test_expression_evaluation.py, python/test/unit/fem/test_fem_pipeline.py, python/test/unit/fem/test_nonlinear_assembler.py, python/test/unit/fem/test_petsc_transfer_matrix.py, python/test/unit/function/test_function.py, python/test/unit/io/test_HDF5.py, python/test/unit/io/test_HDF5_series.py, python/test/unit/io/test_XDMF.py, python/test/unit/io/test_XDMF_P2.py, python/test/unit/la/test_krylov_solver.py, python/test/unit/mesh/test_higher_order_mesh.py, python/test/unit/nls/test_newton.py
The allows natural NumPy 'vectorised' expressions.
=> Simplify Python/NumPy syntax for transposing layout

python/test/unit/io/test_gmsh_io.py, python/test/unit/mesh/test_higher_order_mesh.py, python/test/unit/mesh/test_mesh.py
=> Skip tests that require pygmsh and h5py if they are not installed

.circleci/config.yml
Run workflow every day 01:00 AM.
=> Build nightly

cpp/cmake/templates/UseDOLFIN.cmake.in, python/CMakeLists.txt, python/doc/source/installation.rst
Updates version in some less obvious places.
=> C++17 updates

cpp/dolfin/common/TimeLogger.cpp, python/demo/poisson/demo_poisson.py
After recent changes, these were ignoring their input arguments.
Allow selection of subset of timing types again.
=> Fix behaviour of timings, list_timings

.circleci/config.yml, .circleci/trigger-build-and-pusher-docker-images-workflow.sh
=> Some tweaks to CircleCI configuration

cpp/dolfin/io/cells.cpp
There was a permutation missing for the general order case.
=> Fix reading interval mesh 2nd order

python/test/unit/mesh/test_higher_order_mesh.py
Work around some issues related to JIT not being thread-safe.
=> Test threading fix

python/test/unit/fem/test_fem_pipeline.py
UFL estimated degree very high, drop down to the commonly used values.
=> Control quadrature degree for tensor product elements

python/test/unit/fem/test_fem_pipeline.py
Speeds up tests significantly.
=> Simplify control of quadrature degree for quads/hexes in unit tets

python/test/unit/fem/test_custom_assembler.py
A single petsc4py line should be more efficient.
=> simplify petsc4py imports

cpp/dolfinx/common/IndexMap.h, cpp/dolfinx/fem/DirichletBC.cpp, cpp/dolfinx/la/SparsityPattern.cpp
Still need to fix case where two forms are processed at once.
=> Fix communication for Dirichlet bc data

cpp/doc/Doxyfile, cpp/dolfinx/fem/DirichletBC.h, cpp/dolfinx/fem/DofMap.h, cpp/dolfinx/fem/dofs_permutation.h, cpp/dolfinx/graph/AdjacencyList.h, cpp/dolfinx/la/SparsityPattern.h, cpp/dolfinx/mesh/Partitioning.h, cpp/dolfinx/mesh/TopologyComputation.h
This was missed when the name changed to dolfinx
=> Turn on doc checking again

cpp/dolfinx/fem/SparsityPatternBuilder.cpp, python/test/unit/fem/test_assembler.py
Also re-enable interior facet test in serial.
=> Fix assert in SparsityPatternBuilder

cpp/dolfinx/function/Function.cpp
=> Parallel eval fix

cpp/dolfinx/fem/SparsityPatternBuilder.cpp, python/test/unit/fem/test_assemble_domains.py, python/test/unit/fem/test_assembler.py
Use new owned vs ghost abstractions.
=> Fix sparsity construction for facets

cpp/dolfinx/fem/DiscreteOperators.cpp, cpp/dolfinx/fem/SparsityPatternBuilder.cpp, cpp/dolfinx/la/SparsityPattern.cpp, cpp/dolfinx/la/SparsityPattern.h, python/dolfinx/wrappers/fem.cpp, python/dolfinx/wrappers/la.cpp, python/test/unit/fem/test_discrete_operators.py
=> Small sparsity improvement

cpp/dolfinx/io/xdmf_utils.cpp
Picked up by updated compiler.
=> Fix build error.

docker/Dockerfile
=> Revert Hypre complex build

cpp/dolfinx/fem/DofMapBuilder.cpp, cpp/dolfinx/fem/dofs_permutation.cpp, cpp/dolfinx/fem/utils.cpp, cpp/dolfinx/io/HDF5File.cpp, cpp/dolfinx/io/HDF5Utility.cpp, cpp/dolfinx/io/XDMFFile.cpp, cpp/dolfinx/io/xdmf_read.h, cpp/dolfinx/io/xdmf_write.cpp, cpp/dolfinx/mesh/Mesh.cpp, cpp/dolfinx/mesh/Ordering.cpp, cpp/dolfinx/mesh/Topology.cpp, cpp/dolfinx/mesh/Topology.h, cpp/dolfinx/mesh/TopologyComputation.cpp, cpp/dolfinx/refinement/ParallelRefinement.cpp, cpp/dolfinx/refinement/PlazaRefinementND.cpp, python/dolfinx/wrappers/common.cpp, python/dolfinx/wrappers/mesh.cpp, python/test/unit/io/test_XDMF.py, python/test/unit/io/test_gmsh_io.py, python/test/unit/mesh/test_mesh_value_collection.py
Remove global indicies storage.
=> Remove global indices

python/test/unit/io/test_gmsh_io.py, python/test/unit/mesh/test_higher_order_mesh.py
See https://github.com/nschloe/meshio/blob/master/CHANGELOG.md
=> Fix tests - meshio updates

cpp/dolfinx/fem/ElementDofLayout.cpp, cpp/dolfinx/fem/ElementDofLayout.h, cpp/dolfinx/fem/utils.cpp
I've moved the conversion of the data from ffc to an Eigen Array out of ElementDofLayout so that there's no need to pass a pointer to the ffc data into the constructor.
=> Remove raw pointer

cpp/dolfinx/fem/DirichletBC.cpp, cpp/dolfinx/mesh/Partitioning.cpp
=> Replace std::inclusive_scan with std::partial_sum

python/test/unit/io/test_gmsh_io.py, python/test/unit/mesh/test_higher_order_mesh.py, python/test/unit/mesh/test_mesh_value_collection.py
Tests failing due to pygmsh/meshio problem. Re-enable when pygmsh is updated.
=> Disable pygmsh

cpp/dolfinx/fem/DofMapBuilder.cpp, cpp/dolfinx/mesh/PartitioningNew.cpp, cpp/dolfinx/mesh/PartitioningNew.h, python/dolfinx/wrappers/graph.cpp, python/dolfinx/wrappers/mesh.cpp, python/test/unit/mesh/test_mesh_utils.py
New, work-in-progress functionality that doesn't impinge on existing code.
=> Add function for fetching geometry data from remote process

cpp/dolfinx/fem/DofMapBuilder.cpp
=> Fix MPI communicator creation and destruction.

cpp/dolfinx/fem/utils.cpp
Remove code associated to former `keep_diagonal` case
=> Remove dead code in dolfinx::fem::create_matrix

.circleci/config.yml
=> Musical docker registry chairs

python/test/unit/io/test_gmsh_io.py, python/test/unit/mesh/test_higher_order_mesh.py, python/test/unit/mesh/test_mesh_value_collection.py
=> Revert "Disable pygmsh"

cpp/dolfinx/mesh/TopologyComputation.cpp
Improves some slow comparisons in `TopologyComputation.cpp`
```
master:
Compute entities of dim = 1                     |     2  12.842487  25.684974
Compute entities of dim = 2                     |     2   7.217708  14.435416
this branch:
Compute entities of dim = 1                |     2   4.072081   8.144163
Compute entities of dim = 2                |     2   3.012452   6.024905
```
=> Improve topology computation scalability

cpp/dolfinx/fem/DofMap.h, cpp/dolfinx/fem/PETScDMCollection.cpp, cpp/dolfinx/fem/assemble_matrix_impl.cpp, cpp/dolfinx/fem/assemble_matrix_impl.h, cpp/dolfinx/fem/assemble_scalar_impl.cpp, cpp/dolfinx/fem/assemble_vector_impl.cpp, cpp/dolfinx/function/Function.cpp, cpp/dolfinx/function/FunctionSpace.cpp, cpp/dolfinx/graph/AdjacencyList.h, cpp/dolfinx/mesh/Topology.cpp
Avoids the creation of temporaries
=> Optimise permutation data access in assemblers

.circleci/config.yml, python/test/unit/fem/test_fem_pipeline.py
=> Remove ordering from tests, and turn on tests up to order 3

cpp/dolfinx/fem/ElementDofLayout.cpp, cpp/dolfinx/fem/utils.cpp, python/test/unit/mesh/test_mesh_utils.py
Corrected the shape of the base permutations expected by and passed into the element dof layout, in line with #863.
=> Correct the shape of base_permutations

cpp/dolfinx/fem/FormIntegrals.cpp, python/test/unit/fem/test_assembler.py
This may change again if/when ghosting via vertex comes back.
=> Quick fix for interior integrals in parallel (mesh ghosted via facet)

.github/workflows/dockerimage.yml
- Handle foo/bar branch names for Dockerbuild
- Improve readability of cron string
=> Fix actions triggers

cpp/dolfinx/la/PETScKrylovSolver.cpp, cpp/dolfinx/la/PETScKrylovSolver.h, cpp/dolfinx/la/PETScMatrix.cpp, cpp/dolfinx/la/PETScOperator.cpp, cpp/dolfinx/la/PETScOperator.h
Unused code in the PETSc KSP wrappers.
=> Remove some questionable and unused code

cpp/dolfinx/io/XDMFFile.cpp
Using mesh::create instead of reinventing the wheel.
=> Remove duplicate code in xdmf reader

.github/workflows/dockerimage.yml
=> Do not build docker images on forks

.circleci/config.yml, cpp/dolfinx/io/XDMFFile.cpp, cpp/dolfinx/io/XDMFFile.h, python/demo/mixed-elasticity-sc/static-condensation-elasticity.py, python/dolfinx/common.py, python/dolfinx/io.py, python/dolfinx/plotting.py, python/test/unit/fem/test_assembler.py, python/test/unit/fem/test_custom_assembler.py, python/test/unit/fem/test_nonlinear_assembler.py, python/test/unit/io/test_vtk.py, python/test/unit/io/test_xdmf_mesh.py
Also parameterize more test to run in ghost and non-ghost modes.
=> Add ghosting option when reading a mesh from file

cpp/dolfinx/io/VTKWriter.cpp
Now throwing an error if one tries to write a mesh entity to file with dim<tdim, as no code path points to such a function call. When VTK is re-implemented, it should be able to write higher order mesh entities to file with the same code path as first order entities.
=> Remove cell degree from vtkwriter by defaulting to arbitrary Lagrange cell types

cpp/dolfinx/io/XDMFFile.cpp, cpp/dolfinx/io/XDMFFile.h, python/demo/cahn-hilliard/demo_cahn-hilliard.py, python/dolfinx/io.py, python/dolfinx/wrappers/io.cpp, python/test/unit/io/test_xdmf_function.py, python/test/unit/io/test_xdmf_mesh.py, python/test/unit/io/test_xdmf_meshdata.py, python/test/unit/io/test_xdmf_meshtags.py
This breaks master, need to give it more care.
=> Revert "Save XML file only on XDMFFile.close()"

cpp/dolfinx/io/cells.cpp
Missed this one when rewriting @jorgensd 's code into common api.
=> Add triangle10 for perm_gmsh

cpp/dolfinx/common/IndexMap.cpp, cpp/dolfinx/common/IndexMap.h, cpp/dolfinx/common/MPI.cpp, cpp/dolfinx/common/MPI.h, cpp/dolfinx/fem/DofMap.cpp, cpp/dolfinx/fem/DofMapBuilder.cpp, cpp/dolfinx/fem/FormIntegrals.cpp, cpp/dolfinx/fem/assemble_vector_impl.h, cpp/dolfinx/fem/utils.cpp, cpp/dolfinx/graph/Partitioning.cpp, cpp/dolfinx/la/SparsityPattern.cpp, cpp/dolfinx/mesh/Topology.cpp, cpp/dolfinx/mesh/Topology.h, cpp/dolfinx/mesh/TopologyComputation.cpp, cpp/dolfinx/refinement/ParallelRefinement.cpp, cpp/dolfinx/refinement/ParallelRefinement.h, cpp/test/unit/common/index_map.cpp, python/dolfinx/wrappers/common.cpp
Code, naming and doc improvements.
=> Improve IndexMap communication

cpp/dolfinx/function/CMakeLists.txt, cpp/dolfinx/function/Function.cpp, cpp/dolfinx/function/Function.h, cpp/dolfinx/function/FunctionSpace.cpp, cpp/dolfinx/function/FunctionSpace.h, cpp/dolfinx/function/interpolate.h, python/demo/elasticity/demo_elasticity.py, python/dolfinx/function.py, python/dolfinx/wrappers/function.cpp, python/test/unit/la/test_krylov_solver.py, python/test/unit/la/test_nullspace.py
This is helpful in making FunctionSpace unaware of Function.
=> Make interpolate functions free functions

.github/workflows/spack.yml
Update have been merged upstream
=> Point test to main spack repo

.github/workflows/spack.yml
=> Actions updates for Spack

cpp/dolfinx/common/MPI.h, cpp/dolfinx/fem/DofMapBuilder.h, cpp/dolfinx/fem/SparsityPatternBuilder.h, cpp/dolfinx/graph/BoostGraphOrdering.h, cpp/dolfinx/graph/KaHIP.h, cpp/dolfinx/graph/ParMETIS.h, cpp/dolfinx/graph/Partitioning.h, cpp/dolfinx/graph/SCOTCH.h, cpp/dolfinx/mesh/GraphBuilder.h, cpp/dolfinx/mesh/Partitioning.h, cpp/dolfinx/mesh/PermutationComputation.h, cpp/dolfinx/mesh/TopologyComputation.h, cpp/dolfinx/mesh/cell_types.h, cpp/dolfinx/refinement/PlazaRefinementND.h
Some classes do not define a new data type/object and have only static member functions. I think that it's a better pattern to use namespaces for free/helper functions.
The idea of this PR is to discuss whether these changes are desirable, and if agreed, I can apply the same pattern where it is reasonable.
=> Use namespaces instead of classes with only static members

cpp/demo/hyperelasticity/main.cpp, cpp/demo/poisson/main.cpp, python/demo/elasticity/demo_elasticity.py, python/demo/poisson/demo_poisson.py
=> Make floating point comparison in demos more robust

.github/workflows/docker-end-user.yml
Try and get cache working on lab build, fix build sanity check.
=> Further Docker/CI fixes

python/test/unit/fem/test_expression_evaluation.py
This corrects the test in line with FEniCS/ffcx#281
=> Transpose data in expression test

.github/workflows/spack.yml
Deals with some changes to the Actions VM configuration.
=> Actions VM updates for Spack

docker/Dockerfile
Seems to be the cause of various crashes, needs further investigation.
=> Revert PR #1162 PETSc 3.14 bump 

cpp/cmake/modules/FindSLEPc.cmake
=> fix typo introduced to FindSLEPc.cmake

cpp/dolfinx/io/xdmf_utils.cpp
=> Fix igi_to_vertex mapping in xmdf_utils::extract_local_entities

cpp/dolfinx/function/Function.h, cpp/dolfinx/la/PETScOperator.cpp, cpp/dolfinx/la/PETScOperator.h, cpp/dolfinx/la/PETScVector.cpp, cpp/dolfinx/la/PETScVector.h
Closes #1233 .
Inspired by #1211 , this is not a bug fix but just a restyling for PETScVector and PETScOperator.
=> Restyle move operators

python/dolfinx/wrappers/nls.cpp
Parameter missing in python + a fixed a typo
=> Expose relaxation parameter + typo fix

cpp/dolfinx/common/SubSystemsManager.cpp, cpp/dolfinx/common/loguru.cpp, cpp/dolfinx/common/loguru.hpp
Produces nice stacktraces in DEBUG mode.
=> Bump loguru version, catch signals in DEBUG

.github/workflows/ccpp.yml, README.md
Still an open issue with Python style: https://fenics.github.io/docs/dolfinx/python/
Before merging: Add back in clause to only execute on master branch.
=> Push DOLFINX documentation to GitHub Pages

cpp/cmake/modules/FindKaHIP.cmake, cpp/dolfinx/graph/KaHIP.cpp, cpp/dolfinx/graph/KaHIP.h, docker/Dockerfile
Fix #1058 and bump KaHIP version to v3.10
=> Update FindKaHIP and bump KaHIP version to v3.10

docker/Dockerfile
I must have removed line 156  by mistake.
=> Fix docker build (install kahip)

.github/workflows/intel.yml, cpp/dolfinx/common/MPI.cpp, cpp/dolfinx/graph/AdjacencyList.h
Only tests C++ interface due to Intel compiler bugs that prevent build of Python/pybind11 interface.
=> Add Actions testing with Intel compiler

cpp/dolfinx/fem/assemble_vector_impl.h
=> Add some missing block sizes

docker/Dockerfile
- Update some dependency version in Dockerfile
- Add Hypre to 32-bit complex build of PETSc
- Build petsc4py from PETSc src tree
=> Bump versions in Dockerfile

cpp/dolfinx/common/MPI.h, cpp/dolfinx/fem/assemble_matrix_impl.h, cpp/dolfinx/fem/assemble_scalar_impl.h, cpp/dolfinx/fem/assemble_vector_impl.h, cpp/dolfinx/fem/utils.cpp, cpp/dolfinx/io/xdmf_mesh.cpp, cpp/dolfinx/io/xdmf_utils.cpp, cpp/dolfinx/la/PETScMatrix.cpp
Gives small performance improvement.
=> Some type and function simplifications

python/test/unit/fem/test_ghost_mesh_assembly.py
Reactivate some previously failing tests
=> Reactivate ghostmode assembly tests

cpp/dolfinx/mesh/graphbuild.cpp
Fixes unused variable warning in release builds.
=> Move statement inside debug block

docker/Dockerfile
=> Update numpy with pip in dockerfile

cpp/dolfinx/graph/partition.cpp, cpp/dolfinx/graph/scotch.cpp, cpp/dolfinx/mesh/topologycomputation.cpp
Free and compress some storage in mesh graph creation function.
=> Force some memory to be freed in graph creation

cpp/dolfinx/fem/FiniteElement.cpp, cpp/dolfinx/fem/FiniteElement.h, cpp/dolfinx/fem/FunctionSpace.cpp, cpp/dolfinx/fem/dofmapbuilder.cpp, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/graph/partition.cpp, cpp/dolfinx/graph/scotch.cpp, cpp/dolfinx/mesh/topologycomputation.cpp
Get interpolation data directly from basix
Merged latest master into this
=> Get interpolation data directly from basix

cpp/dolfinx/mesh/Mesh.cpp, cpp/dolfinx/mesh/Mesh.h, cpp/dolfinx/mesh/utils.cpp, cpp/dolfinx/mesh/utils.h, python/dolfinx/wrappers/mesh.cpp, python/test/unit/mesh/test_cell.py, python/test/unit/mesh/test_face.py, python/test/unit/mesh/test_mesh.py
The removed code was out-of-date with many other changes and could compute wrong results.
=> Remove broken cell geometry functions

cpp/dolfinx/common/IndexMap.cpp, cpp/dolfinx/mesh/Topology.cpp
=> Remove inclusive_scan, does not work on GCC before 9.3.0.

docker/Dockerfile
=> Add package libxft2

docker/Dockerfile
Fixes error if build directory already exists.
=> Add -p to build mkdir instructions

cpp/dolfinx/common/IndexMap.cpp, cpp/dolfinx/common/IndexMap.h, cpp/dolfinx/common/MPI.h, cpp/dolfinx/graph/partition.h, cpp/dolfinx/la/PETScVector.h
Cray Compiler is less forgiving about missing headers...
=> Add missing headers

docker/Dockerfile
Use the new two-stage installation
=> Update basix installation

cpp/dolfinx/fem/FunctionSpace.cpp, python/test/unit/fem/test_dof_coordinates.py
=> Apply dof transformations inside tabulate_dof_coordinates

cpp/dolfinx/common/IndexMap.cpp, cpp/dolfinx/common/IndexMap.h, cpp/dolfinx/fem/Form.h, cpp/dolfinx/fem/dofmapbuilder.cpp, cpp/dolfinx/mesh/Topology.cpp, cpp/dolfinx/mesh/utils.cpp
- expose `shared_disp` (offsets in the index map).
Can one propose a better name `shared indices`?
=> Use an AjacencyList for shared indices in IndexMap

python/demo/cahn-hilliard/demo_cahn-hilliard.py, python/demo/poisson/demo_poisson.py, python/demo/pyvista/demo_pyvista.py
start_xvfb now part of main module. Makes code look nicer
=> Pyvista 0.29 updates

docker/Dockerfile, python/demo/gmsh/demo_gmsh.py
=> Revert gmsh change

python/test/unit/fem/test_fem_pipeline.py
These are now supported in FFCx & Basix
=> Turn on NCE/F and RTCE/F tests

cpp/demo/hyperelasticity/main.cpp, cpp/demo/poisson/main.cpp, cpp/dolfinx/fem/DirichletBC.cpp, cpp/dolfinx/fem/DirichletBC.h, cpp/dolfinx/fem/Function.h, cpp/dolfinx/fem/FunctionSpace.cpp, cpp/dolfinx/fem/FunctionSpace.h, cpp/dolfinx/fem/interpolate.h, python/dolfinx/wrappers/array.h, python/dolfinx/wrappers/fem.cpp
This makes the interface consistent with interpolation, and allows really helpful shortcuts.
=> Use xtensor in geometric dof search

.github/workflows/pyvista.yml, docker/Dockerfile
Currently pyvistaqt is incompatible with the latest pyvista release, as reported at https://github.com/pyvista/pyvistaqt/issues/105.
Therefore, we should currently fix the version until a fix has been created.
=> Fix pyvista version

cpp/dolfinx/geometry/utils.cpp, cpp/dolfinx/geometry/utils.h, python/dolfinx/wrappers/geometry.cpp
Same as all other functions in geometry does.
=> Use xtl span in create midpoint tree

cpp/dolfinx/fem/FiniteElement.cpp, cpp/dolfinx/fem/FiniteElement.h, cpp/dolfinx/fem/Form.h, cpp/dolfinx/fem/Function.h, cpp/dolfinx/fem/FunctionSpace.cpp, cpp/dolfinx/fem/assemble_matrix_impl.h, cpp/dolfinx/fem/assemble_vector_impl.h, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/fem/utils.cpp, cpp/dolfinx/fem/utils.h, python/dolfinx/fem/function.py, python/dolfinx/wrappers/fem.cpp, python/test/unit/fem/test_dof_permuting.py
Merging into #1568.
Merging here rather than locally so I can be sure that test pass before changing the other PR
=> Permute DOF numbering for elements where this can be done

cpp/dolfinx/mesh/graphbuild.cpp
=> Just warn about topology instead of throwing error

.github/workflows/spack.yml, README.md
=> Update spack instructions

cpp/dolfinx/common/IndexMap.cpp, cpp/dolfinx/common/IndexMap.h
Simplifies some code, removes memory allocation in scatter.
=> Simplification in IndexMap for scattering

python/dolfinx/mesh.py
=> Fix domain id of refined meshes

python/dolfinx/wrappers/fem.cpp, python/test/unit/fem/test_expression.py
Required for fast point evaluation for time dependent problems.
=> Expose map pull_back and test it with dolfinx.Expression

cpp/dolfinx/fem/FiniteElement.cpp, python/test/unit/fem/test_fem_pipeline.py
Many more complex finite element formulations are currently untested in FEniCSx.
This test aims to add a test of a complete mixed HHJ/Regge biharmonic problem.
=> HHJ/Regge Biharmonic Integration Tests

docker/Dockerfile
- Install pybind11 with pip
- Bump PETSc patch version
=> Dockerfile updates

docker/Dockerfile
=> Pin numpy to numba compatible version

python/test/unit/fem/test_dof_permuting.py
It appears that whatever was causing this to fail previously is now fixed.
Close #1134.
=> Enable xfailed test

.github/workflows/ccpp.yml, cpp/dolfinx/common/IndexMap.h, cpp/dolfinx/common/MPI.cpp, cpp/dolfinx/common/sort.h, cpp/dolfinx/mesh/Topology.cpp
The code is necessarily quite technical, so the extra comments should be helpful in the future.
=> Add more documentation and comments to topology creation

cpp/dolfinx/fem/CoordinateElement.cpp, cpp/dolfinx/mesh/cell_types.cpp, cpp/dolfinx/mesh/cell_types.h
This allows FEniCS/Basix#270 to be done.
=> Remove strings from DOLFINx <-> Basix cell type conversion

cpp/dolfinx/mesh/Mesh.cpp
Fixes incorrect offset computation in `reorder_list()`. This is not picked up when all entries are the same size.
=> Correct offset computation for reordering

python/test/unit/common/test_index_map.py
Add a new test to https://github.com/FEniCS/dolfinx/pull/1680 to check that ghosts in the sub index map are mapped properly.
=> Extra test for dokken/compress_index_map

.github/workflows/ccpp.yml, python/demo/elasticity/demo_elasticity.py, python/demo/mixed-elasticity-sc/static-condensation-elasticity.py, python/demo/stokes-taylor-hood/demo_stokes-taylor-hood.py, python/dolfinx/fem/assemble.py, python/dolfinx/fem/problem.py, python/dolfinx/wrappers/array.h, python/dolfinx/wrappers/fem.cpp, python/test/unit/fem/test_assembler.py, python/test/unit/fem/test_fem_pipeline.py, python/test/unit/fem/test_nonlinear_assembler.py, python/test/unit/mesh/test_higher_order_mesh.py, python/test/unit/nls/test_newton.py
The adds support to the Python interface that has existed in the C++ interface.
=> Support passing of form coefficients to assemblers from Python

cpp/dolfinx/fem/utils.cpp, cpp/dolfinx/fem/utils.h
=> Improved form creation error checking

cpp/dolfinx/common/MPI.cpp, cpp/dolfinx/mesh/Topology.cpp
Performance of in-place calls can be poor with some implementations. Not real benefit to in place calls for the cases where it has been used.
=> Remove in-place MPI calls

.github/workflows/pyvista.yml
Fixing failing visualization test
=> Try fixing pyvistaqt by pinning version

cpp/dolfinx/graph/partition.cpp
I'm not sure how this got missed, or even how it was building with it in.
=> Remove stray header

python/test/unit/fem/test_dof_permuting.py
These can be removed now that https://github.com/FEniCS/dolfinx/issues/1814 is fixed
=> Remove avg from tests

cpp/dolfinx/generation/RectangleMesh.cpp, cpp/dolfinx/generation/RectangleMesh.h, python/dolfinx/generation.py, python/dolfinx/wrappers/generation.cpp, python/test/unit/mesh/test_mesh.py
=> Add diagonal enum for RectangleMesh

cpp/dolfinx/mesh/cell_types.cpp, cpp/dolfinx/mesh/utils.cpp, cpp/dolfinx/mesh/utils.h, cpp/dolfinx/refinement/plaza.cpp, cpp/dolfinx/refinement/plaza.h, cpp/dolfinx/refinement/refine.cpp, cpp/dolfinx/refinement/refine.h, cpp/dolfinx/refinement/utils.cpp, cpp/dolfinx/refinement/utils.h, python/dolfinx/mesh.py, python/dolfinx/wrappers/refinement.cpp
=> Update refinement docs

cpp/dolfinx/refinement/plaza.cpp, cpp/dolfinx/refinement/plaza.h, cpp/dolfinx/refinement/utils.cpp, cpp/dolfinx/refinement/utils.h
The functionality has no tests, hence issues with recent changes were not picked up by CI. See #1851.
=> Revert some change to refine by marker

python/dolfinx/fem/__init__.py, python/dolfinx/mesh.py
Convenience functions required to pack coefficients and constants, as well as exposing function that is used for boundary condition facet marking.
=> Expose some functionality from cpp layer and assembly.

.github/workflows/ccpp.yml, docker/Dockerfile
For information, does not change any files or terminate on failure.
=> Add non-blocking clang-format call to CI

python/dolfinx/fem/problem.py
Old documentation has been deleted and moved
=> Change dead petsc link to petsc4py docs

cpp/dolfinx/geometry/gjk.cpp
As discussed with @chrisrichardson this cannot happen in practice but the end code block should be inside the switch statement.
=> Fix potential out-of-bounds error, not built locally.

cpp/dolfinx/geometry/utils.cpp, python/test/unit/geometry/test_bounding_box_tree.py
This reverts commit 2124fdcc596b7730a40f0c6c2568acd784661bb1.
=> Revert "Fix #1558 (#1879)"

.github/workflows/docker.yml
=> Update docker basic test to make images build

cpp/demo/poisson/main.cpp, cpp/dolfinx/mesh/generation.cpp, cpp/dolfinx/mesh/generation.h, cpp/test/unit/io.cpp, cpp/test/unit/mesh/distributed_mesh.cpp, python/demo/poisson/demo_poisson.py, python/demo/stokes-taylor-hood/demo_stokes-taylor-hood.py, python/dolfinx/mesh.py, python/dolfinx/wrappers/mesh.cpp, python/test/unit/fem/test_assembler.py, python/test/unit/fem/test_fem_pipeline.py, python/test/unit/mesh/test_mesh.py, python/test/unit/ufl-jit-assemble-chain/test_assembly_derivatives.py
Discussed in #1873. Consistent with `create_interval` and `create_box`.
=> Change create_rectangle to take two dimensional points

python/dolfinx/fem/function.py, python/dolfinx/wrappers/la.cpp, python/test/unit/fem/test_function.py
=> Fix function copy option

cpp/dolfinx/mesh/graphbuild.cpp
=> Fix narrowing of global indices in graph builder

cpp/dolfinx/mesh/Topology.cpp
Resolves scalability issue, due to incorrect computation of global space
=> Global range bugfix

cpp/dolfinx/fem/Function.h, cpp/dolfinx/fem/interpolate.h, python/dolfinx/fem/function.py, python/dolfinx/wrappers/fem.cpp, python/test/unit/fem/test_interpolation.py
This sets the cells that interpolation is performed over.
=> Add optional `cells` argument in interpolate functions

python/doc/Makefile
See https://github.com/sphinx-doc/sphinx/issues/4961. Revert this change when resolved.
=> Disable Sphinx warnings as errors.

cpp/dolfinx/mesh/Mesh.cpp
Uses more scoping in topology processing.
=> Further memory reductions in mesh construction

python/dolfinx/wrappers/la.cpp, python/test/unit/la/test_sparsity_pattern.py
https://github.com/FEniCS/dolfinx/pull/1930/files#diff-64c3a7f32a8e3c7fa47f018c195fa277cffb6b8b00079199fee7dcafd8403c0dR80
forgot to propagate changes to the Python interface.
=> Fix broken `SparsityPattern` Python interface

cpp/cmake/templates/DOLFINXConfig.cmake.in
=> SLEPc cmake fix

cpp/dolfinx/io/ADIOS2Writers.cpp
Code syntax simplifications. No functional changes.
=> Simplify ADIOS2 writers

cpp/demo/interpolation-io/main.cpp, cpp/dolfinx/fem/FiniteElement.cpp, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/la/MatrixCSR.h, cpp/dolfinx/la/petsc.cpp, python/dolfinx/mesh.py, python/dolfinx/wrappers/common.cpp, python/test/unit/fem/test_interpolation.py
Block sizes were not correctly handled. Change fixes block size and adds more tests.
=> Fix bug in interpolation of sub-functions

python/demo/elasticity/demo_elasticity.py
Issue when running with MPI by @cmaurini﻿
=> Add missing ghost update to elasticity demo

python/dolfinx/plot.py
Also addresses changes in API after VTK modernization
=> Various clean-ups

cpp/dolfinx/fem/assemble_matrix_impl.h, cpp/dolfinx/fem/assemble_scalar_impl.h, cpp/dolfinx/fem/assemble_vector_impl.h, cpp/dolfinx/fem/dofmapbuilder.cpp, cpp/dolfinx/graph/AdjacencyList.h, cpp/dolfinx/graph/partition.cpp, python/dolfinx/fem/assemble.py, python/test/unit/fem/test_assembler.py, python/test/unit/mesh/test_mesh.py
Improves a few checks and fixes some small details to allow computations when some MPI ranks do not have any cells.
=> Allow creation of, and operations on, a `Mesh` where some ranks have no cells.

python/dolfinx/plot.py
=> Fix facet plotting

python/dolfinx/fem/function.py
=> Remove `Function.ufl_evaluate`

python/setup.py
Doubt we can run with 2021.1.0!
=> Bump UFL requirement

cpp/dolfinx/common/MPI.cpp, cpp/dolfinx/common/utils.h, cpp/dolfinx/io/xdmf_utils.cpp, cpp/dolfinx/mesh/MeshTags.h, cpp/dolfinx/mesh/Topology.cpp, cpp/dolfinx/mesh/Topology.h, python/setup.py
Simplify the steps and better document.
=> Simplify MeshTag construction

cpp/demo/poisson/main.cpp, cpp/dolfinx/common/sort.h, cpp/dolfinx/mesh/Mesh.cpp, cpp/dolfinx/mesh/graphbuild.cpp, cpp/dolfinx/mesh/graphbuild.h, cpp/dolfinx/mesh/topologycomputation.cpp, cpp/test/unit/common/sort.cpp
This is a simplification step that will support more performance improvements in the future.
=> Topology computation improvements, removes xtensor in topology computation

python/dolfinx/fem/petsc.py
=> Set PETSc options prefix for matrix and vector in `fem.petsc.LinearProblem`

cpp/dolfinx/fem/CoordinateElement.cpp, cpp/dolfinx/fem/CoordinateElement.h, cpp/dolfinx/fem/discreteoperators.h, cpp/dolfinx/la/SparsityPattern.h, cpp/dolfinx/mesh/graphbuild.cpp, python/dolfinx/wrappers/fem.cpp, python/test/unit/fem/test_discrete_operators.py
Creation of interpolation matrix A  from space V->W such that
u \in V, w in W such that  Au = w.
Not tested with AMS solvers yet, as pybindings are missing.
=> Discrete interpolation matrix

python/dolfinx/fem/function.py
=> Fix typo - proposed by @srosenbu

cpp/dolfinx/fem/Expression.h, python/test/unit/fem/test_expression.py
=> Fix expression evaluation on subset of cells

python/test/unit/fem/test_assemble_submesh.py
This PR improves the tests for assembling forms over a submesh by testing additional functionality, such as applying boundary conditions.
=> Better submesh assembly tests

python/test/unit/fem/test_fem_pipeline.py
=> Add serendipity pipeline tests

python/test/unit/fem/test_fem_pipeline.py
Now tests rotated Regge (H(curl curl) -> S -> H(div div)) and classical HHJ (H(div div)).
=> Add HHJ element to FEM pipeline test

.github/workflows/docker.yml
=> Add possibility to manually trigger Docker builds e.g. on release.

cpp/demo/poisson_matrix_free/main.cpp, cpp/dolfinx/la/Vector.h, cpp/test/vector.cpp, python/dolfinx/wrappers/la.cpp
- Change return type of `la::norm`
-  return `double` for `Vector<double>` and `Vector<std::complex<double>>`
- return `float` for `Vector<float>` and `Vector<std::complex<float>>`
- Template tests ..
=> Use more free functions in `la/Vector.h`

cpp/dolfinx/common/math.h, cpp/dolfinx/fem/DirichletBC.cpp, cpp/dolfinx/fem/Function.h, cpp/dolfinx/fem/FunctionSpace.cpp, cpp/dolfinx/fem/FunctionSpace.h, cpp/dolfinx/fem/interpolate.cpp, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/geometry/BoundingBoxTree.cpp, cpp/dolfinx/geometry/utils.cpp, cpp/dolfinx/mesh/Mesh.cpp, cpp/dolfinx/mesh/utils.cpp, cpp/dolfinx/mesh/utils.h, cpp/dolfinx/refinement/utils.cpp, python/dolfinx/wrappers/fem.cpp, python/dolfinx/wrappers/mesh.cpp, python/setup.py, python/test/unit/mesh/test_mesh.py
Generally simpler and avoid hidden costs in the xtensor code.
=> Remove some xtensor from mesh utility code

cpp/dolfinx/common/Scatterer.cpp, cpp/dolfinx/common/Scatterer.h
Also:
+  Move non-templated code to cpp file.
=> Fix assertion in Scatterer

cpp/demo/interpolation-io/main.cpp
=> Fix comment in interpolation demo (C++)

python/dolfinx/fem/function.py
=> Remove unused and untested `form_degree`

docker/dolfinx-complex-mode, docker/dolfinx-real-mode
Fix python version in the source-mode scripts. Autodetected at runtime.
=> Fix python version in dolfinx-complex/real-mode

.github/workflows/intel.yml, cpp/CMakeLists.txt
Add option to specify how UFCx should be found.
=> Tighter control over ufcx discovery method

cpp/dolfinx/CMakeLists.txt
Ref discussion on slack. @massimiliano-leoni could you verify that this works for you?
=> Change pugixml CMake target to be backwards compatible

.circleci/config.yml, .github/workflows/ccpp.yml, .github/workflows/intel.yml, .github/workflows/redhat.yml, .github/workflows/sonarcloud.yml
Following geometry type changes.
=> Reset FFCx branch in CI

.github/workflows/spack.yml
=> Use gcc 10 in Spack CI

cpp/demo/interpolation-io/main.cpp, cpp/demo/poisson_matrix_free/main.cpp, cpp/dolfinx/common/math.h, cpp/dolfinx/fem/CoordinateElement.cpp, cpp/dolfinx/fem/CoordinateElement.h, cpp/dolfinx/fem/Expression.h, cpp/dolfinx/fem/FiniteElement.cpp, cpp/dolfinx/fem/FiniteElement.h, cpp/dolfinx/fem/Function.h, cpp/dolfinx/fem/FunctionSpace.cpp, cpp/dolfinx/fem/discreteoperators.h, cpp/dolfinx/fem/interpolate.cpp, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/fem/utils.h, cpp/dolfinx/graph/partition.h, cpp/dolfinx/io/ADIOS2Writers.cpp, cpp/dolfinx/io/vtk_utils.cpp, cpp/dolfinx/io/xdmf_utils.cpp, cpp/dolfinx/refinement/plaza.h, python/demo/demo_elasticity.py, python/dolfinx/fem/function.py, python/dolfinx/wrappers/fem.cpp, python/test/unit/fem/test_discrete_operators.py, python/test/unit/fem/test_dof_permuting.py, python/test/unit/fem/test_dofmap.py, python/test/unit/fem/test_expression.py, python/test/unit/fem/test_function_space.py, python/test/unit/fem/test_interpolation.py
Simplifies code, uncovered some bugs, and is faster.
Some later optimisation can be performed now that code is clearer.
=> Remove xtensor code from element code

python/dolfinx/fem/function.py
This type is causing mypy errors in the Basix workflows: eg https://github.com/FEniCS/basix/runs/7463416014?check_suite_focus=true
=> X is not a property

docker/Dockerfile
Bump ADIOS2, PETSc, pybind11 and pyvista versions.
=> Bump dependency versions in Dockerfile

python/demo/demo_tnt-elements.py
Increase quadrature degree so quadrature is exact.
=> Increase quadrature degree in custom element demo

cpp/dolfinx/mesh/utils.h
Stupidly minor comment change, but I think the current comment is the opposite of what is intended.
=> Extremely minor comment change

cpp/dolfinx/io/xdmf_utils.cpp
=> Make XDMF compatible with second order hexahedral meshes

cpp/dolfinx/common/defines.cpp
=> Remove unused include header

cpp/demo/hyperelasticity/main.cpp, cpp/demo/interpolation_different_meshes/main.cpp, cpp/demo/poisson_matrix_free/main.cpp, cpp/dolfinx/common/TimeLogManager.cpp, cpp/dolfinx/common/math.h, cpp/dolfinx/fem/Form.h, cpp/dolfinx/fem/assembler.h, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/fem/utils.h, cpp/dolfinx/geometry/utils.cpp, cpp/dolfinx/graph/AdjacencyList.h, cpp/dolfinx/graph/ordering.h, cpp/dolfinx/graph/partition.h, cpp/dolfinx/la/petsc.cpp, cpp/dolfinx/la/utils.h, cpp/dolfinx/mesh/utils.cpp, cpp/dolfinx/mesh/utils.h
The CI needs to be re-run once the Docker image has been rebuilt with the latest doxygen.
=> Work-arounds for latest doxygen

cpp/dolfinx/common/Scatterer.h, cpp/test/common/index_map.cpp
+ add test that it actually returns a vector.
=> Fix return of create_request_vector

.github/workflows/pyvista.yml, docker/Dockerfile
As https://github.com/pyvista/pyvista/issues/3274 is not resolved
=> Pin ipywidgets

.circleci/config.yml, .github/workflows/ccpp.yml, cpp/CMakeLists.txt, cpp/dolfinx/common/IndexMap.cpp, cpp/dolfinx/fem/ElementDofLayout.h, cpp/dolfinx/fem/FiniteElement.cpp, cpp/test/matrix.cpp, python/dolfinx/fem/petsc.py, python/test/unit/fem/test_expression.py, python/test/unit/fem/test_fem_pipeline.py, python/test/unit/fem/test_function.py, python/test/unit/fem/test_function_space.py, python/test/unit/io/test_vtk.py, python/test/unit/mesh/test_higher_order_mesh.py
Also sort some Python imports and make CI solvers more robust.
=> Print PETSc version during CMake config

cpp/CMakeLists.txt, cpp/cmake/scripts/generate-cmakefiles.py, cpp/cmake/templates/DOLFINXConfig.cmake.in, cpp/demo/hyperelasticity/CMakeLists.txt, cpp/demo/poisson/CMakeLists.txt, cpp/demo/poisson_matrix_free/CMakeLists.txt
=> Simplify PETSc complex scalar detection

cpp/CMakeLists.txt, cpp/cmake/modules/FindParMETIS.cmake
=> Revert CMake ranges requirement for ParMETIS

python/test/unit/common/test_timer.py
Linked to https://github.com/FEniCS/ufl/pull/139
=> Fixes deprecation warning in random

python/doc/source/demos.rst
This PR adds the `demo_axis.py` from https://github.com/FEniCS/dolfinx/pull/2339 in the documentation.
=> Add `demo_axis` in `demos.rst`

.github/workflows/macos.yml
Cannot use ADIOS2 from Homebrew.
=> Add ADIOS2 to macOS build

cpp/dolfinx/geometry/utils.cpp
There is a type error (should be `int` not `double`) for `initial_entity` and a few other things tidied up.
=> Fix some mistakes in BoundingBox

python/dolfinx/io/utils.py
- Remove false claim about time step from write_mesh, write_meshtags.
- Add note in write_function regarding what it does under the hood.
=> Improve XDMFFile docs

cpp/dolfinx/mesh/cell_types.cpp
Ref: https://fenicsproject.discourse.group/t/can-dolfinx-read-a-gmsh-file-containing-1d-mesh-of-an-ellipse/9765/7
=> Add point as cell type to be able to read in vertex tags

.circleci/config.yml, cpp/dolfinx/common/dolfinx_common.h, cpp/dolfinx/fem/assemble_scalar_impl.h, cpp/dolfinx/io/XDMFFile.cpp, cpp/dolfinx/io/xdmf_mesh.cpp, python/CMakeLists.txt, python/setup.py
Provides better support for parallel builds.
=> Default to ninja when building Python/pybind11 interface

docker/Dockerfile, python/demo/demo_cahn-hilliard.py, python/demo/demo_interpolation-io.py, python/demo/demo_navier_stokes.py, python/demo/demo_pml/demo_pml.py, python/demo/demo_static-condensation.py, python/demo/demo_stokes.py, python/demo/demo_tnt-elements.py, python/demo/demo_types.py, python/demo/demo_waveguide/demo_half_loaded_waveguide.py, python/dolfinx/fem/__init__.py, python/dolfinx/fem/forms.py, python/dolfinx/fem/function.py, python/dolfinx/geometry.py, python/dolfinx/io/__init__.py, python/dolfinx/io/gmshio.py, python/dolfinx/io/utils.py, python/dolfinx/mesh.py, python/test/conftest.py, python/test/unit/fem/test_custom_assembler.py, python/test/unit/fem/test_custom_jit_kernels.py, python/test/unit/fem/test_element_integrals.py, python/test/unit/fem/test_expression.py, python/test/unit/fem/test_interpolation.py, python/test/unit/geometry/test_bounding_box_tree.py, python/test/unit/io/test_xdmf_meshtags.py, python/test/unit/mesh/test_meshtags.py, python/test/unit/mesh/test_refinement.py
=> Remove clang from Dockerfile

cpp/demo/hyperelasticity/main.cpp, cpp/demo/interpolation-io/main.cpp, cpp/dolfinx/fem/CoordinateElement.cpp
Changes related to basix FiniteElement interface
=> Basix interface change

.github/ISSUE_TEMPLATE/bug_report.yml
Until https://github.com/github/roadmap/issues/277 has been resolved
=> Add more versions of DOLFINx to dropdown

python/dolfinx/fem/bcs.py, python/dolfinx/fem/function.py
The is something of an anti-pattern. Replace with `try`/`except`.
=> Remove some `isinstance`

python/dolfinx/plot.py
=> Fix call to dolfinx.cpp.io.extract_vtk_connectivity in dolfinx.io.create_vtk_mesh

cpp/dolfinx/la/Vector.h
This fixes a problem introduced in PR #2603.
=> Fix template parameters

python/dolfinx/plot.py
=> Fixes for mixed dimensional topology in dolfinx.io.create_vtk_mesh

cpp/dolfinx/fem/Expression.h, cpp/dolfinx/fem/Form.h, cpp/dolfinx/fem/Function.h, cpp/dolfinx/fem/assemble_matrix_impl.h, cpp/dolfinx/fem/assemble_scalar_impl.h, cpp/dolfinx/fem/assemble_vector_impl.h, cpp/dolfinx/fem/utils.h, python/dolfinx/wrappers/fem.cpp
=> Use `std::span` for Form domain indices

cpp/dolfinx/fem/FiniteElement.cpp
Support change in https://github.com/FEniCS/basix/pull/663.
=> Update for Basix type changes

cpp/dolfinx/fem/interpolate.h, python/test/unit/fem/test_interpolation.py
=> Fix for interpolation of a callable on cells subset

.github/workflows/docker-dev-test-env.yml, .github/workflows/docker-end-user.yml, docker/Dockerfile
Should be able to fix unreliable/broken image caching and reduce build times
=> Split Docker builds

cpp/dolfinx/graph/AdjacencyList.h, cpp/dolfinx/io/xdmf_mesh.h
Include `<cstdint>` in places where it is missing
=> Further fixes for gcc-13

python/dolfinx/fem/function.py, python/test/unit/fem/test_function_space.py
Ref: https://fenicsproject.discourse.group/t/triangle-elements-in-3d-broken-in-dolfinx/9426/17
=> Fix 3D manifolds from vector and tensorfunctionspace

cpp/dolfinx/geometry/BoundingBoxTree.h, cpp/dolfinx/io/VTKFile.cpp, cpp/dolfinx/io/VTKFile.h, cpp/dolfinx/io/XDMFFile.cpp, cpp/dolfinx/io/XDMFFile.h, cpp/dolfinx/io/xdmf_function.cpp, cpp/dolfinx/io/xdmf_function.h, cpp/dolfinx/io/xdmf_meshtags.h, cpp/dolfinx/mesh/Mesh.h, python/dolfinx/wrappers/io.cpp
This follows on from the support for multiple types.
=> Reduce code duplication

.github/workflows/pyvista.yml, docker/Dockerfile.end-user, python/demo/demo_pyvista.py
Ref: https://github.com/pyvista/pyvista/releases/tag/v0.40.0
=> Bump pyvista to 0.40.0

.github/workflows/redhat.yml, cpp/dolfinx/fem/discreteoperators.h, cpp/dolfinx/geometry/gjk.h, cpp/dolfinx/geometry/utils.h
Reverts #2697 due to failure on oneAPI CI.
=> Revert geometric tolerance changes 

.github/workflows/docker-oneapi-test-env.yml, docker/Dockerfile.oneapi, python/test/unit/fem/test_vector_function.py
See https://gitlab.com/petsc/petsc/-/merge_requests/6705.
=> Use PETSc release version in oneAPI docker file

cpp/dolfinx/graph/AdjacencyList.h, cpp/dolfinx/graph/partition.h, cpp/dolfinx/mesh/Topology.h, cpp/dolfinx/mesh/generation.h, cpp/dolfinx/mesh/topologycomputation.h, cpp/dolfinx/mesh/utils.h, python/dolfinx/mesh.py, python/dolfinx/wrappers/mesh.cpp
Trivial partitioner does no distribution of cells.
Fixes #101.
=> Allow trivial (null) cell partitioner

python/dolfinx/io/utils.py
Making it similar to all other code (and makes life easier with complicated paths).
=> Add paths to typing of VTX and Fides

cpp/dolfinx/fem/utils.cpp
Small change that wasn't committed.
=> Minor changes left out of #2742

python/test/unit/fem/test_expression.py
See https://github.com/FEniCS/ufl/issues/204
=> Stop using deprecated UFL initialisation

python/dolfinx/wrappers/fem.cpp
=> Add missing templating of inverse transform

python/dolfinx/io/gmshio.py
=> Revise a `gmshio` docstring

python/dolfinx/wrappers/fem.cpp
Required for: https://github.com/jorgensd/adios4dolfinx/pull/32
=> Add complex wrappers for equivalent floating type for exposed dof transformations

.github/ISSUE_TEMPLATE/config.yml
See https://github.com/francesco-ballarin/dolfinx-issue-template/issues/new/choose for a preview of the resulting four issue types.
=> Add two more cases to GitHub ISSUE_TEMPLATE: installation and general questions

.github/workflows/docker-end-user.yml
Fixes #2818
Apologies, I missed replacing occurrences in the `.github` folder ;)
the docker workflow was manually testing in https://github.com/FEniCS/dolfinx/actions/runs/6542521991 with success status
=> Fix docker workflow after removal of `fem.FunctionSpace` function

cpp/dolfinx/io/ADIOS2Writers.h
=> Complex variables stored correctly in VTXWriter

INSTALL, README.md, python/README.rst, python/doc/source/installation.rst
For the new scikit-build-core based install.
=> Update install instructions.

.github/workflows/pyvista.yml, python/demo/demo_pyvista.py
Tested in https://github.com/FEniCS/dolfinx/actions/runs/6756026441
=> Fix `pyvista` demo and workflow

.github/workflows/docker-end-user.yml
In relation to #2846 and #2861
=> Try smaller ARM runner with nanobind

README.md, python/test/unit/fem/test_quadrature_elements.py
Add code from https://github.com/FEniCS/ffcx/pull/622 as a test
=> Add test of quadrature element

python/test/unit/fem/test_function_space.py, python/test/unit/fem/test_quadrature_elements.py, python/test/unit/fem/test_symmetric_tensor.py
Add a test to check that symmetric elements are correct.
Fixes https://github.com/FEniCS/dolfinx/issues/2750
=> Add test of symmetric tensor elements

cpp/dolfinx/nls/NewtonSolver.cpp, cpp/dolfinx/nls/NewtonSolver.h, python/dolfinx/wrappers/petsc.cpp, python/test/unit/nls/test_newton.py
See discussion https://github.com/wjakob/nanobind/discussions/361.
Fixes #2898.
=> Work-around nanobind issue with `std::function`

.github/ISSUE_TEMPLATE/bug_report.yml
Add summary box and update versions
=> Update GH bug template

cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/fem/petsc.h, cpp/dolfinx/la/petsc.cpp, cpp/dolfinx/la/petsc.h, python/demo/demo_mixed-poisson.py, python/dolfinx/wrappers/petsc.cpp
Also some minor interface simplifications.
=> Implementation performance improvements when concatenating function spaces for PETSc

python/test/unit/fem/test_expression.py
See also https://github.com/FEniCS/ffcx/pull/643
=> Replace deprecated ffcx.element_interface.QuadratureElement with basix.ufl.quadrature_element

cpp/dolfinx/fem/DofMap.h, cpp/dolfinx/io/ADIOS2Writers.h, python/dolfinx/wrappers/mesh.cpp
This raises an error for the issue reported in #2929. The check has non-trivial cost, so is performed in debug mode only.
This doesn't fix the issue in #2929, but tests a precondition.
=> Add dofmap consistency check for `VTXWriter` and `FidesWriter`

README.md
Made a mistake last time, correction.
=> Another update to Spack

cpp/dolfinx/fem/dofmapbuilder.cpp, python/dolfinx/wrappers/fem.cpp
Some updates to `dofmapbuilder.cpp` aiming towards mixed topology support. 
Internal changes, which should not affect any user code.
=> Dofmap builder preparation for mixed topology

python/doc/source/conf.py, python/dolfinx/mesh.py, python/pyproject.toml
Small changes to get ruff checks to pass.
=> Updates for ruff

python/dolfinx/mesh.py
=> Remove dead code in mesh.py

cpp/dolfinx/fem/utils.h, cpp/test/io.cpp, python/dolfinx/wrappers/io.cpp
Follows on from https://github.com/FEniCS/ffcx/issues/666.
=> Check that UFCx kernel functions are not `null`

cpp/dolfinx/fem/CoordinateElement.cpp, cpp/dolfinx/fem/CoordinateElement.h, cpp/dolfinx/fem/Expression.h, cpp/dolfinx/fem/FiniteElement.cpp, cpp/dolfinx/fem/FiniteElement.h, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/fem/utils.cpp, cpp/dolfinx/fem/utils.h, cpp/dolfinx/la/SparsityPattern.cpp, cpp/dolfinx/la/SparsityPattern.h, cpp/dolfinx/la/petsc.h, python/dolfinx/wrappers/fem.cpp
No point passing by reference.
=> Always pass `std::span` by value

cpp/dolfinx/mesh/utils.h
=> Documentation fix

.github/workflows/macos.yml
- Switch to ARM (M1) runner with macOS.
- Update setup-python action.
- Add full unit test run.
=> Switch macOS CI to arm M1

cpp/dolfinx/fem/DofMap.cpp, cpp/dolfinx/fem/Expression.h, cpp/dolfinx/fem/Function.h, cpp/dolfinx/fem/FunctionSpace.h, cpp/dolfinx/fem/assemble_matrix_impl.h, cpp/dolfinx/fem/assemble_scalar_impl.h, cpp/dolfinx/fem/assemble_vector_impl.h, cpp/dolfinx/fem/discreteoperators.h, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/geometry/utils.h, cpp/dolfinx/io/ADIOS2Writers.h, cpp/dolfinx/io/vtk_utils.h, cpp/dolfinx/io/xdmf_function.cpp, cpp/dolfinx/io/xdmf_mesh.cpp, cpp/dolfinx/mesh/Geometry.h, cpp/dolfinx/mesh/utils.h, cpp/dolfinx/refinement/plaza.h, cpp/dolfinx/refinement/utils.h, python/dolfinx/wrappers/fem.cpp
Ready to merge once https://github.com/FEniCS/basix/pull/792 is merged.
=> Updates for `mdspan`

cpp/dolfinx/fem/utils.h, python/test/unit/fem/test_assemble_submesh.py
This is the last PR needed to support mixed-domain problems of codimension 0.
=> Add support for mixed-domain coefficient packing

cpp/dolfinx/geometry/utils.h, cpp/dolfinx/io/xdmf_utils.h, cpp/dolfinx/mesh/utils.h
Closes #3109.
Debugged and solved together with @jorgensd .
=> Fix determine point ownership when majority of points in receiving mesh is outside in-mesh 

cpp/dolfinx/io/VTKFile.cpp
=> Move piece node outside of function loop in VTKFile

cpp/CMakeLists.txt, cpp/cmake/templates/DOLFINXConfig.cmake.in, python/dolfinx/__init__.py, python/test/unit/fem/test_expression.py, python/test/unit/fem/test_nonlinear_assembler.py
=> Remove legacy detection of PETSc scalar type

cpp/dolfinx/fem/CoordinateElement.cpp, cpp/dolfinx/fem/FiniteElement.cpp, cpp/dolfinx/fem/FiniteElement.h, cpp/dolfinx/fem/Function.h, cpp/dolfinx/fem/FunctionSpace.h, cpp/dolfinx/fem/assemble_matrix_impl.h, cpp/dolfinx/fem/assemble_vector_impl.h, cpp/dolfinx/fem/discreteoperators.h, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/fem/utils.h, cpp/dolfinx/io/vtk_utils.h
Updates for https://github.com/FEniCS/basix/pull/802
=> Updates for Basix function changes

RELEASE.md
Things noticed this release cycle.
=> Updates and clarifications in release notes

README.md
=> Remove CircleCI badge from `README.md`

docker/Dockerfile.test-env
=> Add petsc4py build requirements

.github/workflows/oneapi.yml, docker/Dockerfile.oneapi
Remove pip install from Dockerfile
=> Simplify oneAPI CI

.github/workflows/spack.yml
Required by Spack for some packages.
=> Install unzip package in CI for Spack

python/dolfinx/utils.py
Users were given little information to help move forwards with fixing PETSc lib loading issue.
=> Add more output to errors raised on PETSc lib import.

cpp/demo/mixed_topology/main.cpp, cpp/dolfinx/common/IndexMap.cpp, cpp/dolfinx/common/MPI.h, cpp/dolfinx/common/Scatterer.h, cpp/dolfinx/common/utils.h, cpp/dolfinx/fem/DirichletBC.cpp, cpp/dolfinx/fem/DirichletBC.h, cpp/dolfinx/fem/Form.h, cpp/dolfinx/fem/dofmapbuilder.cpp, cpp/dolfinx/fem/interpolate.h, cpp/dolfinx/geometry/utils.h, cpp/dolfinx/graph/ordering.cpp, cpp/dolfinx/graph/partition.cpp, cpp/dolfinx/graph/partitioners.cpp, cpp/dolfinx/io/xdmf_utils.cpp, cpp/dolfinx/la/MatrixCSR.h, cpp/dolfinx/la/SparsityPattern.cpp, cpp/dolfinx/mesh/Geometry.h, cpp/dolfinx/mesh/MeshTags.h, cpp/dolfinx/mesh/Topology.cpp, cpp/dolfinx/mesh/graphbuild.cpp, cpp/dolfinx/mesh/topologycomputation.cpp, cpp/dolfinx/mesh/utils.cpp, cpp/dolfinx/mesh/utils.h, cpp/dolfinx/refinement/plaza.h, cpp/dolfinx/refinement/utils.cpp, cpp/test/common/index_map.cpp, cpp/test/common/sort.cpp
And `std::is_sorted` replaced by `std::ranges::is_sorted`
=> Replace `std::sort` with `std::ranges::sort`

cpp/doc/source/conf.py, cpp/dolfinx/fem/assembler.h, python/doc/source/conf.py, python/test/unit/fem/test_assembler.py
Resolves https://github.com/FEniCS/dolfinx/issues/3301
=> Only try to lift boundary conditions if forms are provided

python/demo/demo_biharmonic.py
Fixes a missed comment of PR https://github.com/FEniCS/dolfinx/pull/3283, as pointed out by @francesco-ballarin
=> Fix comment in prior PR

cpp/dolfinx/fem/utils.h, cpp/test/CMakeLists.txt, cpp/test/fem/functionspace.cpp
Fixes https://github.com/FEniCS/dolfinx/issues/3345
=> Fix bug in `create_functionspace`

.github/workflows/macos.yml
Previously ran weekly on `main`.
Resolves #3312.
=> Run macos CI on pull requests

cpp/dolfinx/io/XDMFFile.cpp
Would resolve #3316 / clarify usage of ascii mode.
=> Add error handling of ASCII + write/append mode with XDMFFile.

python/dolfinx/wrappers/petsc.cpp
=> Expose Newton convergence check setter in Python

python/dolfinx/fem/bcs.py
=> Expose `DirichletBC.dof_indices` to Python interface 

.github/workflows/ccpp.yml
This checks that these flags are set correctly and ensures that in the kitchen sink build we actually find all of the features we expect.
=> Check optional features are found/not found.

cpp/dolfinx/mesh/generation.h, python/dolfinx/wrappers/mesh.cpp
Fixes https://github.com/FEniCS/dolfinx/issues/3357
=> Fix missing template type in generation

docker/Dockerfile.end-user
=> Add CMAKE_PREFIX_PATH to Dockerfile

python/dolfinx/mesh.py, python/test/unit/refinement/test_refinement.py
Fixing the same issue as: https://github.com/FEniCS/dolfinx/pull/3367/ again
=> Fix mesh constructor again

python/pyproject.toml
Comment includes link to issue to track.
Re-formatting is due to ruff.
=> Add comment in `pyproject.toml` on cffi version pin

cpp/dolfinx/nls/NewtonSolver.h
No code changes, just more docs.
=> Improve Newton solver docs

cpp/dolfinx/fem/FiniteElement.cpp, cpp/dolfinx/fem/FiniteElement.h, python/test/unit/fem/test_mixed_element.py
=> Allow mixed element with single element

python/dolfinx/fem/element.py, python/test/unit/fem/test_dof_permuting.py
Introduced in: https://github.com/FEniCS/dolfinx/pull/3542
Exposed by tests in adios4dolfinx:.
=> Fix regression in FiniteElement Python wrapper

python/test/unit/io/test_xdmf_function.py
Fixing regression introduced in https://github.com/FEniCS/dolfinx/pull/3547, see https://github.com/FEniCS/ufl/pull/331#issuecomment-2538753407.
=> Fix regression from PR 3547

python/test/unit/fem/test_fem_pipeline.py
Add missing `dtype` in `test_fem_pipeline.py`
=> Add missing datatype in test_fem_pipeline

cpp/dolfinx/common/sort.h, cpp/dolfinx/fem/assemble_matrix_impl.h, cpp/dolfinx/fem/assemble_vector_impl.h, cpp/dolfinx/geometry/BoundingBoxTree.h, cpp/dolfinx/graph/partitioners.cpp, cpp/dolfinx/mesh/Mesh.h, cpp/dolfinx/mesh/Topology.cpp, cpp/dolfinx/mesh/graphbuild.cpp, cpp/dolfinx/mesh/graphbuild.h, cpp/dolfinx/mesh/utils.cpp, cpp/dolfinx/mesh/utils.h, cpp/test/mesh/refinement/rectangle.cpp, python/dolfinx/mesh.py, python/dolfinx/wrappers/fem.cpp, python/test/unit/fem/test_assembler.py
Follow common code path for meshes with one cell type and meshes with more than one cell type.
Step towards #3567.
=> Single code path for mesh creation

cpp/dolfinx/fem/dofmapbuilder.cpp, cpp/dolfinx/mesh/Geometry.h, cpp/dolfinx/mesh/Topology.cpp, cpp/dolfinx/mesh/Topology.h, cpp/dolfinx/mesh/permutationcomputation.cpp, cpp/dolfinx/mesh/topologycomputation.cpp, cpp/dolfinx/mesh/topologycomputation.h, python/dolfinx/wrappers/mesh.cpp
Improve docs and avoid multiple code paths.
More substantial changes to follow.
=> Topology doc and code path improvements

cpp/dolfinx/mesh/Topology.cpp, cpp/dolfinx/mesh/Topology.h, cpp/dolfinx/mesh/topologycomputation.cpp, cpp/dolfinx/mesh/topologycomputation.h, python/dolfinx/mesh.py, python/dolfinx/wrappers/mesh.cpp, python/test/unit/mesh/test_mixed_topology.py
=> Simplify and improve Topology interface

python/demo/demo_pml.py, python/demo/demo_scattering_boundary_conditions.py, python/demo/demo_tnt-elements.py
defelement has moved from .com to .org
=> update DefElement links

python/conda-oneapi-test-env.yml
Updates to Python 3.12 and other updates.
=> Update oneAPI CI

cpp/demo/mixed_poisson/CMakeLists.txt, cpp/demo/mixed_poisson/main.cpp, cpp/demo/mixed_poisson/mixed_poisson.py, cpp/doc/source/demo.rst, python/pyproject.toml
Breathe fails with latest Sphinx release.
=> Doc fixes and pin Sphinx version

python/demo/demo_stokes.py
Stokes demo: create PETSc IS on mesh communicator (rather than `COMM_SELF`)
Resolves #3691
=> Stokes demo: create PETSc IS on mesh communicator

cpp/dolfinx/common/MPI.h, cpp/dolfinx/common/Scatterer.h, cpp/dolfinx/fem/FunctionSpace.h, cpp/dolfinx/fem/discreteoperators.h, cpp/dolfinx/io/HDF5Interface.cpp, cpp/dolfinx/io/HDF5Interface.h, cpp/dolfinx/io/VTKHDF.h, cpp/dolfinx/la/MatrixCSR.h, cpp/dolfinx/mesh/generation.h, cpp/dolfinx/mesh/utils.h, python/dolfinx/wrappers/assemble.cpp, python/dolfinx/wrappers/dolfinx_wrappers/array.h, python/dolfinx/wrappers/fem.cpp, python/dolfinx/wrappers/io.cpp, python/dolfinx/wrappers/mesh.cpp, python/dolfinx/wrappers/petsc.cpp
Includes fix of nasty `using namespace ...` in a header file, which should never happen.
=> Various code fixes and simplifications

.github/workflows/docker-end-user.yml
Reverts changes in #3697 - Docker images should not re-build on every push.
=> Revert changes to end-user Docker build

.github/dependabot.yml
Not sure how this will work, but we can try and disable later if too many PRs are coming?
=> Make dependabot check dockerfiles

.github/workflows/ccpp.yml, .github/workflows/fenicsx-refs.env, python/dolfinx/fem/assemble.py, python/dolfinx/fem/bcs.py, python/dolfinx/fem/element.py, python/dolfinx/fem/forms.py, python/dolfinx/fem/function.py, python/dolfinx/io/utils.py, python/dolfinx/la/petsc.py, python/dolfinx/mesh.py, python/dolfinx/plot.py
Depends on https://github.com/FEniCS/ufl/pull/383 and https://github.com/FEniCS/basix/pull/944
Basix mypy check in the dolfinx CI appeared to be more exhaustive then the one in the linting step here. Therefore, this adds a mypy check in the non matrix 'Build and test' run.
=> Fix mypy errors for newly typed ufl

.github/workflows/ccpp.yml, python/dolfinx/fem/function.py, python/dolfinx/mesh.py
=> More `mypy` fixes

python/demo/demo_axis.py, python/demo/demo_biharmonic.py, python/demo/demo_helmholtz.py, python/demo/demo_pml.py, python/demo/demo_poisson.py, python/demo/demo_scattering_boundary_conditions.py, python/demo/demo_tnt-elements.py, python/dolfinx/fem/petsc.py, python/test/unit/fem/test_petsc_solver_wrappers.py
Matches behaviour of NonlinearProblem. Examples and tests updated to encourage users to check.
=> LinearProblem.solve return converged_reason and number_iterations

cpp/dolfinx/refinement/interval.h, cpp/dolfinx/refinement/plaza.h, cpp/dolfinx/refinement/utils.h
=> Replace `std::map` in refinement

.github/workflows/ccpp.yml, python/dolfinx/la/petsc.py, python/dolfinx/utils.py
Also extends the mypy check to also run in the PETSc CI.
Fixes https://github.com/FEniCS/dolfinx/issues/3769
=> Run `mypy` in package mode

cpp/dolfinx/la/MatrixCSR.h
=> Documentation update for `MatrixCSR::mult`

.github/workflows/ccpp.yml
Removes duplicate CI code that has no effect.
=> Remove redundant CI Actions code

python/dolfinx/io/gmshio.py, python/dolfinx/mesh.py, python/test/unit/fem/test_assembler.py, python/test/unit/fem/test_dof_permuting.py, python/test/unit/fem/test_dofmap.py, python/test/unit/fem/test_element_integrals.py, python/test/unit/fem/test_function.py, python/test/unit/fem/test_function_space.py, python/test/unit/fem/test_interpolation.py, python/test/unit/fem/test_petsc_discrete_operators.py, python/test/unit/fem/test_vector_function.py, python/test/unit/geometry/test_gjk.py, python/test/unit/io/test_adios2.py, python/test/unit/io/test_vtk.py, python/test/unit/io/test_xdmf_mesh.py, python/test/unit/mesh/test_cell.py, python/test/unit/mesh/test_higher_order_mesh.py, python/test/unit/mesh/test_manifold_point_search.py, python/test/unit/mesh/test_mesh.py, python/test/unit/mesh/test_mesh_partitioners.py
Fixes https://github.com/FEniCS/dolfinx/issues/3792
=> Align order of `create_mesh` in Python layer to C++ layer

python/dolfinx/mesh.py
Wrong indentation in documentation
=> Fix indentation of create_mesh

python/dolfinx/fem/forms.py, python/dolfinx/wrappers/fem.cpp
=> Fix Python-binding of `Form::num_integrals`

python/dolfinx/fem/forms.py
=> Fix type hint regression
