FEniCS/dolfinx

- cpp/dolfin/fem/DofMapBuilder.cpp
- cpp/dolfin/fem/DofMapBuilder.h
- python/test/unit/function/test_function_space.py
Make most functions 'pure', i.e. `const` arguments and return pairs, tuples, etc (using move constructors).
> Dofmap builder simplifications

- cpp/dolfin/common/MPI.h
Makes a switchable implementation of alltoall available, which uses MPI-2 MPI_Put and MPI_Get.
Can be switched by setting `-DMPI_ALLTOALL_USE_PUT_GET`.
> Update MPI::all_to_all to use MPI_Put and MPI_Get

- .circleci/config.yml
- Dockerfile
- cpp/dolfin/fem/Assembler.cpp
- cpp/dolfin/fem/Form.cpp
- cpp/dolfin/fem/Form.h
- cpp/dolfin/fem/FormCoefficients.cpp
- cpp/dolfin/fem/FormCoefficients.h
- cpp/dolfin/fem/FormIntegrals.cpp
- cpp/dolfin/fem/FormIntegrals.h
- python/src/fem.cpp
- python/test/unit/fem/test_numba_assembly.py
Move tabulate_tensor to `Form` and relieves the assembler for the responsibility of updating
coefficients, or choosing which integral to use based on cell index.
* add a constructor to `Form` without any UFC integrals
* allow user-defined cell integrals (e.g. with numba) to be attached to `Form`
* add test for user-defined numba kernel
Obviously there is more to do, and much to clean up when we get rid of `SystemAssembler`.
> Move tabulate_tensor to Form

- cpp/dolfin/mesh/Mesh.cpp
- cpp/dolfin/mesh/MeshPartitioning.cpp
- cpp/dolfin/mesh/MeshPartitioning.h
- python/demo/undocumented/ghost-mesh/demo_ghost-mesh.py
- python/test/unit/mesh/test_ghost_mesh.py
This re-enables the 'ghost via shared vertex' ghost method.
*  fixes a bug where the global number of cells was incorrect for ghosted meshes.
* also improves ghost mesh tests
> Re-enable ghost shared vertex

- cpp/dolfin/la/SLEPcEigenSolver.cpp
- cpp/dolfin/la/SLEPcEigenSolver.h
- python/src/la.cpp
Although SLEPc separates the real and imaginary part of eigenvalues and eigenvectors, the scalar type is complex (with zero imaginary part) when PETSc is compiled with complex support.   
Changes:
* Set eigenvalues scalars to PetscScalar
* Convert spectral_shift to PetscScalar before calling EPSSetTarget
Note: The parameter "spectral_shift" is still real. For complex spectral shift: use complex parameters or a parameter for real and imaginary parts?
> Add complex suppport to la::SLEPcEigenSolver

- python/dolfin/fem/solving.py
Currently, the solve function swallows all form compiler parameters.
> Pass form compiler parameters to Form constructor in variational problem

- .circleci/config.yml
- cpp/dolfin/common/types.h
- cpp/dolfin/fem/FormIntegrals.h
Define `ufc_scalar` for use in _ufc.h_.
This PR should be considered together with FFC [PR #31](https://github.com/FEniCS/ffcx/pull/31).
> Define ufc_scalar for a complex UFC interface

- .circleci/config.yml
- cpp/dolfin/function/Expression.cpp
- python/demo/documented/stokes-taylor-hood/demo_stokes-taylor-hood.py.rst
- python/dolfin/function/function.py
- python/test/unit/function/test_function.py
Related to issue #98 
`Expression::restrict` had erroneous code transposing the evaluated values at DoFs. This affected any function spaces whose rank is greater than 0.
The changes here are:
- Remove an erroneous transpose operation
- Add back some `Function::interpolate` of `Expression` tests 
- Revert the assertion of the pressure norm value to the value computed using old DOLFIN
> Expression::restrict fix

- cpp/demo/documented/singular-poisson/main.cpp
- cpp/demo/undocumented/contact-vi-snes/main.cpp
- cpp/demo/undocumented/contact-vi-tao/main.cpp
- cpp/demo/undocumented/curl-curl/main.cpp
- cpp/demo/undocumented/elasticity/main.cpp
- cpp/demo/undocumented/gmg-poisson/main.cpp
- cpp/dolfin/CMakeLists.txt
- cpp/dolfin/common/MPI.cpp
- cpp/dolfin/common/MPI.h
- cpp/dolfin/common/SubSystemsManager.cpp
- cpp/dolfin/common/defines.cpp
- cpp/dolfin/common/defines.h
- cpp/dolfin/io/HDF5Interface.cpp
- cpp/test/unit/common/SubSystemsManager.cpp
- python/demo/documented/maxwell-eigenvalues/demo_maxwell-eigenvalues.py.rst
- python/demo/documented/singular-poisson/demo_singular-poisson.py.rst
- python/demo/undocumented/buckling-tao/demo_buckling-tao.py
- python/demo/undocumented/contact-vi-snes/demo_contact-vi-snes.py
- python/demo/undocumented/contact-vi-tao/demo_contact-vi-tao.py
- python/demo/undocumented/curl-curl/demo_curl-curl.py
- python/demo/undocumented/mixed-poisson-sphere/demo_mixed-poisson-sphere.py
- python/dolfin/__init__.py
- python/dolfin_utils/test/skips.py
- python/src/common.cpp
- python/src/fem.cpp
- python/src/mpi_casters.h
- python/src/petsc_casters.h
- python/test/unit/la/test_mg_solver.py
First step.
The following step is renaming `dolfin.has_foo()` into `dolfin.config.has_foo` (property) and alternative names where appropriate, e.g., `dolfin.config.complex_mode`. The question is whether we want to do the the namespacing into `dolfin::config` in C++ too.
> Remove remnants of MPI and PETSc being optional

- python/demo/documented/biharmonic/demo_biharmonic.py.rst
- python/demo/documented/poisson/demo_poisson.py.rst
- python/demo/documented/stokes-iterative/demo_stokes-iterative.py.rst
- python/demo/documented/stokes-taylor-hood/demo_stokes-taylor-hood.py.rst
- python/demo/undocumented/buckling-tao/demo_buckling-tao.py
- python/demo/undocumented/contact-vi-tao/demo_contact-vi-tao.py
- python/demo/undocumented/elasticity/demo_elasticity.py
- python/demo/undocumented/poisson-disc/demo_poisson-disc.py
- python/doc/source/api.rst
- python/dolfin/__init__.py
- python/dolfin/io.py
- python/test/unit/io/test_HDF5.py
- python/test/unit/io/test_HDF5_series.py
- python/test/unit/io/test_XDMF.py
- python/test/unit/io/test_XDMF_P2.py
- python/test/unit/mesh/test_mesh.py
Idea of this PR is to separate `io` namespace and try new "nothing in cpp namespace be public" approach.
- Removed import of IO to global namespace in `__init__.py`.
- Wrapped `VTKFile`, `XDMFFile`, `HDF5File` in `io.py`
> Wrap cpp.io in python

- python/demo/documented/poisson/demo_poisson.py.rst
- python/demo/undocumented/poisson-disc/demo_poisson-disc.py
- python/doc/source/conf.py
- python/dolfin/io.py
- python/src/io.cpp
- python/test/unit/io/test_XDMF.py
- python/test/unit/io/test_XDMF_P2.py
- python/test/unit/mesh/test_mesh.py
This is a start on designing a way to make the `dolfin.cpp` interface private and to generate much improved documentation for the Python interface. Only `dolfin.io` is addressed at this stage.
- Making the `dolfin.cpp` interface private (still accessible, but not part of the 'public' interface) gives a nice separation between the C++ and Python interfaces, and means that a change in the C++ interface does not need to lead to a consequent change in the Python interface (which will be a very good thing).
- Declaring a 'public' Python interface gives us something we can aim to keep stable and manage changes/deprecations in an orderly fashion, and document well. Advanced users can access the `dolfin.cpp` interfaces, with the awareness that they can change.
- The unwrapping of objects, e.g. …
> Start with hiding of dolfin.cpp (for IO) and improved doc generation

- cpp/dolfin/io/XDMFFile.cpp
- cpp/dolfin/io/XDMFFile.h
- python/demo/documented/poisson/demo_poisson.py.rst
- python/dolfin/io.py
- python/src/io.cpp
- python/test/unit/io/test_XDMF.py
- python/test/unit/io/test_XDMF_P2.py
- python/test/unit/mesh/test_mesh.py
Adds private variable `_encoding` to XDMFFile. This variable is set by constructor and allows more state dependent calls to io methods.
Reason:
- simplify interface for io methods, no need to spoil encoding everywhere
> Put encoding to XDMFFile constructor

- cpp/dolfin/io/HDF5File.h
- cpp/dolfin/io/HDF5Utility.cpp
- cpp/dolfin/io/HDF5Utility.h
- cpp/dolfin/io/XDMFFile.cpp
- cpp/dolfin/io/XDMFFile.h
- python/test/unit/io/test_XDMF_P2.py
Add support to:
- Write complex functions 
- `XDMFFile::write(const function::Function& u, const Encoding encoding)`
- `XDMFFile::write(const function::Function& u, double time_step, const Encoding encoding)`
Different `Attribute` (`AttributeType = {Scalar, Vector, Tensor}`) are created for each component (real and imaginary). The prefixes `"real"` and `"imag"` are attached to the function name to identify the component. 
Excerpt from an output file :
```        
<Attribute Name="real_field" AttributeType="Scalar" Center="Node">
<DataItem Dimensions="36 1" Format="HDF">output.h5:/VisualisationVector/real/0</DataItem>
</Attribute>
<Attribute Name="imag_field" AttributeType="Scalar" Center="Node">
<DataItem Dimensions="36 1" Format="HDF">output.h5:/VisualisationVector/imag/0</DataItem> …
```
> Add Complex support to XDMFFile

- cpp/dolfin/mesh/MeshIterator.h
Fixes https://github.com/FEniCS/dolfinx/issues/145
The removed lines are redundant because `_entity._local_index` is overwritten anyway on every dereferencing operator call and no other access to `_entity` is possible through the iterator. Furthermore it fixes an out of bounds read if the constructor is used to create an past the end iterator.
> Remove redundant index updates that may lead to invalid reads for end it

- python/test/unit/io/test_XDMF.py
- python/test/unit/io/test_XDMF_P2.py
This PR aims to increase the coverage of the current xdmf tests to treat the complex case.
The tests remain the same in real mode. 
In the complex mode, a nonzero imaginary part is added to the functions.
> Uptade XDMF tests to cover complex mode

- cpp/dolfin/io/HDF5File.cpp
- cpp/dolfin/io/VTKWriter.cpp
- cpp/dolfin/io/VTKWriter.h
Remaining modifications to get dolfinx to compile with PETSc-complex, in preparation to run nightly tests for the complex mode on master branch.
Since `PetscScalar = double` for PETSc real, these changes do not affect the real mode.
> Get dolfinx to compile with petsc-complex (remaining changes)

- python/dolfin/fem/assembling.py
`Assembler` used to swallow `form_compiler_parameters`
> Pass on form compiler parameters in Assembler

- cpp/cmake/templates/dolfin.pc.in
Old hardcoded version causes issues on e.g. platforms using lib64/.
> Use paths set by GNUInstallDirs in root CMakeLists.txt

- cpp/dolfin/io/XDMFFile.cpp
Probably no comments, albeit an ugly fix.
> Prevent 4-vector being interpreted as 2D tensor in XDMF

- python/dolfin/jit/pybind11jit.py
Similar PR as merged to dolfin-old https://bitbucket.org/fenics-project/dolfin/pull-requests/472/updated-pybind11jitpy-so-that/diff .
This functionality is crucial for users writing their own C++ performance routines with their own external libraries linked.
> Add more compile options to pybind11 jit

- .circleci/config.yml
- cpp/dolfin/fem/Form.cpp
- python/test/unit/fem/test_custom_jit_kernels.py
- python/test/unit/fem/test_numba_assembly.py
Shows how to easily write a `tabulate_tensor` kernel in C from Python.
> Add cffi-based element kernels to tests

- python/dolfin/fem/__init__.py
- python/dolfin/fem/assembling.py
- python/dolfin/fem/form.py
- python/dolfin/fem/solving.py
No python layer wrapper should subclass from its `cpp.foo` counterpart.
I removed this inheritance and added inheritance from `ufl.Form` instead. (the inheritance is not used anywhere, but we should be more systematic)
I also propose to strictly follow the rule: 
> 1. Any dolfin's python object that attaches data (function spaces, coefficients, ...) to UFL object should subclass it.
In the virtue of this rule, `dolfin.fem.Form` is indeed attaching function spaces to `cpp.fem.Form`.
> Refactor dolfin python's Form

- python/dolfin/jit/jit.py
- python/src/fem.cpp
- python/src/function.cpp
- python/test/unit/fem/test_discrete_operators.py
- python/test/unit/fem/test_petsc_transfer_matrix.py
This makes the pybind11 code a whole lot simpler.
One change should have broken user jit, but mustn't be covered at the moment by tests. Will be an easy fix.
> Remove pybind11 unwrapping of Python objects

- cpp/CMakeLists.txt
- cpp/dolfin/CMakeLists.txt
- cpp/dolfin/common/defines.cpp
- cpp/dolfin/common/defines.h
- cpp/dolfin/io/XDMFFile.cpp
- cpp/dolfin/io/XDMFFile.h
- python/dolfin/__init__.py
- python/dolfin/common.py
- python/dolfin_utils/test/skips.py
- python/src/common.cpp
- python/test/unit/io/test_HDF5.py
- python/test/unit/io/test_HDF5_series.py
- python/test/unit/io/test_XDMF.py
This includes updates around the ifdefs for HDF5. 
Making HDF5 required simplifies the logic around tests, and required dependencies provide more clarity for users.
> Make HDF5 (parallel) a required dependency

- cpp/dolfin/graph/CSRGraph.h
- cpp/dolfin/mesh/CoordinateDofs.cpp
- cpp/dolfin/mesh/CoordinateDofs.h
- cpp/dolfin/mesh/DistributedMeshTools.cpp
- cpp/dolfin/mesh/Mesh.cpp
- cpp/dolfin/mesh/Mesh.h
- cpp/dolfin/mesh/MeshConnectivity.cpp
- cpp/dolfin/mesh/MeshConnectivity.h
- cpp/dolfin/mesh/MeshFunction.h
- cpp/dolfin/mesh/MeshIterator.h
- cpp/dolfin/mesh/MeshTopology.cpp
- cpp/dolfin/mesh/MeshTopology.h
- cpp/dolfin/mesh/TopologyComputation.cpp
- python/dolfin/function/specialfunctions.py
- python/src/mesh.cpp
- python/test/unit/function/test_function.py
Eventually should remove `MeshConnectivity` and use a CSR graph data structure.
> Simplify mesh connectivity

- cpp/dolfin/la/PETScMatrix.h
Fix  a minor error in cpp/dolfin/la/PETScMatrix.h
> Move PETScVector forward declaration in dolfin::la namespace

- python/src/la.cpp
dolfin::la::SLEPcEigenSolver::get_eigenpair was being wrapper instead of get_eigenvalue
> Fix wrong pybind11 wrapper in SLEPcEigenSolver

- python/src/la.cpp
This is backport of the last item in https://bitbucket.org/fenics-project/dolfin/pull-requests/424/add-a-few-pybind11-wrappers/diff , that was merged to DOLFIN master after a brief discussion.
A couple of libraries that I develop rely on this for DOLFIN. pyadjoint will need this as well (see e.g. https://bitbucket.org/dolfin-adjoint/pyadjoint/src/master/fenics_adjoint/types/genericmatrix.py )
> Allow dynamic attributes in pybind11 wrapped dolfin::la::PETScMatrix and dolfin::la::PETScVector

- python/CMakeLists.txt
- python/dolfin/MPI.py
- python/dolfin/__init__.py
- python/dolfin/common.py
- python/dolfin_utils/test/skips.py
- python/setup.py
- python/src/common.cpp
- python/src/mpi_casters.h
- python/src/petsc_casters.h
- python/test/unit/common/test_mpi.py
- python/test/unit/jit/test_jit.py
- python/test/unit/la/test_mg_solver.py
Having mpi4py and petsc4py seems to be required for a decent user experience with the DOLFIN Python bindings. A counter-example of packages that are not required for decent user experience would be SLEPc and SLEPc4py. Building mpi4py and petsc4py is trouble-free, even on HPC. Most HPC toolchains with Python, e.g. Intel, include mpi4py out of the box.
Assuming both exist by default removes complexity and many unneeded codepaths.
> Make mpi4py and petsc4py mandatory requirements

- .circleci/config.yml
- cpp/dolfin/fem/Form.cpp
- cpp/dolfin/fem/FormIntegrals.cpp
- cpp/dolfin/fem/FormIntegrals.h
- cpp/dolfin/fem/LocalAssembler.cpp
- cpp/dolfin/fem/SystemAssembler.cpp
- cpp/dolfin/fem/UFC.cpp
- python/src/fem.cpp
- python/test/unit/fem/test_custom_jit_kernels.py
This is in conjunction with the branch https://github.com/FEniCS/ffcx/tree/chris/flatten-coeff-dofs
* access coefficient dofs through a flat array, with offsets determined by the coefficient element
sizes.
> flatten coefficient dofs

- python/dolfin/fem/assembling.py
Hi,
I believe that the condition showed in the diff is a leftover from previous implementations, because:
(i) I cannot find any other _compiled_form in the entire fenics/fenicsx codebase
(ii) if there was, it definitely could not be attached to cpp.fem.Form object, because cpp.fem.Form wrapper was declared without py::dynamic_attr()
Feel free to close in case I overlooked something else and the check is actually needed.
Francesco
> Remove check on _compiled_form attribute in _create_cpp_form

- cpp/dolfin/fem/assemble_vector_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.h
- cpp/dolfin/fem/assembler.cpp
Some simplification and unpicking of the new vector assembly.
The implementation use Eigen. The data pointer underlying PETSc `Vec`s is wrapped as an `Eigen::Map`, into which a form is assembled.
> Some refactoring of vector assembly

- cpp/dolfin/fem/FiniteElement.cpp
- cpp/dolfin/fem/FiniteElement.h
* Catches the `return -1` from various ufc functions when they are not defined.
> Catch ufc errors

- cpp/dolfin/fem/DirichletBC.cpp
- cpp/dolfin/fem/assemble_vector_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.h
- cpp/dolfin/fem/assembler.cpp
- cpp/dolfin/fem/assembler.h
- cpp/dolfin/la/utils.cpp
- cpp/dolfin/la/utils.h
Add wrapper for representing PETSc `Vec` as `Eigen::Map`.
> Simplify setting of bc on vector

- cpp/dolfin/common/MPI.h
- cpp/dolfin/fem/DirichletBC.cpp
- cpp/dolfin/fem/utils.cpp
Some changes for quirks of clang, also reverting MPI type detection: issues with int types.
> Fixes for clang on MacOS

- cpp/CMakeLists.txt
- cpp/cmake/modules/FindEigen3.cmake
- cpp/cmake/modules/FindParMETIS.cmake
- cpp/cmake/modules/FindSCOTCH.cmake
- python/cmake/FindPETSc4py.cmake
- python/dolfin/pybind11jit.py
Switch to CMake standard variable `FOO_ROOT` in place of `FOO_DIR`.
Also clean up some CMake policy settings.
> Use CMake default root dir for dependencies

- cpp/dolfin/fem/SystemAssembler.cpp
- cpp/dolfin/fem/utils.cpp
- cpp/dolfin/function/Function.cpp
- cpp/dolfin/io/VTKWriter.cpp
- cpp/dolfin/io/XDMFFile.cpp
- cpp/dolfin/la/PETScMatrix.cpp
- cpp/dolfin/la/PETScMatrix.h
- cpp/dolfin/la/PETScOperator.cpp
- cpp/dolfin/la/PETScOperator.h
- cpp/dolfin/la/PETScVector.cpp
- cpp/dolfin/la/PETScVector.h
Replaced with access to underlying `Vec` array, held by `EIgen::Map.
> Remove more PETSc wrappers

- cpp/dolfin/fem/assemble_scalar_impl.cpp
- cpp/dolfin/fem/assemble_scalar_impl.h
- cpp/dolfin/fem/assemble_vector_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.h
- cpp/dolfin/fem/assembler.cpp
Very minor change, which could make reading the fem::impl a bit easier
> Rename fem::impl assemble methods to assemble_scalar and assemble_vector respectively, for consistency with assemble_matrix

- python/demo/elasticity/demo_elasticity.py
- python/demo/poisson/demo_poisson.py
- python/dolfin/__init__.py
- python/dolfin/generation.py
- python/test/unit/la/test_nullspace.py
- python/test/unit/mesh/test_mesh.py
- python/test/unit/mesh/test_mesh_quality.py
- python/test/unit/ufl-jit-assemble-chain/test_form_operations.py
Another bunch of python wrappers. Calling `dolfin.cpp.generation` should be avoided in user code from now on.
> Wrap dolfin.generation module

- cpp/demo/hyperelasticity/hyperelasticity.ufl
- cpp/demo/hyperelasticity/main.cpp
- cpp/demo/poisson/main.cpp
- cpp/dolfin/fem/Form.cpp
- cpp/dolfin/fem/Form.h
- python/src/fem.cpp
Stop using `shared_ptr` where it is no longer needed for ufc objects passed into dolfin.
> Use reference to pass ufc_form

- cpp/dolfin/fem/CoordinateMapping.h
- cpp/dolfin/fem/Form.cpp
- python/src/fem.cpp
Extracts essential information (including two functions) from `ufc_coordinate_mapping` at the construction time of dolfin's `CoordinateMapping` class. 
* Potential for user mappings in the future without using ffc/ufc.
> Removes ufc_coordinate_mapping from dolfin

- cpp/demo/hyperelasticity/main.cpp
- cpp/demo/poisson/main.cpp
- cpp/dolfin/fem/FiniteElement.cpp
- cpp/dolfin/fem/FiniteElement.h
- python/src/fem.cpp
Hangs onto the function pointers instead. Part of move to make ufc optional.
> Remove holding of ufc_finite_element struct

- .circleci/config.yml
- Dockerfile
Jupyterlab will replace Jupyter notebooks soon, and offers a far superior interface (including a more classic write script then execute script workflow).
https://jupyterlab.readthedocs.io/en/stable/
I decided to install Jupyterlab at the same time as Jupyter. This supports one further documented way of getting the lab, which is to navigate to https://localhost:8080/lab after having used the standard `jupyter notebook` call.
> Add Jupyterlab to Docker image collection

- cpp/CMakeLists.txt
* turn off flag which is only set in clang, but not gcc with -Wall.
> Turn off clang brace check

- cpp/dolfin/fem/Form.cpp
- cpp/dolfin/fem/Form.h
- cpp/dolfin/fem/FormCoefficients.cpp
- cpp/dolfin/fem/FormCoefficients.h
- cpp/dolfin/fem/FormIntegrals.cpp
- cpp/dolfin/fem/FormIntegrals.h
- cpp/dolfin/fem/utils.cpp
- cpp/dolfin/fem/utils.h
- python/test/unit/fem/test_custom_jit_kernels.py
Makes `FormIntegrals` and `FormCoefficients` free of ufc, and confines conversion from ufc_form to the Form constructor.
* Adds possibility to set coefficients for user kernels + unit test
> Update Form to be less dependent on ufc_form

- cpp/demo/hyperelasticity/main.cpp
- cpp/demo/poisson/main.cpp
- cpp/dolfin/function/Expression.cpp
- cpp/dolfin/function/Expression.h
- cpp/dolfin/function/SpecialFunctions.cpp
- cpp/dolfin/function/SpecialFunctions.h
- python/dolfin/function/expression.py
- python/src/function.cpp
- python/test/unit/function/test_function.py
When using Numba expressions, it was not possible to get a 'time' parameter. This adds a time parameter to Expression that a user can update outside of an eval function.
Also remove the `cell` argument. The design was inconsistent w.r.t evaluation at an arbitrary number of points. E.g., for multiple cells it was not defined which cell a point belonged to. Moreover, it was not used in any tests or demos. Can be re-designed later if needed.
> Add time argument to Expression

- python/test/unit/fem/test_custom_assembler.py
Add pytest-xdist worker thread id to compiled module name.
> Make test using cffi to expose PETSc thread-safe.

- cpp/dolfin/fem/PETScDMCollection.cpp
- cpp/dolfin/fem/assemble_matrix_impl.cpp
- cpp/dolfin/fem/assemble_scalar_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.cpp
- cpp/dolfin/function/Function.cpp
- cpp/dolfin/generation/BoxMesh.cpp
- cpp/dolfin/io/HDF5File.cpp
Some dynamic memory allocation could be reduced now, after fixed geometry width.
Probably, a good compiler could deduce this from returned values, but anyway...
> Reduce dynamic eigen memory

- cpp/dolfin/io/HDF5File.cpp
This fixes the problem identified in Issue 1000 from the Bitbucket tracker and prevents `read_mesh` from crashing in parallel with quad/hex meshes (for certain combinations of meshes and numbers of processors).  
However, unlike in the current stable version of DOLFIN on Bitbucket, this fix **does not** lead to correct behavior of `read_mesh` with with the parameter `use_partition_from_file=true`, due to the orthogonal issue that, in DOLFIN-X, `build_distributed_mesh` no longer checks whether an existing partition exists, and always re-partitions the mesh.  (I will open an issue for discussion of this separate problem.)
> Prevent crash during HDF5File::read_mesh with quad/hex elements in parallel

- cpp/dolfin/function/Function.cpp
Function evaluation takes a point with true geometrical dimensions,
e.g. for mesh with gdim=2  we call `f([0.5, 0.5])`, thus the point needs padding for use in bounding box tree cell computation.
> Pad input point to 3d

- cpp/dolfin/fem/DofMapBuilder.cpp
- cpp/dolfin/fem/PETScDMCollection.cpp
- cpp/dolfin/fem/assemble_matrix_impl.cpp
- cpp/dolfin/fem/assemble_scalar_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.cpp
- cpp/dolfin/function/Function.cpp
- cpp/dolfin/function/FunctionSpace.cpp
- cpp/dolfin/io/xdmf_write.cpp
- cpp/dolfin/mesh/Connectivity.cpp
- cpp/dolfin/mesh/Connectivity.h
- cpp/dolfin/mesh/CoordinateDofs.cpp
- cpp/dolfin/mesh/CoordinateDofs.h
- cpp/dolfin/mesh/Mesh.cpp
- cpp/dolfin/mesh/Mesh.h
- cpp/dolfin/mesh/Ordering.cpp
- cpp/dolfin/mesh/Partitioning.cpp
- cpp/dolfin/mesh/Partitioning.h
- python/src/fem.cpp
- python/src/mesh.cpp
- python/test/unit/fem/test_dofmap.py
Geometry 'dofs' were not being updated when re-ordering a mesh, leading to incorrect results.
This fixes the case of affine (P1) geometry. High-order geometry needs carefully consideration (refactoring, really) and does not work at present. Re-ordering a non-affine simplex mesh will throw an error.
> Fixes for mesh re-ordering and geometry

- .circleci/config.yml
- cpp/dolfin/fem/Form.cpp
- cpp/dolfin/fem/Form.h
- cpp/dolfin/fem/FormIntegrals.cpp
- cpp/dolfin/fem/FormIntegrals.h
- cpp/dolfin/fem/assemble_matrix_impl.cpp
- cpp/dolfin/fem/assemble_matrix_impl.h
- cpp/dolfin/fem/assemble_scalar_impl.cpp
- cpp/dolfin/fem/assemble_scalar_impl.h
- cpp/dolfin/fem/assemble_vector_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.h
- cpp/dolfin/mesh/MeshEntity.cpp
- cpp/dolfin/mesh/MeshEntity.h
- python/src/fem.cpp
- python/test/unit/fem/test_assembler.py
- python/test/unit/fem/test_custom_assembler.py
- python/test/unit/fem/test_custom_jit_kernels.py
This replaces the tabulate_tensor signature for all integrals (except custom) to the same signature.
* will lead to further simplifications in `FormIntegrals`
* needs ffcx branch https://github.com/FEniCS/ffcx/tree/chris/unify-facet-integral-sigs
> Replace tabulate signature and start on interior facet integrals

- cpp/dolfin/mesh/Partitioning.cpp
- python/test/unit/io/test_XDMF.py
- python/test/unit/mesh/test_mesh.py
Throw an error if the expected local number of cells is less than 2.
This "fixes" [Issue 114](https://github.com/FEniCS/dolfinx/issues/114). It hangs when a process owns 0 cells, after the partitioning process.
Partitioning small graphs can lead to unexpected results, such as a different number of parts than requested (known Issue of Scotch and Parmetis, e.g.: [Issue](http://glaros.dtc.umn.edu/gkhome/node/786)), and segmentation fault when using k-way partitioning (eg.: [Issue](https://github.com/schulzchristian/KaHIP/issues/34)).
> Avoid partitioning small meshes

- python/setup.py
Not used in DOLFIN, but is used in tests.
> Remove numba requirement in setup.py

- Dockerfile
With Gmsh sdk we have Python API available. Prepares docker image for https://github.com/FEniCS/dolfinx/pull/454
> Update Gmsh to sdk version for python API

- cpp/dolfin/io/HDF5File.cpp
- cpp/dolfin/io/HDF5File.h
- cpp/dolfin/io/XDMFFile.cpp
- cpp/dolfin/io/XDMFFile.h
- python/demo/mixed-elasticity-sc/static-condensation-elasticity.py
- python/demo/stokes-taylor-hood/demo_stokes-taylor-hood.py
- python/dolfin/io.py
- python/src/io.cpp
- python/test/unit/io/test_HDF5.py
- python/test/unit/io/test_XDMF.py
- python/test/unit/io/test_XDMF_P2.py
`HDF5File` and `XDMFFile` already have their communicator (passed for the constructor).
In `XXXXX::read_mesh` the communicator parameter was not used.
Removing the comm parameter avoids ambiguity if one uses more than 1 communicator for other tasks.
> Remove unused comm parameter from read_mesh

- cpp/dolfin/fem/FormIntegrals.cpp
- cpp/dolfin/fem/assemble_matrix_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.cpp
- cpp/dolfin/mesh/MeshEntity.cpp
- cpp/dolfin/mesh/MeshEntity.h
- python/test/unit/fem/test_ghost_mesh_assembly.py
Adds some unit tests for integrals with ghost cells, and fixes some resulting issues in assembler.
* mostly resolved by adjusting the list of `active_entities` in `FormIntegrals`
* Integrals on `dx`, `ds`, and `dS`
* Compares serial and parallel results for equality
> Add ghost assembly tests

- python/doc/source/installation.rst
The [readthedocs page](https://fenicsproject.org/docs/dolfinx/dev/python/installation.html) still points to Docker Hub, not quay.io. This also removes a duplicate word in the documentation page.
> Update URL to containers

- cpp/dolfin/fem/assemble_matrix_impl.cpp
- cpp/dolfin/fem/assemble_scalar_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.cpp
- cpp/dolfin/function/Function.cpp
- cpp/dolfin/function/Function.h
- cpp/dolfin/function/FunctionSpace.cpp
- python/demo/mixed-elasticity-sc/static-condensation-elasticity.py
- python/demo/stokes-taylor-hood/demo_stokes-taylor-hood.py
- python/dolfin/function/function.py
- python/src/function.cpp
- python/test/unit/function/test_function.py
`ufl.Coefficient.__call__` was being hidden in the subclass `dolfin.Function`, and this messed up DG restrictions.
This change requires user to call the method `eval` to evaluate a Function at points.
> Avoid hiding ufl.Coefficient.__call__

- cpp/dolfin/fem/utils.cpp
Provide `std::free` as custom deleter when building `std::shared_ptr<ufc_dofmap>`.
> Add custom deleter to shared_ptr<ufc_dofmap> (addresses issue #524)

- cpp/doc/Doxyfile
- cpp/dolfin/common/MPI.cpp
- cpp/dolfin/common/MPI.h
- cpp/dolfin/function/Function.h
- cpp/dolfin/io/HDF5Interface.h
* Final clean-up required to run doxygen with warn=error
* Removes some outdated MPI wrappers
* Uses doxygen `@cond` command to comment out regions (template specialisations)
> More doxygen compliance

- cpp/dolfin/io/HDF5File.cpp
- cpp/dolfin/io/VTKWriter.cpp
- cpp/dolfin/io/xdmf_write.cpp
- cpp/dolfin/mesh/Mesh.cpp
- cpp/dolfin/mesh/cell_types.cpp
- cpp/dolfin/mesh/utils.cpp
Assumed that the VTK mapping and cell_permutation always matches, which is not the case for quadrilaterals, using Lexiographic ordering (when we use built in meshes). 
Support for reading gmsh-quad meshes are still not there, as a flag needs to be introduced to tell the constructor which ordering the input data has.
Reverting assumptions in mesh/utils, and decoupling cell_permutation from visualization, as the assumption I made there clearly does not hold in general
> Fixes bug introduced in PR 532

- cpp/dolfin/function/Function.cpp
- cpp/dolfin/function/Function.h
- python/demo/mixed-elasticity-sc/static-condensation-elasticity.py
- python/dolfin/function.py
- python/src/function.cpp
- python/test/unit/function/test_function.py
This changes the `Function` `eval` interface to take (i) a list of points and (ii) a list of cells indices that contain each point. Points with negative cell indices are ignored (the bounding box search now returns a negative index when the cell containing a point is not found). This makes point evaluations in parallel much simpler.
The change makes what is happening behind `eval` explicit and removes a ton of opaque magic behind the scenes, e.g. cell searches, assumptions on what to do when a point is 'close' to a cell but not within it, etc. Now allowing an arbitrary number of points to be processed permits a number of performance optimisations and minimises dynamics memory allocations.
Example usage:
```
x = numpy.array(......)
tree = geometry.BoundingBoxTree(mesh, mesh.geometry.dim) …
```
> Simplify Function::eval interface

- cpp/dolfin/fem/assemble_matrix_impl.cpp
- cpp/dolfin/fem/assemble_scalar_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.cpp
- cpp/dolfin/function/Function.cpp
- cpp/dolfin/function/Function.h
- cpp/dolfin/function/FunctionSpace.cpp
Remove `Function::restriction`, which obfuscated a simple operation and involved  a number of operations that should be taken outside of tight loops.
This PR improves the code in `Function` and `FunctionSpace`, and adds placeholder functions in the assembly code that can be removed later with more re-factoring of coefficients in the assembly code.
> Remove Function::restriction

- .circleci/config.yml
- cpp/dolfin/fem/assemble_matrix_impl.cpp
- cpp/dolfin/fem/assemble_scalar_impl.cpp
- cpp/dolfin/fem/assemble_vector_impl.cpp
- python/test/unit/fem/test_assemble_domains.py
Fixes issue #545 , see also FFCx https://github.com/FEniCS/ffcx/pull/154
However, current approach is still suboptimal. We fetch all coefficients for the whole form for each integral - even though if the integral is using only one of them. Improvement will come as additional PR, this is mainly to fix the bugs discovered by @francesco-ballarin .
> Fix coefficient offsets

- Dockerfile
`decorator` no longer used in Python tests. Removed from `Dockerfile`.
> Remove old test dependency

- cpp/dolfin/fem/DofMapBuilder.cpp
- cpp/dolfin/io/HDF5File.cpp
- cpp/dolfin/io/XDMFFile.cpp
- cpp/dolfin/io/xdmf_write.cpp
- cpp/dolfin/mesh/DistributedMeshTools.cpp
- cpp/dolfin/mesh/DistributedMeshTools.h
- cpp/dolfin/mesh/Mesh.cpp
- cpp/dolfin/mesh/Mesh.h
- cpp/dolfin/mesh/Ordering.cpp
- cpp/dolfin/mesh/Topology.cpp
- cpp/dolfin/mesh/Topology.h
- cpp/dolfin/mesh/TopologyComputation.cpp
- cpp/dolfin/refinement/ParallelRefinement.cpp
- python/src/mesh.cpp
- python/test/unit/io/test_XDMF.py
- python/test/unit/mesh/test_refinement.py
This pulls together the entity creation and numbering for edges and facets. 
Now, when they are created on demand, they are also given global indexing.
Future work will refactor `TopologyComputation::compute_entities()` and `DistributedMeshTools::number_entities()` so that the ghosting scheme can be updated.
> Consolidate mesh entity creation and numbering

- python/src/la.cpp
- python/test/unit/fem/test_nonlinear_assembler.py
The tests were not sufficient for ensuring ghost values were correctly set.
Simple changes introduce non-homogeneous BCs and initial guesses to the nonlinear tests.
Also adds blocked vector scatter and getter functions to the pybind layer.
> Improve nonlinear assembly tests

- cpp/dolfin/mesh/MeshFunction.h
- cpp/test/unit/CMakeLists.txt
- cpp/test/unit/mesh/MeshFunction.cpp
This PR introduces a new test case for the issue I highlighted in the discussion of #563.
I believe that, after #563 and the forthcoming changes to the remaining mesh entities, MeshFunction's values for shared entities are currently out of sync between sharing processes after MeshFunction::mark.
I believe that a fix would be to add a third argument `MeshRangeType::ALL` to `mesh::MeshRange` on line 233 of MeshFunction.h. Please advise if that is indeed the correct fix, and I will apply in a commit to this branch.
> Incompatibility of MeshFunction.mark and PR #563

- python/dolfin/fem/solving.py
This should be called as a PETSc option, i.e. `{"ksp_view": None}` and not forced on the user.
> Remove the behind the scenes ksp.view()

- cpp/dolfin/refinement/ParallelRefinement.cpp
- python/test/unit/mesh/test_refinement.py
Fixing issue #614 , using the information from the unrefined geometry in the mesh initializer.
> Fix issue 614 for refinement of 2D mesh resulting in 3D geometry

- python/src/mesh.cpp
- python/src/nls.cpp
A workaround to allow `nls.cpp` to compile with `python3 setup.py build --debug`.
Without this, we can't compile in debug mode.
> Some fixes to allow setup.py to run in debug mode

- cpp/dolfin/fem/assemble_vector_impl.h
I caught this while being lazy with the `using` directive in `.cpp` files, getting errors like
```
error: call of overloaded ‘assemble_vector(Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >&, const dolfin::fem::Form&)’ is ambiguous
dolfin/fem/assemble_vector_impl.h:44:5: note: candidate: void dolfin::fem::impl::assemble_vector(Eigen::Ref<Eigen::Matrix<double, -1, 1> >, const dolfin::fem::Form&)
assemble_vector(Eigen::Ref<Eigen::Matrix<PetscScalar, Eigen::Dynamic, 1>> b,
^~~~~~~~~~~~~~~
dolfin/fem/assembler.h:55:5: note: candidate: void dolfin::fem::assemble_vector(Eigen::Ref<Eigen::Matrix<double, -1, 1> >, const dolfin::fem::Form&)
assemble_vector(Eigen::Ref<Eigen::Matrix<PetscScalar, Eigen::Dynamic, 1>> b,
^~~~~~~~~~~~~~~
```
when including …
> Remove unnecessary include in assemble_vector_impl.h

- python/dolfin/mesh.py
- python/test/unit/fem/test_dofmap.py
- python/test/unit/mesh/test_refinement.py
Simple cleanup. Remove `Mesh.geometric_dimension()` in the python layer in favour of `Mesh.geometry.dim`
> remove Mesh.geometric_dimension()

- .circleci/config.yml
The messages from ctest currently convey no information about errors. With this option, it outputs anything outputted by the test if the test fails.
> ctest  output on failure

- cpp/CMakeLists.txt
Neighbourhood collective operations were introduced in MPI 3.0, and they are currently being used in `IndexMap`, should dolfinx require MPI 3?
> Require MPI-3

- cpp/dolfin/common/Table.cpp
* Fixes bug where table was not accumulating across processes, leading to timings being out by a factor of the number of processes
> Fix error in MPI reduction for timing tables

- cpp/dolfin/generation/BoxMesh.cpp
- cpp/dolfin/generation/BoxMesh.h
Improves the creation of `BoxMesh` in parallel, by distributing the cells and vertices across processes during creation.
* Allows the use of ParMETIS (which failed before, due to empty data on some processes)
* Removes an unnecessary permutation call for hex mesh.
* Consolidates code for hex/tet geometry creation which is the same.
* Should reduce runtime when running scaling benchmarks.
> Improve parallel boxmesh

- python/test/unit/fem/test_custom_assembler.py
and only look up petsc_dir once.
Closes Issue #718.
> use petsc4py to get PETSC_DIR path

- cpp/cmake/scripts/generate-cmakefiles.py
When MPIEXEC_PARAMS is defined at configure time
(cmake -DMPIEXEC_PARAMS=...) it allows flags like --oversubscribe
to be added where desirable
(e.g. to enable build tests on 2-cpu machines, where tests
use 3 processes via -np 3)
Applies commit d6c8cf8 from dolfin-old PR#519
> allow MPIEXEC_PARAMS to be added to test parameters

- .circleci/config.yml
Bit wasteful on CircleCI hours, but at least it should work. Multistage Dockerfiles and build caching seems to be work in progress at Docker HQ.
> Turn off two stage Docker image build

- cpp/dolfinx/mesh/DistributedMeshTools.cpp
- cpp/dolfinx/mesh/Mesh.cpp
- cpp/dolfinx/mesh/Partitioning.cpp
- python/test/unit/fem/test_assembler.py
- python/test/unit/mesh/test_ghost_mesh.py
This fixes the problem with ghost cells and IndexMap. 
Disables `shared_vertex` mode for now.
More clean up needs to be done, and also re-enabling `shared_vertex` mode.
> Fix numbering of cells in ghosted mesh

- python/dolfinx/mesh.py
I find the old definition to be confusing, especially in a code like the following
```
from dolfinx import *
mesh = UnitSquareMesh(MPI.comm_world, 3, 3)
mf = MeshFunction("size_t", mesh, 2, 0)
assert isinstance(mf, MeshFunction) # fails
```
> Define MeshFunction and MeshValueCollection as functions rather than classes in python layer

- python/test/unit/fem/test_fem_pipeline.py
Previous test did nothing, as locate_dofs_geometrical found all degrees of freedom in the function space and therefore this test did not check anything. Now using a combination of topology.on_boundary and locate_dofs_topological to set the bc properly
> Fixing pipeline test to actually do something

- cpp/dolfinx/fem/DirichletBC.cpp
Failixing example:
`mpirun -n 2 python3 file.py`
```
import dolfinx
import numpy
from dolfinx.fem import locate_dofs_topological
comm = dolfinx.MPI.comm_world
mesh = dolfinx.UnitSquareMesh(comm, 2, 2)
mesh.create_connectivity_all()
V = dolfinx.FunctionSpace(mesh, ("CG", 1))
facets = numpy.where(mesh.topology.on_boundary(1))[0]
if comm.rank == 0:
facets = facets[:-1]
marker = locate_dofs_topological(V, 1, facets)
assert(marker.size == 5)
```
In a next PR, I'll add some tests and use `MPI_Neighbor_alltoallv` .
> Fix get_remote_bcs1

- cpp/dolfinx/fem/ElementDofLayout.cpp
- cpp/dolfinx/fem/ElementDofLayout.h
- python/test/unit/mesh/test_mesh_utils.py
- Added some documentation for base permutations input of `ElementDofLayout`.
- Added asserts in the `ElementDofLayout` to check the shape of the base permutations, so that the assertion is hit rather than a segfault later.
> Document base permutations

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/mesh/Partitioning.cpp
`std::partial_sum` uses the input type for summation. When this is `int32` and the output type is `int64` there can be an overflow.
> Replace std::partial_sum where summation type overflows

- cpp/dolfinx/mesh/TopologyComputation.cpp
* When ghost cells are present, ensures that:
1. entities which only appear in ghost cells *are not* numbered locally
2. entities which never appear in ghost cells *are* numbered locally
3. entities shared between ghost and non-ghost cells are decided by lowest rank
* When no ghost cells are present, boundary entity ownership is decided by lowest rank.
The decision mechanism can be adjusted fairly easily in a future PR.
> Ghost entity ownership

- cpp/dolfinx/graph/SCOTCH.cpp
64-bit SCOTCH builds were broken.
> Fix SCOTCH int type

- python/dolfinx/plotting.py
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/mesh/test_mesh.py
Mixed geometry and topology. Get data from mesh.topology or mesh.geometry to make it unambiguous.
> Remove pybind11 mesh.cell helper

- cpp/dolfinx/common/MPI.cpp
- cpp/dolfinx/common/MPI.h
The following code
```
import gc
from dolfinx import MPI, Mesh
from dolfinx.cpp.mesh import CellType, GhostMode
def unit_cell():
points = np.array([[0.], [1.]])
cells = np.array([list(range(len(points)))])
mesh = Mesh(MPI.comm_world, CellType.interval, points, cells,
[], GhostMode.none)
return mesh
gc.disable()  # Manually control garbage collection
counter = 0
while True:
print("Iteration", counter)
unit_cell()
counter += 1
gc.collect()  # Force garbage collection
```
fails on master (on a dolfinx docker image) with
```
[...]
Iteration 2038
Iteration 2039
Iteration 2040
Iteration 2041
Traceback (most recent call last):
File "tmp.py", line 18, in <module>
unit_cell()
File "tmp.py", line 10, in unit_cell
[], GhostMode.none)
RuntimeError: Duplication of MPI communicator …
```
> Implement move assignment operator in MPI::Comm to make sure that previously held communicator is freed.

- cpp/dolfinx/io/VTKWriter.cpp
After separation of Geometry and Topology, the topology vertex ordering is different from the geometry vertex ordering. Therefore we have to convert them to be able to visualize mesh functions properly.
Minimal example were visualization fails on master:
```
import dolfinx
import dolfinx.io
mesh = dolfinx.UnitSquareMesh(dolfinx.MPI.comm_world, 2, 2)
mf = dolfinx.MeshFunction("size_t", mesh, mesh.topology.dim-1, 0)
dolfinx.io.VTKFile("mf.pvd").write(mf)
```
> Fix VTK Viusalization of facet functions

- cpp/dolfinx/io/xdmf_mf.h
... otherwise assertion gets triggered.
Let me know if you want me to add a simple test.
> Connectivity may need to be initialized when reading in a lower dimensional MeshFunction

- .circleci/config.yml
- python/dolfinx/fem/__init__.py
- python/dolfinx/fem/assemble.py
We forgot to rename this when changing dolfin to dolfinx. CI is now failing, but upon merging #895 CI will run correctly.
> Rename dolfin to dolfinx in flake8 check

- python/test/unit/fem/test_custom_assembler.py
Seems some details of the module search path have changed.
> Path fix in test for Python 3.8

- .circleci/config.yml
- .github/workflows/ccpp.yml
- cpp/CMakeLists.txt
- cpp/cmake/scripts/copy-test-demo-data.py
- cpp/cmake/scripts/generate-cmakefiles.py
- cpp/cmake/scripts/generate-form-files.py
- cpp/demo/CMakeLists.txt
- cpp/test/unit/CMakeLists.txt
This PR changes CMakeLists.txt and form generation stages for C++ demos and tests so that the files are generated in the build directory and not in the source tree.
@RizzerOnGitHub I believe this will fix both #888 and #893. If possible start from a clean repo and a clean build dir.
The changes included here are not fully backward compatible. In particular, the demos and unittests target are not added anymore to the main makefile. Instead, demos and tests should be configured as standalone projects after the core library has been installed. CI has been updated to reflect this change. I believe that this separation is beneficial for CI testing, because these standalone projects (especially demos) were previously not covered, but could have been used by end users.
The only remaining build …
> Generate C++ demo and test files in build directory, rather than source directory

- docker/Dockerfile
Was omitted previously because it required ParMETIS, which caused licensing issues. ParMETIS no longer required.
> Add superlu_dist to CircleCI docker build

- cpp/dolfinx/fem/assembler.cpp
- cpp/dolfinx/fem/assembler.h
- python/dolfinx/wrappers/fem.cpp
* Remove #ifdef and use Petsc typedefs. This should make compatibility simpler for complex and 64-bit builds.
> Remove some ifdefs, just use Petsc typedefs

- cpp/CMakeLists.txt
- cpp/cmake/scripts/generate-cmakefiles.py
This is a follow up to #897, that restores the capability to have automatically generated CMakeLists.txt in the demos source directory, as per @garth-wells request.
The changes introduced in #897 to accommodate the packaging pipeline by @RizzerOnGitHub are still in place (please @RizzerOnGitHub confirm by running your pipeline again, if possibile). This PR only fixes the non-backward compatible change that was introduced in #897: end users (and CI) are still supposed to configure and build demos in the build (or install directory), but CMakeLists.txt files are generated in the source tree as well (as it used to be before #897) to ensure better backward compatibility and easier development of new demos.
> Restore in-place generation of CMakeLists.txt files for demos

- .github/workflows/ccpp.yml
- cpp/dolfinx/fem/DofMap.cpp
- cpp/dolfinx/fem/DofMap.h
- cpp/dolfinx/fem/SparsityPatternBuilder.cpp
- cpp/dolfinx/fem/assemble_matrix_impl.cpp
- cpp/dolfinx/fem/assemble_matrix_impl.h
- cpp/dolfinx/fem/assemble_vector_impl.cpp
- cpp/dolfinx/fem/assemble_vector_impl.h
- cpp/dolfinx/fem/assembler.cpp
- cpp/dolfinx/la/SparsityPattern.cpp
- cpp/dolfinx/la/SparsityPattern.h
- python/demo/stokes-taylor-hood/demo_stokes-taylor-hood.py
- python/test/unit/fem/test_assembler.py
- python/test/unit/fem/test_custom_assembler.py
- python/test/unit/fem/test_nonlinear_assembler.py
- python/test/unit/nls/test_newton.py
Remove PetscInt from DofMap and assembly, copying dofs to 64-bit on-the-fly if PETSc is configured with 64-bit-indices.
> Use 32-bit index for DofMap

- cpp/dolfinx/mesh/Topology.cpp
These functions should check that the cell permutation data has been created instead of returning an empty list if it doesn't exist
> Check that data has been created before returning

- python/dolfinx/wrappers/mesh.cpp
Name was not exposed in Python which didn't allow to change it - and save multiple meshes into one file.
> Expose Mesh.name

- .github/workflows/Dockerfile
- .github/workflows/dockerimage.yml
Makes MUMPS available in 64-bit index builds.
> Bump petsc/slepc to v3.13 in Dockerfile

- cpp/dolfinx/fem/FormIntegrals.cpp
- cpp/dolfinx/geometry/BoundingBoxTree.cpp
- cpp/dolfinx/geometry/utils.cpp
- cpp/dolfinx/mesh/Mesh.cpp
- cpp/dolfinx/mesh/Mesh.h
- cpp/dolfinx/mesh/utils.cpp
- cpp/dolfinx/refinement/ParallelRefinement.cpp
- python/dolfinx/mesh.py
- python/dolfinx/plotting.py
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/fem/test_dofmap.py
- python/test/unit/fem/test_element_integrals.py
- python/test/unit/function/test_function.py
- python/test/unit/io/test_xdmf_meshdata.py
- python/test/unit/mesh/test_cell.py
- python/test/unit/mesh/test_face.py
- python/test/unit/mesh/test_ghost_mesh.py
- python/test/unit/mesh/test_mesh.py
This fixes a long-standing ambiguity around what is the 'number of mesh entities' (global, local, with or without ghosts), and for topological dimension zero whether it is vertices or geometric 'nodes'.
The caller must now go via `topology` (resolving the vertex vs geometric node ambiguity) and use the `index_map` for the entity dimension. `index_map` distinguishes between global, local and ghost.
Making this changes shows up numerous locations where code is probably broken for ghosted meshes. This change forces the caller to think about ghosting.
> Remove Mesh::num_entities

- cpp/dolfinx/io/XDMFFile.cpp
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/io/test_xdmf_mesh.py
- set name to mesh on reading,
- test it,
- re-enable 1D mesh tests,
- add `LOG(WARNING)` for writing function to a non-existing mesh. This could cause tons of issues because of the old interface - users are used to write functions only. Doing so Paraview crashes.
> Few XDMFFile improvements

- cpp/dolfinx/mesh/Mesh.cpp
- cpp/dolfinx/mesh/Mesh.h
- cpp/dolfinx/refinement/ParallelRefinement.cpp
- python/dolfinx/wrappers/mesh.cpp
Store actual topology/geometry objects (rather than pointers) and add move semantics to constructor.
> Avoid copies in Mesh construction

- cpp/dolfinx/graph/SCOTCH.cpp
`&vector[0]` is as an out-of-bounds access that is caught some platforms (an assertion inside
vector.h has to be active), e.g. Fedora 31, on others it is not, e.g. Ubuntu 20.04.
`vector.data()` will return a `nullptr` in this case with any failure.
> Fix issue #959: use vector.data() instead of &vector[0]

- cpp/dolfinx/common/utils.h
- cpp/dolfinx/mesh/MeshTags.h
- python/dolfinx/mesh.py
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/fem/test_assemble_domains.py
- python/test/unit/fem/test_element_integrals.py
- python/test/unit/io/test_xdmf_meshtags.py
- Makes implementation less implicit
- Move algorithms out of MeshTags
- Remove the bug-prone "double default arguments" of the same type in `MeshTags` constructor 
- Remove non-pure private functions
> Simplify MeshTag construction by requiring sorted and unique constructor arguments

- .circleci/config.yml
- python/dolfinx/fem/coordinatemapping.py
- python/dolfinx/fem/dofmap.py
- python/dolfinx/fem/form.py
- python/dolfinx/function.py
- python/dolfinx/wrappers/fem.cpp
An attempt to fix #966
**Update 1:**
Helpers `make_ufc_foo` now removed, pybind11 layer takes `uintptr_t`, dereferences and calls C++ helpers directly with ufc objects.
--- 
This fix changes `make_ufc_foo` to return from `uintptr_t` an actual `ufc_foo` object.
This has the advantage in lifetime management, because anyone calling `make_ufc_foo` makes a copy of an actual ufc object pointed to. It defaults to pybind11 `return_value_policy::copy` so new returned object has lifetime now managed on Python side, while the "old" cdata structure returned directly by FFCx JIT is usually garbage collected (we do not store a reference to it, e.g. in form.py).
> Fix UFC JIT objects memory management

- python/demo/mixed-elasticity-sc/static-condensation-elasticity.py
- python/test/unit/fem/test_custom_assembler.py
Probably a bug in 0.49.0 Numba version, the behaviour doesn't match their documentation.
> Fix numba cffi_support import

- cpp/dolfinx/function/Function.cpp
Here is a probably unintended copy of DofMap in create_vector (admittedly, that the getters returning shared_ptr are a tricky copy trap...). Also, I suppose that the "heavy" data member of DofMap, `_dofmap` could be turned into a shared_ptr<const>, which would make copies cheap.
> Avoid copy in `create-vector`

- cpp/dolfinx/common/TimeLogManager.cpp
- cpp/dolfinx/common/TimeLogger.h
Bring the implementation close to the canonical "Meyers'" singleton.
> Do not use "new" for singleton, since the destructor will never be called

- cpp/dolfinx/fem/assemble_vector_impl.cpp
- python/test/unit/fem/test_assembler.py
Fixes loop range for lifting on ghosted meshes, and enable more tests with ghosting.
Fixes some issues in #1003.
> Fix bc lifting on ghosted mesh

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/common/IndexMap.h
- cpp/dolfinx/fem/DofMap.cpp
- cpp/dolfinx/fem/DofMapBuilder.cpp
- cpp/dolfinx/fem/utils.cpp
- cpp/dolfinx/graph/Partitioning.cpp
- cpp/dolfinx/graph/Partitioning.h
- cpp/dolfinx/la/SparsityPattern.cpp
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/TopologyComputation.cpp
- cpp/dolfinx/refinement/ParallelRefinement.cpp
- cpp/test/unit/common/index_map.cpp
- python/dolfinx/wrappers/common.cpp
- Remove `_all_ranges` completely and also some unnecessary `MPI_Allgather` calls (one per IndexMap construction). For that, I included a vector with the ghost owners to the IndexMap constructor;
- The function `get_global_ghost_owners` is only used for debugging.  I can remove it;
- Added global_size as a private member variable, can also be removed and calculated on demand. But the communication cost is hidden (nonblocking communication).
Next PR asymmetric neighborhood communication and optimization. I've split it into more parts to make it easier to review.
> IndexMap: Remove _all_ranges and MPI_Allgather calls

- .circleci/config.yml
- cpp/dolfinx/generation/BoxMesh.cpp
- cpp/dolfinx/generation/IntervalMesh.cpp
- cpp/dolfinx/generation/RectangleMesh.cpp
- cpp/dolfinx/io/XDMFFile.cpp
- cpp/dolfinx/io/cells.cpp
- cpp/dolfinx/io/cells.h
- cpp/dolfinx/mesh/Mesh.cpp
- cpp/dolfinx/mesh/Mesh.h
- cpp/dolfinx/refinement/ParallelRefinement.cpp
- python/demo/gmsh/demo_gmsh.py
- python/dolfinx/io.py
- python/dolfinx/mesh.py
- python/dolfinx/wrappers/io.cpp
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/fem/test_dof_permuting.py
- python/test/unit/io/test_xdmf_mesh.py
- python/test/unit/mesh/test_higher_order_mesh.py
- python/test/unit/mesh/test_meshtags.py
`mesh::create` --> `mesh::create_mesh` to be analogous to `mesh::create_meshtags`,
`cell_perm_vtk` --> `perm_vtk` to have the same name as in c++,
`perm_gmsh()` now takes the same arguments as `perm_vtk()`.
> Mesh naming consistecy fixes

- cpp/dolfinx/io/XDMFFile.cpp
It seems `<Information>` cannot have value in its body, despite XDMF wiki says so. We need to store value in an attribute `<Information Value="...">`, otherwise ParaView crashes. Credit: @anzil
> Change <Information> storage

- python/dolfinx/io.py
This adds missing cell type mapping for `line`, `line3` and `line4` as well as `vertex` to dictionary `_gmsh_cells`.
> Add mapping for gmsh cell types line, line3, line4 and vertex

- cpp/CMakeLists.txt
- cpp/cmake/modules/FindUFC.cmake
- python/cmake/FindMPI4PY.cmake
- python/cmake/FindPETSc4py.cmake
- python/setup.py
-  Move `find_package(Python3)` to the top level CMakeList
- Use `FindPython3` module, `FindPythonInterp` is deprecated since CMake 3.12.  The new module allows to find active virtualenv python (good for hpc systems !).
- Read `UFC_INCLUDE_DIR` environment variable. (It was not being used)
- Bump CMake version (?)
> Fix minor problems with cmake-python

- cpp/dolfinx/geometry/BoundingBoxTree.h
- cpp/dolfinx/geometry/utils.cpp
- cpp/dolfinx/geometry/utils.h
- python/dolfinx/geometry.py
- python/test/unit/geometry/test_gjk.py
- python/test/unit/mesh/test_cell.py
Works for all mesh entities.
Makes a linear approximation of the curved geometry.
This is the first step in better support of collision detection for higher order meshes.
> Change squared_distance to handle arbitrary order geometries

- cpp/dolfinx/refinement/ParallelRefinement.cpp
- cpp/dolfinx/refinement/ParallelRefinement.h
Bug reported at [discourse](https://fenicsproject.discourse.group/t/dolfinx-dim-change-in-mesh-refinement-and-parent-children-relationship/3492)
MWE:
```
import dolfinx
import ufl
points = np.array([[0, 0],  [1.2, 0],  [1.5, 1],  [0.2, 1]])
cells = np.array([[0, 1, 2],  [0, 2, 3]])
cell = ufl.Cell("triangle", geometric_dimension=2)
domain = ufl.Mesh(ufl.VectorElement("Lagrange", cell, 1))
mesh = dolfinx.mesh.create_mesh(MPI.COMM_WORLD, cells, points, domain)
print(mesh.topology.dim, mesh.geometry.dim)  # 2   2
mesh2=refine(mesh)
print(mesh2.topology.dim, mesh2.geometry.dim)  # 2 3
```
This is the least intrusive way of slicing the new_vertex_coordinates, as the returned midpoints are 3D.
> Keep the geometrical dimension of parent mesh when refining

- cpp/dolfinx/io/xdmf_function.cpp
Caused functions on higher-order meshes impossible to write.
This is just a hotfix. I'll simplify functions IO for isoparametric elements only in a coming PR.
> Bugfix for IO of functions on higher-order meshes

- python/dolfinx/fem/assemble.py
- python/test/unit/fem/test_assembler.py
- Fix return type (hint) and diagonal value
- remove python 'for loop'
> Minor changes to asemble csr matrix

- .circleci/config.yml
- README.md
- docker/Dockerfile
- docker/dolfinx-complex-mode
- docker/dolfinx-real-mode
I propose three concrete images in this new `Dockerfile`: `dolfinx/dev-env`, `dolfinx/dolfinx` and `dolfinx/lab`.
Still TODO:
1. Shell script to switch between dolfinx in real and complex modes.
2. Update CircleCI (and/or GH actions) nightly builds.
> Simplify Docker image hierarchy

- cpp/dolfinx/function/FunctionSpace.cpp
Due to brackets in the wrong place, this block is being run for each cell rather than just once.
> Remove extra loop brackets

- python/test/unit/fem/test_custom_assembler.py
C type `int` is not guaranteed to be an `np.int32`, better to use `np.intc`.
Reflects change made in FFCX unit tests (https://github.com/FEniCS/ffcx/pull/271).
> Change int32 to intc in test that calls UFC interface.

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/common/IndexMap.h
- cpp/dolfinx/common/MPI.cpp
- cpp/dolfinx/common/MPI.h
- cpp/dolfinx/fem/DofMapBuilder.cpp
- cpp/dolfinx/graph/Partitioning.cpp
- cpp/dolfinx/graph/Partitioning.h
- cpp/dolfinx/io/xdmf_utils.cpp
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/Topology.h
- cpp/dolfinx/mesh/TopologyComputation.cpp
- cpp/dolfinx/refinement/ParallelRefinement.cpp
- cpp/dolfinx/refinement/ParallelRefinement.h
Two different spellings of _neighbor_ are used. 
The idea of this PR is to set one, to make it easier to search for variables or functions...
> Fix neighbor spelling

- cpp/dolfinx/fem/DofMap.cpp
- cpp/dolfinx/fem/DofMap.h
- cpp/dolfinx/fem/assemble_matrix_impl.h
- cpp/dolfinx/fem/assemble_scalar_impl.h
- cpp/dolfinx/fem/assemble_vector_impl.h
- cpp/dolfinx/graph/BoostGraphOrdering.cpp
- python/demo/elasticity/demo_elasticity.py
- python/dolfinx/plotting.py
- python/dolfinx/wrappers/fem.cpp
- python/dolfinx/wrappers/graph.cpp
- python/test/unit/fem/test_custom_assembler.py
- python/test/unit/fem/test_dofmap.py
- python/test/unit/fem/test_expression_evaluation.py
- python/test/unit/la/test_krylov_solver.py
- python/test/unit/la/test_nullspace.py
- python/test/unit/mesh/test_meshtags.py
- Add 'transpose' dofmap (maps global index to local cell contributions). Used the assemble/accumulate unassembled vectors in a thread-safe fashion.
- Add test that uses `numba.prange` to parallelise an assembly loop
- Some performance optimisations in the assemblers
> Add Numba parallel (threaded) assembly example

- cpp/demo/hyperelasticity/main.cpp
- cpp/demo/poisson/main.cpp
- cpp/dolfinx/common/SubSystemsManager.cpp
- cpp/dolfinx/common/SubSystemsManager.h
- cpp/dolfinx/la/PETScVector.cpp
- python/dolfinx/__init__.py
- python/dolfinx/wrappers/common.cpp
This removes the rather ugly singleton for initialising and finalising MPI, PETSc, etc from C++. It makes the actions explicit and removes one of the problem areas for multi-threaded applications.
This change is consistent with the C++ interface being explicit. It does not affect the Python interface.
> Remove singleton class (SubSystemsManager)

- python/setup.py
The pybind11 CMake module reads PYTHON_EXECUTABLE and the PETSc4py CMake module reads Python3_EXECUTABLE. We should specify both to avoid potential problems of having two different pythons in the same build.
> pass PYTHON_EXECUTABLE as well as Python3_EXECUTALBE from setup.py to make

- cpp/dolfinx/common/SubSystemsManager.cpp
- cpp/dolfinx/graph/Partitioning.cpp
- cpp/dolfinx/mesh/Topology.cpp
- python/dolfinx/__init__.py
- python/dolfinx/wrappers/fem.cpp
* Fixes a deadlock in topology computation when certain processes have no ghost cells.
* Enables logging output with `-dolfinx_loglevel` (unambiguous) command-line option.
> Re-enable logging from command line with better argument

- .github/workflows/ccpp.yml
See e.g.
https://github.com/francesco-ballarin/dolfinx/actions/runs/197560010
for a failing run before this commit, and
https://github.com/francesco-ballarin/dolfinx/actions/runs/197642963
for a successful run with this commit
> Skip github action related to documentation push on fenicsproject.org when running on forks

- python/dolfinx/wrappers/fem.cpp
Was missing the standard boiler plate code to accept `uintptr_t` and cast back into `ufc_dofmap`.
> Wrap create_element_dof_map into Python using `uintptr_t`

- cpp/CMakeLists.txt
- cpp/cmake/templates/DOLFINXConfig.cmake.in
- cpp/dolfinx/CMakeLists.txt
The PR use just one way to detect Boost (using the Boost provided CMake file). This avoids the issue when CMake provided the Boost detection, but the Boost release post-dates the CMake release (the CMake Boost needs updating every time there is a Boost release).
This change requires Boost >= 1.70, which was the first version to include CMake files.
The CMake output for finding Boost had been made more verbose to make it easier to check which Boost installation is being picked up.
The PR also supports Spack installs (further updates on this to follow).
> Update and simplify Boost detection

- python/dolfinx_utils/test/fixtures.py
Hotfix for failing IO tests. Adds a 1s waiting loop to assure os.mkdir did touch the filesystem.
> Wait for os.mkdir

- cpp/dolfinx/mesh/utils.cpp
- cpp/dolfinx/mesh/utils.h
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/mesh/test_surface_mesh.py
Add two utility functions to `mesh::` 
* `entities_to_geometry` - computes the indices in `mesh::Geometry` of the vertices of the given entities
- this is needed in several places in the library, and will be useful for future refactoring
* `exterior_facet_indices` - computes the facet indices of facets which lie on the external surface.
- the logic is similar to that in `FormIntegrals`. It does not return exterior facets of ghost cells.
By using `facet_indices = exterior_facet_indices(mesh);` we can obtain a list of topology indices for surface facets (unoriented),
Further by using `geom_indices = entities_to_geometry(mesh, tdim -1, facet_indices, true);` we get the oriented geometry.
> Surface facet calculation

- cpp/dolfinx/fem/CoordinateElement.cpp
- cpp/dolfinx/fem/CoordinateElement.h
Allows caller to control the tolerance.
> Add eps argument for Newton solver in CoordinateElement

- python/dolfinx/wrappers/fem.cpp
After #1168 these two functions has to be exposed to be able to do numba assembly with subdomains.
> Expose cpp form functions

- cpp/dolfinx/fem/Form.h
- cpp/dolfinx/fem/assemble_vector_impl.h
- python/test/unit/fem/test_assemble_domains.py
This assembles boundary conditions to the RHS, i.e. `b = b - A*b`, where `A` is now the correct local element tensor, including contributions from all subdomains and interior facet integrals. Fixes a critical bug #1110 .
I've restructured the code a bit so it has the same pattern as for assemble functions, meaning there is high level `apply_lifting()` which handles BC for all subdomains of the mesh and then there are specific `_lift_bc_cells, _lift_bc_exterior_facet, _lift_bc_interior_facet` which runs on a given subset of active mesh entities.
Some code repetition appears which could be maybe refactored in the future.
> Fix BC application

- cpp/dolfinx/fem/utils.h
The user can now safely set `assume_aligned` in FFCX.
Fix for issue #1171.
> Pack constants into aligned Eigen array

- cpp/dolfinx/mesh/utils.cpp
- cpp/dolfinx/mesh/utils.h
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/mesh/test_face.py
Current master is broken, as the following test:
```
def test_normals(cube, square):
""" Test that cell normals of a set of facets """
def left_side(x):
return numpy.isclose(x[0], 0)
fdim = cube.topology.dim - 1
facets = locate_entities_boundary(cube, fdim, left_side)
normals = cell_normals(cube, fdim)
assert(numpy.isclose(normals[facets], [-1, 0, 0]).all(axis=1).all())
fdim = square.topology.dim - 1
facets = locate_entities_boundary(square, fdim, left_side)
normals = cell_normals(square, fdim)
assert(numpy.isclose(normals[facets], [-1, 0, 0]).all(axis=1).all())
```
would return gibberish if we exposed `cell_normals` to the python layer. This is because it is missing the topology->geometry mapping, which was created way back when we separated mesh topology and geometry.
This pull request …
> Fix broken code for cell_normals and make it more efficient by using entitiy lists

- cpp/cmake/modules/FindPETSc.cmake
- cpp/cmake/modules/FindSLEPc.cmake
Following on from PR#1195, when looking for PETSc and SLEPC in pkg_search_module, pkgconfig priority was previously given to the cray version of the pkgconfig files. This patch restores that priority, after including lowercase petsc and slepc as alternative pkg names.
> give priority to cray pkgconfig files when searching for PETSc, SLEPc

- cpp/dolfinx/CMakeLists.txt
Use Eigen's default. User can specify with EIGEN_MAX_ALIGN_BYTES.
> Remove DOLFINX_EIGEN_MAX_ALIGN_BYTES

- cpp/dolfinx/common/utils.h
- cpp/dolfinx/io/xdmf_mesh.cpp
- cpp/dolfinx/io/xdmf_mesh.h
- cpp/dolfinx/io/xdmf_meshtags.h
- cpp/dolfinx/io/xdmf_utils.h
- python/test/unit/io/test_xdmf_meshdata.py
- python/test/unit/io/test_xdmf_meshtags.py
Improved version of #1223, writing only owned entities of mesh tags to file to avoid duplication in parallel.
> XDMFFile.write_meshtags for owned entities

- cpp/dolfinx/CMakeLists.txt
This patch exposed a number of alignment issues that we are currently investigating. Forcing the alignment of Eigen allocated memory in DOLFINX to 32 seems to 'fix' the issue.
> Revert "Remove DOLFINX_EIGEN_MAX_ALIGN_BYTES (#1213)"

- python/dolfinx/__init__.py
- python/dolfinx/common.py
- python/dolfinx/wrappers/common.cpp
As `dolfinx::Table` is not wrapped to Python, this binding would only cause an error, see: #1217. This PR removes it.
> Remove timings binding

- .github/workflows/spack.yml
- cpp/dolfinx/mesh/GraphBuilder.cpp
- cpp/dolfinx/mesh/GraphBuilder.h
In `GraphBuilder::compute_local_dual_graph_keyed` we have currently:
```
facet[k] = vertices[facet_vertices(j, k)];
```
where `facet` is int32 and `vertices` is `int64`. This narrowing could lead to errors for meshes with a large number of nodes.
> Fix int64->int32 narrowing bug

- cpp/dolfinx/fem/CoordinateElement.cpp
- cpp/dolfinx/fem/CoordinateElement.h
- python/dolfinx/wrappers/fem.cpp
Some practitioner's meshes fail to do any IO, since it is calling eval() which needs physical-to-reference map. This small change allows users to do
```python
mesh.geometry.cmap.non_affine_atol = 1.0e-8
mesh.geometry.cmap.non_affine_max_its = 20
```
(or whatever works) before the respective NR calls.
> Allow control of non-affine NR iterations

- cpp/dolfinx/common/SubSystemsManager.cpp
- cpp/dolfinx/mesh/GraphBuilder.cpp
- cpp/dolfinx/mesh/GraphBuilder.h
- cpp/dolfinx/mesh/Partitioning.cpp
- cpp/dolfinx/refinement/utils.cpp
This PR updates the dual graph builder, which processes raw mesh topology before partitioning.
* Check for error conditions (e.g. >2 cells sharing a facet)
* Use AdjacencyList more
* Provide better load balancing of the global match phase (speeds up overall computation)
> Graphbuilder checks

- cpp/dolfinx/fem/assemble_matrix_impl.h
- python/test/unit/fem/test_vector_assemble.py
Introduced in #1242, which only changed assembly routines for cell integrals. This PR fixes these two issues, and adds two simple tests that yielded `Loguru caught a signal: SIGABRT` without the fix
Co-authored and debugged with @chrisrichardson
> Fix assembly of interior and exterior facets for vector spaces

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/common/IndexMap.h
- python/dolfinx/wrappers/common.cpp
This function is a duplicate of `IndexMap::global_indices()` and is not used anywhere in the code base. It also has a type (IndexMap.cpp, Line 569) causing crashes if ever used in parallel.
> Remove IndexMap.indices()

- docker/Dockerfile
Removed aggressive compiler flags from KaHIP `CMakeList` that "apparently" break portability 
(KaHIP is crashing with illegal hardware instruction errors on some docker images).
An issue has been filed in the KaHIP repository.
> Test branch to fix KaHIP on containers

- .circleci/config.yml
- .github/workflows/ccpp.yml
- python/CMakeLists.txt
Improves stack trace caught by loguru.
Pybind11 always adds `-fvisibility=hidden` for some internal reasons (and performance), which hides symbols and makes backtraces which dynamically load `/usr/local/lib/python3.8/dist-packages/dolfinx/cpp.cpython-38-x86_64-linux-gnu.so` not very informative.
With this PR any segfault during assembler (dolfinx header code) is nicely caught (only in debug mode) as 
```
...
8       0x7fb2e8ed8b83 void dolfinx::fem::assemble_matrix<double>(std::function<int (int, int const*, int, int const*, double const*)> const&, dolfinx::fem::Form<double> const&, std::vector<std::shared_ptr<dolfinx::fem::DirichletBC<double> const>, std::allocator<std::shared_ptr<dolfinx::fem::DirichletBC<double> const> > > const&) + 1379
7       0x7fb2e8ee8b2f void …
```
> Compile pybind11 wrappers in debug mode, expose symbols

- cpp/dolfinx/fem/dofmapbuilder.cpp
* Remove `owned[]` array 
* Remove `pos[]` array and release `offsets[]` a bit earlier.
* Should save a bit of memory and maybe time in this code which is at the high-water mark of mesh generation
> Dofmapbuilder optimise

- .github/workflows/intel.yml
Tests with classic Intel compilers are disabled due to an issue with pybind.
Once that is solved I can re-enable the tests.
Fix expected to pybind version 2.6.2:
https://github.com/pybind/pybind11/issues/2771
> Test intel compilers

- .circleci/config.yml
- .github/workflows/ccpp.yml
- cpp/dolfinx/generation/BoxMesh.cpp
- cpp/dolfinx/io/cells.cpp
- cpp/dolfinx/mesh/Geometry.cpp
- cpp/dolfinx/mesh/cell_types.cpp
- python/dolfinx/wrappers/fem.cpp
- python/test/unit/fem/test_fem_pipeline.py
- python/test/unit/io/test_xdmf_mesh.py
- python/test/unit/mesh/test_higher_order_mesh.py
Correct a few bugs in how higher order meshes are handled.
Added scalar pipeline tests using Unit meshes to be sure there are not broken.
Simplified higher order mesh tests and added 3D tests.
Close #54
> Higher order meshes

- cpp/dolfinx/fem/FiniteElement.cpp
- cpp/dolfinx/fem/FiniteElement.h
- cpp/dolfinx/fem/Function.h
- cpp/dolfinx/fem/evaluate.h
- cpp/dolfinx/fem/interpolate.h
- python/test/unit/function/test_function.py
Fixes #1358 and another potential issue in FiniteElement only getting the interpolation matrix from basix once
Some additional bug-fixes in interpolation, and proper error handling for mixed elements or invalid lambda functions.
> Fix interpolation speed regression

- python/test/unit/function/test_function.py
Rewriting assign test to use petsc vectors. Could probably be removed as it does not really test any dolfin-x functionality (but we should probably illustrate this in a demo).
Also removing old interpolation test by testing the tiny things it did in other tests.
> Cleanup tests

- cpp/dolfinx/common/MPI.h
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/topologycomputation.cpp
- cpp/dolfinx/refinement/utils.cpp
Just brings `dolfinx::MPI::neighbor_all_to_all` to the same interface as `dolfinx::MPI::all_to_all`
> Use AdjacencyList as input for neighbour all-to-all

- cpp/dolfinx/fem/CoordinateElement.cpp
- cpp/dolfinx/fem/CoordinateElement.h
- cpp/dolfinx/fem/FiniteElement.cpp
- cpp/dolfinx/fem/FiniteElement.h
- cpp/dolfinx/fem/Function.h
- cpp/dolfinx/mesh/Topology.cpp
Eigen Tensors can't be sliced (only single items can be accessed), and are a huge pain to wrap with pybind. Until a new version of Eigen comes out with proper Tensor support std::vector might be better?
> Removed Eigen::Tensor

- python/dolfinx/wrappers/fem.cpp
- python/dolfinx/wrappers/mesh.cpp
To be able to use dolfinx::array2d in python the need to be wrapped up as py:array_t.
> Fix returntypes for dolfinx::array2d

- cpp/dolfinx/io/xdmf_function.cpp
- cpp/dolfinx/io/xdmf_utils.cpp
Fixes a bug which forced any function with block size > 1 be evaluated into "point values" (i.e. interpolated into CG1) even if the underlying element was DG0.
> Fix block-size for cell-centered data in XDMF IO

- python/dolfinx/wrappers/graph.cpp
Needed to specify ghost cells in shared facet mode with custom partitioner
> add adjacency nested list to python for mesh partitioning

- docker/Dockerfile
basix now installs from folder python/.
> Fix basix install directory

- docker/Dockerfile
- python/CMakeLists.txt
Will have to see if this increases size of final image or whether Docker can work out that many COPYed files are the same between intermediate and dev-env images. At least it should now work.
> libbasix.so was not being copied from intermediate to final image.

- python/dolfinx/wrappers/fem.cpp
- python/test/unit/fem/test_assembler.py
Fixes current broken pybind, which translates `int*` as `int` for python.
> Fix python lambda assembler

- docker/Dockerfile
- python/demo/gmsh/demo_gmsh.py
As Eigen is out of basix, we can bump gmsh without getting alignment segfaults.
Fix one interface change from 4.6.0 -> 4.8.0
> Bump GMSH to 4.8.0

- .circleci/config.yml
- .github/workflows/ccpp.yml
- cpp/dolfinx/fem/CoordinateElement.cpp
- cpp/dolfinx/fem/CoordinateElement.h
- cpp/dolfinx/fem/utils.cpp
Added permute_dofs and unpermute_dofs functions to Basix, so these can be removed from the generated code.
This PR is coupled with FEniCS/basix#187 and FEniCS/ffcx#325.
> Move permute_dofs and unpermute_dofs functions from FFCx to Basix

- cpp/CMakeLists.txt
- cpp/demo/hyperelasticity/main.cpp
- cpp/demo/poisson/main.cpp
- cpp/dolfinx/CMakeLists.txt
- cpp/dolfinx/fem/CoordinateElement.cpp
- cpp/dolfinx/fem/CoordinateElement.h
- cpp/dolfinx/fem/Function.h
- cpp/dolfinx/fem/FunctionSpace.cpp
- cpp/dolfinx/fem/interpolate.cpp
- cpp/dolfinx/fem/interpolate.h
- cpp/dolfinx/fem/utils.cpp
- python/dolfinx/wrappers/fem.cpp
Co-author: @jorgensd 
- Remove tabulation from loops:
- `CoordinateElement::push_forward` now receives the tabulated data.
- Created a function to compute the jacobian and related data `compute_jacobian_data` given the tabulated data at the interpolation points (reference domain). In main, a newton to back engineer the interpolation point using compute reference geometry, which is not necessary because the we know the interpolation points.
- Introduce xtensor to communicate directly with `basix::FiniteElement`
- Use xtensor to allocate large datasets (instead of array2d or vector because they need initialization).
- Remove Eigen::Replicate and avoid some lazy computation, which were expensive.
Further optimizations (in a future PR):
- Special treatment for Lagrange elements …
> Refactor expression interpolation

- cpp/dolfinx/common/linalg.h
- cpp/dolfinx/common/math.h
- cpp/dolfinx/fem/CoordinateElement.cpp
xtensor and numpy compute the determinant using LU decomposition.
This PR introduces formulas that are more accurate and faster for matrices up to 3x3.
Impact on performance:
```python3
mesh = dolfinx.UnitCubeMesh(comm, 100, 100, 100, CellType.tetrahedron)
V = dolfinx.FunctionSpace(mesh, ("N1curl", 1))
```
| | Main | This branch |
| :---         |     :---:      |          :---: |
| `compute_point_values`   | 21.30 s    | 17.13 s   |
| `interpolate`    | 47.74 s     | 32.91 s    |
```python3
mesh = dolfinx.UnitCubeMesh(comm, 100, 100, 100, CellType.hexahedron)
V = dolfinx.FunctionSpace(mesh, ("NCE", 1))
```
| | Main | This branch |
| :---         |     :---:      |          :---: |
| `compute_point_values`   | 19.59 s| 15.64 s  |
| `interpolate`    |  58.31 s      | 16.42 s  |
```python3 …
```
> Introduce accurate formulas for determinant and inverse of small matrices

- cpp/dolfinx/fem/CoordinateElement.cpp
- python/dolfinx/wrappers/fem.cpp
- `const double` is intepreted by pybind11 as longdouble.
- The assert on shape(2) (3rd dimension) makes no sense on an array of dimension 2.
> Bug fixes in CoordinateElement

- cpp/dolfinx/fem/interpolate.cpp
Instead of calling push forward with a repeated `ij`-loop and zeroing of data, merge the loops with direct assignment of an accumulator.
Speed-ups compared to main for Nedelec and Lagrange showed below.
> Optimization of `interpolation_coords`

- python/demo/gmsh/demo_gmsh.py
Part of the step by step approach of bumping gmsh. 
We start with updating syntax that is deprecated in future releases.
> Change getboundary to modern syntax

- cpp/dolfinx/common/CMakeLists.txt
As the math header is very useful for other C++ code that uses dolfinx, I suggest exposing it.
> Expose math header

- python/dolfinx/__init__.py
Something changed about install location since you wrote this code last year @garth-wells.
> Python related includes are installed into `wrappers/`

- cpp/dolfinx/fem/dofmapbuilder.cpp
Fixes Issue #1535 caused by unallocated vector of size zero.
> Increase vector size for OpenMPI

- cpp/dolfinx/fem/assemble_matrix_impl.h
- cpp/dolfinx/fem/assemble_scalar_impl.h
- cpp/dolfinx/fem/assemble_vector_impl.h
- cpp/dolfinx/fem/assembler.h
- cpp/dolfinx/fem/evaluate.h
- cpp/dolfinx/fem/petsc.cpp
- cpp/dolfinx/fem/petsc.h
- python/dolfinx/wrappers/fem.cpp
This change allows form constants and coefficients to be re-used, avoiding unnecessary re-computation in cases.
> Allow user to supply form constants and coefficients to assemblers

- docker/Dockerfile
Resolves #1328.
GMSH built from source with OpenCascade and OpenMP support.
Instruction set tested locally and in #1500
> Gmsh bump + src install

- python/test/unit/io/test_xdmf_meshtags.py
Use `numpy.int32`, etc, in place of `numpy.intc`. Fixes #1289.
> Use fixed-with Numpy integer types

- cpp/dolfinx/nls/NewtonSolver.cpp
Issue reported by Sandeep:
Using the NewtonSolver with `convergence_check` residual leaves the rtol to infinity, as `_residual0` is never initialized.
> Residual0 now initialized for residual method.

- python/dolfinx/wrappers/fem.cpp
Expose booleans required for python assemblers
> Expose dof permutation bools

- cpp/dolfinx/la/Vector.h
One can use usm_allocator and use SYCL kernels:
```c++
using usm_alloc = cl::sycl::usm_allocator<double, cl::sycl::usm::alloc::shared>;
auto map = V->dofmap()->index_map;
int bs = V->dofmap()->bs();
cl::sycl::queue q;
usm_alloc myAlloc(q);
dolfinx::la::Vector<double, usm_alloc> b(map, bs, myAlloc);
auto&& vec = b.mutable_array();
// Get pointer to vector data for access in SYCL kernel
double* data = vec.data();
int size = vec.size();
q.submit([&](cl::sycl::handler& h) {
h.parallel_for(cl::sycl::range<1>(size), [=](cl::sycl::id<1> idx) { data[idx] = idx; });
}).wait();
for (auto e : vec)
std::cout << e << " ";
```
> Template la::Vector over allocator

- cpp/dolfinx/common/array2d.h
```c++
_storage = std::vector<T, Allocator>(shape[0] * shape[1], value, alloc);
```
Calls a deleted copy constructor with USM allocator.
> Fix array2d for USM allocators

- cpp/demo/hyperelasticity/main.cpp
- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/common/IndexMap.h
- cpp/dolfinx/common/MPI.cpp
- cpp/dolfinx/common/MPI.h
- cpp/dolfinx/fem/DirichletBC.cpp
- cpp/dolfinx/fem/dofmapbuilder.cpp
- cpp/dolfinx/fem/petsc.cpp
- cpp/dolfinx/fem/utils.cpp
- cpp/dolfinx/la/PETScVector.cpp
- cpp/dolfinx/la/Vector.h
- cpp/dolfinx/refinement/utils.cpp
Very rarely needed and often mis-used.
> Remove the  'symmetric' neighbourhood communicator from IndexMap

- cpp/dolfinx/mesh/Mesh.cpp
- cpp/dolfinx/mesh/graphbuild.cpp
- cpp/dolfinx/mesh/graphbuild.h
Number of passes was 25, which was a left over from testing.
> Reduce number of GPS re-ordering passes for mesh cells

- python/demo/helmholtz2D/demo_helmholtz_2d.py
Fix a few things in the Helmholtz demo:
- Use solver that is consistent in serial and parallel (reported by @adeebkor ).
- Remove unused function
- <s>Use scatter forward after interpolation
> Cleanup helmholtz demo

- cpp/dolfinx/la/Vector.h
Fixes a double-free memory problem in la::Vector
> Add MPI_Type_dup to copy and move

- python/dolfinx/wrappers/nls.cpp
To be able to monitor number of linear iterations per Newton step.
Could also be used to vary the relaxation parameter.
> Expose set_update in newton-solver 

- python/test/unit/fem/test_element_integrals.py
This PR adds a test for "RTCF" elements. See https://github.com/FEniCS/ffcx/issues/373 for more information. This test failed before https://github.com/FEniCS/ufl/pull/63 was merged.
> Add test for "RTCF" elements 

- .github/workflows/ccpp.yml
This should prevent occasional failing tests (eg https://github.com/FEniCS/dolfinx/runs/3018905856) due to two version pushing at almost the same time
> Only push real32 docs

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/common/IndexMap.h
- cpp/dolfinx/fem/DofMap.cpp
- cpp/dolfinx/fem/Form.h
- cpp/dolfinx/fem/dofmapbuilder.cpp
- cpp/dolfinx/la/Vector.h
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/utils.cpp
This gives lower-level control over scatters, and allows us to work with just the required data and doesn't force callers to pass other data.
> Permit only required data to be passed to IndexMap scatters

- .github/workflows/docker-build-env.yml
- .github/workflows/docker-end-user.yml
When a tag is created, this will push docker images with that tag (eg `dolfinx/dolfinx:v0.1.1-arm64` `dolfinx/lab:v0.1.1-amd64` etc).
Fixes #1610
> Push docker images with tag prefix

- cpp/CMakeLists.txt
- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/graph/partition.cpp
Set re-ordering flag to false in `MPI_Dist_graph_create_adjacent`. Setting to true allows global ranks to be re-ordered (which would break things), but few, if any, implementation support re-ordering so the issue didn't show up.
Also uses more `std::transform` in place of plain loops.
> Fix misunderstanding of MPI dist graph comm reordering

- .github/workflows/intel.yml
- cpp/dolfinx/generation/BoxMesh.cpp
- cpp/dolfinx/generation/RectangleMesh.cpp
- cpp/dolfinx/io/VTKFile.cpp
- cpp/dolfinx/io/xdmf_mesh.cpp
- cpp/dolfinx/io/xdmf_utils.cpp
- cpp/dolfinx/mesh/Geometry.h
- cpp/dolfinx/mesh/utils.cpp
- cpp/dolfinx/refinement/utils.cpp
- python/dolfinx/wrappers/fem.cpp
- python/dolfinx/wrappers/io.cpp
- python/dolfinx/wrappers/mesh.cpp
xtensor/icpx issues:
- Assign to a view (using `operator=()`)
- Return an `xt::adapt` instead of an `xtensor<T, 2>`.
- `operator[]` has unpredictable behavior for 2d/3d tensors.
I'm working in a new PR for `icpc`.
> Fixes for the new Intel Compiler

- .github/workflows/ccpp.yml
- .github/workflows/docker-end-user.yml
Can be used to control matching branches for end-user docker images on release tag creation.
> Make checkout refs explicit

- cpp/dolfinx/fem/CoordinateElement.cpp
Former approach calls `basix::topology` which needs dynamic memory alloc. Topological dimension of coordinate element is easily used in hot loops.
> Faster way of fetching tdim

- docker/Dockerfile
This provides updated MPI libraries, in which some bugs have been fixed.
> Bump Ubuntu base image to 21.04

- docker/Dockerfile
LLVM-10 doesn't seem to exist in 21.04, see: https://packages.ubuntu.com/hirsute/devel/
> Try LLVM-9

- cpp/CMakeLists.txt
- cpp/cmake/scripts/generate-cmakefiles.py
- cpp/test/unit/CMakeLists.txt
- python/CMakeLists.txt
Earlier versions can cause problems with 'modern' configuration of dependencies.
> Bump min CMake version to 3.16. Earlier versions are not tested.

- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/Topology.h
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/fem/test_element_integrals.py
- python/test/unit/fem/test_fem_pipeline.py
- python/test/unit/function/test_interpolation.py
- python/test/unit/geometry/test_bounding_box_tree.py
- python/test/unit/io/test_xdmf_meshtags.py
- python/test/unit/mesh/test_cell.py
- python/test/unit/mesh/test_custom_partitioners.py
- python/test/unit/mesh/test_mesh.py
- python/test/unit/mesh/test_meshtags.py
Removes the lazy `compute_connectivity_all()`, which is usually mis-used and is expensive (in time and memory)
> Remove topology functions that shouldn't be used

- cpp/CMakeLists.txt
- cpp/cmake/templates/DOLFINXConfig.cmake.in
- python/CMakeLists.txt
This support detection of the Basix C++ libraries when installed together with the Basix Python interface.
> Support detection of Basix library in Python tree

- cpp/dolfinx/mesh/Topology.cpp
* Shorten `mesh::create_topology` by spinning out various stages to anonymous namespace functions
* Remove some dead code
* Remove "remap" by numbering cellwise in the first place
* Remove call to `IndexMap::compute_shared_indices` and use `scatter_fwd_indices` instead.
> Refactor create topology

- python/test/unit/fem/test_symmetry.py
Make meshes in symmetry tests smaller and turn them off in parallel, reduced the maximum order that is tested
> Faster symmetry tests

- python/demo/pyvista/demo_pyvista.py
- python/dolfinx/plot.py
Point/Cell_arrays deprecated: https://github.com/pyvista/pyvista/blob/b562517e5046513876059f4f902809b3debc14aa/pyvista/core/dataset.py#L1192-L1193
Basix DG/DQ dof ordering same as Lagrange (https://github.com/FEniCS/dolfinx/pull/1670), simplifies vtk topology creation, and caused the visualization pipeline to fail.
> Pyvista updates

- cpp/dolfinx/fem/CoordinateElement.cpp
Improvements of about 15% for the following code:
```python
import dolfinx
mesh = dolfinx.UnitCubeMesh(MPI.COMM_WORLD, 20, 20, 20)
V = dolfinx.FunctionSpace(mesh, ("N1curl", 2))
u = dolfinx.Function(V)
with dolfinx.common.Timer("interpolate"):
u.interpolate(lambda x: x)
dolfinx.list_timings(MPI.COMM_WORLD, [dolfinx.TimingType.wall])
```
GCC 10.3.0
CXX Flags = "-Ofast -march=native"
and `-DXTENSOR_OPTIMIZE=1` in basix
```
this - interpolate                                                     |     1  0.856936  0.856936
main - interpolate                                                     |     1  1.029000  1.029000
```
> Remove calls to xt::broadcast in interpolation

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/graph/partition.cpp
- cpp/dolfinx/io/HDF5Interface.h
- cpp/dolfinx/io/XDMFFile.cpp
- cpp/dolfinx/la/PETScMatrix.cpp
- cpp/dolfinx/la/PETScMatrix.h
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/refinement/utils.cpp
Running Release mode with -Werror -Wall -pedantic shows quite a few possible unused variables, as they are only used in asserts. This commit fixes it.
> Add [[maybe_unused]] to variables unused in "Release" mode.

- cpp/dolfinx/io/HDF5Interface.h
Function that implicitly finds the size of input data. If only called in assert, this returns data of (0,0).
Fixes #1785  introduced in #1784
> Fixes #1785

- python/dolfinx/wrappers/geometry.cpp
Having these in the wrong order gave the function confusing pybind documentation
> Correct order of args in pybind

- python/CMakeLists.txt
This now matches the one used in installed checks in
[python/setup.py](https://github.com/FEniCS/dolfinx/blob/main/python/setup.py#L45)
Without this change cmake would fail for me to find petsc4py when I have a Python installation in /usr/local/
> Use interpreter variable passed to cmake to find python modules

- cpp/dolfinx/io/HDF5Interface.cpp
This will pick up any versioning issues with the `H5Oget_info_by_name` wrapper.
> Call H5Oget_info_by_nameX directly for HDF5

- python/dolfinx/jit.py
When running systemd service it's customary run it as a system user without home directory. In such a setup default JIT cache directory (`~/.cache/fenics`) cannot be created and user configuration file (`~/.config/dolfinx/dolfinx_jit_parameters.json`) cannot be set. This PR adds ability to override user configuration file location by `DOLFINX_JIT_PARAMETERS_FILE` environment variable.
> Get dolfinx_jit_parameters.json location from envvar

- cpp/dolfinx/io/utils.cpp
* Ensure that the filename string does not contain any `\0` characters by going through `.c_str()` from boost
> Remedy errant boost behaviour

- cpp/dolfinx/graph/partitioners.cpp
```
[28/65] Building CXX object dolfinx/CMakeFiles/dolfinx.dir/graph/partitioners.cpp.o
FAILED: dolfinx/CMakeFiles/dolfinx.dir/graph/partitioners.cpp.o
/usr/bin/c++ -DADIOS2_USE_MPI -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_TIMER_DYN_LINK -DDEBUG -DDOLFINX_VERSION=\"0.3.1.0\" -DHAS_ADIOS2 -DHAS_KAHIP -DHAS_PTSCOTCH -Ddolfinx_EXPORTS -I/root/shared/dolfinx/cpp -I/root/shared/dolfinx/cpp/dolfinx -isystem /root/shared/ffcx/ffcx/codegeneration -isystem /usr/local/petsc/linux-gnu-real-32/include -isystem /usr/local/petsc/include -Ofast -march=native -Wall -Werror -pedantic -g -fPIC -std=c++17 -MD -MT dolfinx/CMakeFiles/dolfinx.dir/graph/partitioners.cpp.o -MF dolfinx/CMakeFiles/dolfinx.dir/graph/partitioners.cpp.o.d -o …
```
> Fix parhip build error

- cpp/dolfinx/fem/DirichletBC.h
- cpp/dolfinx/fem/assemble_matrix_impl.h
- cpp/dolfinx/fem/assemble_vector_impl.h
- cpp/dolfinx/fem/assembler.h
- cpp/dolfinx/graph/partition.cpp
- cpp/dolfinx/mesh/graphbuild.cpp
- python/dolfinx/wrappers/fem.cpp
The allows interaction with Python/NumPy and xtensor without copies, and testing in a different context indicated that `std::vector<int8_t>` is faster than `std::vector<bool>`.
> Use std::int8_t in place of bool for bc vectors

- cpp/dolfinx/refinement/utils.cpp
- python/dolfinx/mesh.py
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/mesh/test_refinement.py
Fixing bug in Python interface reported at: https://fenicsproject.discourse.group/t/what-is-the-latest-api-for-mesh-refinement-in-dolfinx/7201
Fixing bug in C++ refinement when number of new vertices on a process is 0.
Add tests for refinement using list of edges.
Reactivate gdim refinement test
Expose `compute_incident_entities` to use with refinement
> Fix refinement and add tests for sub refinement

- cpp/dolfinx/common/IndexMap.cpp
- python/test/unit/common/test_index_map.py
[This](https://github.com/FEniCS/dolfinx/blob/main/cpp/dolfinx/common/IndexMap.cpp#L271) `IndexMap` constructor does not initialise `_displs_recv_fwd` correctly, which can cause a segmentation fault in `IndexMap::scatter_fwd_begin` due to [this](https://github.com/FEniCS/dolfinx/blob/main/cpp/dolfinx/common/IndexMap.h#L250) check being missed.
This PR fixes the issue and adds a test that fails without the fix. A more direct test might be better, but `IndexMap::scatter_fwd_begin` isn't currently exposed to Python.
Debugged with help from @jorgensd.
> Fix for `IndexMap` segmentation fault

- python/doc/source/api.rst
The link from the Python docs to the C++ docs is broken. Making this match the URL in the main README.
> Update link to C++ docs

- cpp/dolfinx/geometry/gjk.cpp
Use known size in loop as reported by Sonarcloud
> Fix GJK loop access

- cpp/dolfinx/common/MPI.h
- Add std::int8_t to supported types
> Issue compile time error if data type is not supported (MPI)

- cpp/dolfinx/la/Vector.h
Change return type from `T` to `double`.
> Fix return type for `la::Vector::norm`

- cpp/dolfinx/fem/DirichletBC.h
- cpp/dolfinx/fem/FiniteElement.cpp
- cpp/dolfinx/fem/FiniteElement.h
- cpp/dolfinx/io/ADIOS2Writers.cpp
- cpp/dolfinx/io/VTKFile.cpp
- cpp/dolfinx/io/xdmf_function.cpp
- cpp/dolfinx/io/xdmf_utils.cpp
- python/demo/mixed-elasticity-sc/static-condensation-elasticity.py
- python/dolfinx/fem/function.py
- python/dolfinx/wrappers/fem.cpp
- python/test/unit/fem/test_bcs.py
- python/test/unit/fem/test_function_space.py
- python/test/unit/io/test_vtk.py
Also removes `FiniteElement::value_rank` since this is just `value_shape.size()`.
> Replace confusing legacy `FiniteElement::value_dimension` with `FiniteElement::value_shape` 

- cpp/dolfinx/fem/dofmapbuilder.cpp
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/Topology.h
- cpp/dolfinx/refinement/plaza.cpp
- cpp/dolfinx/refinement/utils.cpp
- cpp/dolfinx/refinement/utils.h
`vector<bool>` is a possibly space-efficient specialization of `vector<T>` .
In exchange for this optimization, it doesn't offer all the capabilities and interface of a normal standard container(it doen't have `vector<T>::data` or  `vector<T>::iterator` members).
https://en.cppreference.com/w/cpp/container/vector_bool
This can be confusing and inhibits the use of some stl functions, and IndexMap scatter functions.
> Convert std::vector<bool> to std::vector<int8_t>

- cpp/dolfinx/fem/assemble_matrix_impl.h
- cpp/dolfinx/fem/assemble_scalar_impl.h
- cpp/dolfinx/fem/assemble_vector_impl.h
- cpp/dolfinx/fem/petsc.cpp
- cpp/dolfinx/geometry/BoundingBoxTree.cpp
- python/test/unit/fem/test_assemble_cppimport.py
Removes unused arg and fixes formatting issues picked up by CI.
> Remove unused function arguments in bc lifting implementation

- cpp/dolfinx/fem/DirichletBC.cpp
- cpp/dolfinx/la/petsc.h
These cause compilation to fail when using pedantic flag options
> Remove unnecessay semicolons

- cpp/dolfinx/fem/Function.h
The pull back affine function in `dolfinx::fem::Function::eval` called `cmap.tabulate` for every point, even if it could be tabulated only once.
This causes a huge regression when eval is called on large sets of points, (for instance in `compute_point_values` used for `XDMFFile.write_function`).
MWE:
```python
import dolfinx
import dolfinx.io
import dolfinx.fem
import dolfinx.mesh
N = 100
mesh = dolfinx.mesh.create_unit_cube(MPI.COMM_WORLD, N, N, N)
V = dolfinx.fem.FunctionSpace(mesh, ("CG", 1))
uh = dolfinx.fem.Function(V)
uh.x.array[:] = 1
for i in range(10):
with dolfinx.common.Timer("~FEM: Compute at nodes"):
uh.compute_point_values()
t = dolfinx.common.timing("~FEM: Compute at nodes")
print(f"Point values: {t[0]} {t[1]} {t[1]/t[0]}")
```
**main**
```bash
Point …
```
> Fix regression in eval

- cpp/dolfinx/common/IndexMap.cpp
Workaround to issue https://github.com/pmodels/mpich/issues/5764 .
`MPI_Comm_dup` fails for unweighted graph communicators.
The issue has been fixed in https://github.com/pmodels/mpich/pull/5629 and it's available in mpich 4.0rc3( a release candidate).
> Add uniform weights to MPI neighbor communicator

- cpp/dolfinx/common/TimeLogger.cpp
- cpp/dolfinx/common/TimeLogger.h
- cpp/dolfinx/common/timing.cpp
- cpp/dolfinx/common/timing.h
- python/dolfinx/common.py
- python/dolfinx/wrappers/common.cpp
Currently, `list_timings()` produces the average time of a `Timer` across all MPI ranks. This is misleading, and the maximum (or minimum) are more useful.
This PR makes it possible to easily select, and makes max the default.
> Make timing MPI reduction easily selectable, and MPI_MAX by default

- cpp/dolfinx/la/Vector.h
Provides a function to return the allocator associated with the internal data container.
> Add function to get Vector allocator

- cpp/dolfinx/geometry/BoundingBoxTree.cpp
- cpp/dolfinx/geometry/utils.cpp
- cpp/dolfinx/graph/AdjacencyList.h
- cpp/dolfinx/graph/partition.h
- cpp/dolfinx/io/ADIOS2Writers.cpp
- cpp/dolfinx/la/SLEPcEigenSolver.cpp
- cpp/dolfinx/la/petsc.cpp
- cpp/dolfinx/mesh/Geometry.cpp
- cpp/dolfinx/mesh/Geometry.h
- cpp/dolfinx/mesh/Mesh.cpp
- cpp/dolfinx/mesh/Mesh.h
- cpp/dolfinx/mesh/MeshTags.h
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/Topology.h
- cpp/dolfinx/mesh/cell_types.h
- cpp/dolfinx/mesh/generation.cpp
- cpp/dolfinx/mesh/generation.h
- cpp/dolfinx/mesh/graphbuild.cpp
- cpp/dolfinx/mesh/permutationcomputation.cpp
- cpp/dolfinx/mesh/topologycomputation.cpp
- cpp/dolfinx/mesh/utils.cpp
- cpp/dolfinx/mesh/utils.h
- cpp/dolfinx/refinement/plaza.cpp
- cpp/test/unit/io.cpp
- cpp/test/unit/mesh/distributed_mesh.cpp
Also removes some xtensor views and introduces some memory scoping in the mesh construction to reduce peak memory usage.
> Fix questionable `std::move` in mesh construction

- python/dolfinx/wrappers/io.cpp
Use `std::filesystem::path` in place of `std::string` for filenames in pybind11 interface layer.
> Use std::filesystem in pybind11 layer

- python/dolfinx/__init__.py
This avoid the need to explicitly import all second level submodules. Users are encouraged to do one of
1. Verbose,
```python
import dolfinx
mesh = dolfinx.mesh.create_unit_square(...)
```
2. Less verbose,
```python
from dolfinx import mesh
my_mesh = mesh.create_unit_square(...)
```
3. Least verbose, but plenty imports.
```python
from dolfinx.mesh import create_unit_square
mesh = create_unit_square(...)
```
> Import second level submodules automatically

- python/dolfinx/plot.py
- python/dolfinx/wrappers/io.cpp
Reuse some functionality from #1990 to properly plot higher order meshes with Pyvista.
Plotting of sub entities (edges, facets) are linearised based on the topology.
> Extend pyvista plotting to higher order meshes.

- cpp/dolfinx/fem/assemble_vector_impl.h
Certain mixed formulations evaluate interior facet integrals with different function spaces being involved.
This PR fixes the offset used to access the element vector `be` such that out-of-bounds array access is avoided in the above scenario.
> Correct offset to avoid out-of-bounds array access

- cpp/demo/hyperelasticity/main.cpp
- cpp/demo/interpolation-io/main.cpp
- cpp/demo/poisson/main.cpp
- cpp/dolfinx/nls/NewtonSolver.cpp
- cpp/dolfinx/nls/NewtonSolver.h
- python/dolfinx/nls.py
- python/dolfinx/wrappers/nls.cpp
- python/test/unit/nls/test_newton.py
This is the last(?) C++ class/function that depends directly on PETSc and isn't sequestered inside a `petsc::` namespace. This helps maintain clear interface between DOLFINx and PETSc.
The Newton solver design, including how to possibly abstract away the backend, needs to be reviewed in the future. It's questionable why we have a Newton solver that depends in PETSc when we could just use PETSc SNES.
> Sandbox PETSc-dependent NewtonSolver class in `nls::petsc` namespace

- cpp/dolfinx/fem/FiniteElement.cpp
- cpp/dolfinx/fem/petsc.cpp
- cpp/dolfinx/fem/utils.cpp
Current implementation of `V = create_functionspace(basix_element, bs)` does  not allow for usage of sub spaces, i.e.
`V.sub(i)`. This PR adds the appropriate functionality to create sub spaces of such function-spaces.
> Fix sub element creation of function space based on basix element

- cpp/dolfinx/io/XDMFFile.cpp
- cpp/dolfinx/io/xdmf_utils.cpp
- cpp/dolfinx/io/xdmf_utils.h
- python/demo/gmsh/demo_gmsh.py
- python/dolfinx/wrappers/io.cpp
Introduce some scoping in `xdmf_utils::distribute_entity_data` to reduce peak memory usage.
Also:
- Remove some xtensor in favour of `std::vector`
- Fix bug in gmsh demo
> Reduce peak memory use when distributing data in parallel

- cpp/dolfinx/common/MPI.cpp
- cpp/dolfinx/common/MPI.h
- cpp/dolfinx/fem/DofMap.cpp
- cpp/dolfinx/fem/dofmapbuilder.cpp
- cpp/dolfinx/graph/partition.cpp
- cpp/dolfinx/io/xdmf_function.cpp
- cpp/dolfinx/io/xdmf_mesh.cpp
- cpp/dolfinx/io/xdmf_meshtags.h
- cpp/dolfinx/la/SparsityPattern.cpp
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/graphbuild.cpp
- cpp/dolfinx/mesh/topologycomputation.cpp
- cpp/dolfinx/refinement/utils.cpp
- cpp/test/unit/common/index_map.cpp
- cpp/test/unit/vector.cpp
Implements the algorithm in https://dx.doi.org/10.1145/1837853.1693476 for dynamic computation of a sparse neighbourhood. Replaces non-scalable discovery that uses all-to-all.
There are more places where this, or similar, algorithm should be used.
See #60.
Also fixes a bug in the computation of cell ghost/halo layers.
> Add scalable sparse neighbourhood discovery

- cpp/dolfinx/mesh/topologycomputation.cpp
- python/test/unit/mesh/test_mesh.py
This PR fixes a bug in topology creation affecting processes with no cells. The bug causes, for example, the facet-vertex connectivity to have one node when it should have zero. This PR also adds a test that fails in parallel on main.
> Fix bug in topology creation

- python/dolfinx/fem/function.py
We should not use `-` in function names, as it will cause ffcx to fail compiling as it is interpreted as the `minus` operator
MWE.
```python
from dolfinx import mesh as msh, fem
import ufl
mesh = msh.create_unit_square(MPI.COMM_WORLD, 10, 10)
el = ufl.VectorElement("Lagrange", mesh.ufl_cell(), 1, dim=2)
V = fem.FunctionSpace(mesh, el)
u = fem.Function(V)
ux, uy = u.split()
fem.form(ux*ufl.dx)
```
> Fix sub component name

- python/dolfinx/fem/function.py
- python/test/unit/fem/test_function.py
> Avoid using count/id to name `fem.Functions` in Python

- python/dolfinx/fem/function.py
- python/test/unit/io/test_xdmf_function.py
Should fix #2074 and #2061 . UFL id generated with unique global generator in UFL should not be overwritten with
dolfinx's Function id. Equality of UFL objects is different to equality of dolfinx cpp objects.
This will make UFL form in #2074 deterministic again (python `id()` is not) and file IO should work as well, as Function names contain the deterministic UFL id.
> Do not overwrite UFL id in Function

- cpp/dolfinx/mesh/Topology.cpp
- python/test/unit/mesh/test_mesh.py
This PR allows empty permutation vectors to be returned on ranks with no cells or facets, and adds a test which fails on main.
> Return empty permutations on ranks with no cells or facets

- cpp/dolfinx/fem/Form.h
- python/dolfinx/fem/assemble.py
- python/test/unit/fem/test_assemble_submesh.py
This PR fixes a bug where some exterior facets are not detected in `set_default_domains` when one process owns all the cells in a submesh but other processes ghost some of those cells.  It also adds a test that fails on main.
> Fix for exterior facet integrals on a submesh

- cpp/dolfinx/graph/partition.cpp
- cpp/dolfinx/refinement/utils.h
- python/demo/interpolation-io/demo_interpolation-io.py
- python/dolfinx/io.py
- python/dolfinx/wrappers/io.cpp
- python/test/unit/io/test_adios2.py
Reduces the pybind11 wrapper code.
Raise an import error rather than a runtime error where appropriate.
> Move file `__enter__`/`__exit__` to the Python layer

- cpp/dolfinx/common/MPI.h
- cpp/dolfinx/common/utils.h
- cpp/dolfinx/graph/partition.cpp
- cpp/dolfinx/mesh/Mesh.cpp
- cpp/dolfinx/mesh/Topology.cpp
Ensures that mesh distribution and ownership determination is deterministic for a given number of MPI ranks. The issue is the new functions in #2050 are not deterministic in terms of the ordering of the returned ranks. This is a natural consequence of the MPI nonblocking sends. This PR make mesh creation deterministic by sorted the array of ranks in two specific places.
Also fixes hash functions.
> Make mesh distribution deterministic for a given number of ranks

- python/doc/README.md
- python/doc/README.rst
- python/doc/source/conf.py
- python/doc/source/jupytext_process.py
Required after change in MyST defaults: https://myst-parser.readthedocs.io/en/latest/develop/_changelog.html#dollarmath-is-now-disabled-by-default.
Fixes #2098.
> Add MyST option to enable 'dollarmath'

- .gitignore
Since usage of VTX/Fides is quite common now, we should ignore the corresponding output files.
> Add adios2 files (.bp) and pngs to gitignore

- cpp/dolfinx/fem/discreteoperators.h
- python/dolfinx/wrappers/fem.cpp
Ignoring zeros improves both assembly and matrix-vector product time.
```python3
import ufl
from dolfinx.cpp.fem.petsc import interpolation_matrix
from dolfinx.fem import FunctionSpace
from dolfinx.mesh import create_unit_cube
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import norm
comm = MPI.COMM_WORLD
mesh = create_unit_cube(comm, 20, 20, 20)
e0 = ufl.FiniteElement("Lagrange", mesh.ufl_cell(), 5)
e1 = ufl.FiniteElement("Lagrange", mesh.ufl_cell(), 1)
V = FunctionSpace(mesh, e0)
W = FunctionSpace(mesh, e1)
begin = MPI.Wtime()
for i in range(10):
G = interpolation_matrix(V._cpp_object, W._cpp_object)
G.assemble()
end = MPI.Wtime()
if (comm.rank == 0):
print("Assemble: \t", end - begin)
x, y = G.getVecs()
begin = MPI.Wtime()
for i in range(10): …
```
> Ignore zero entries - interpolation matrix

- cpp/dolfinx/common/math.h
- cpp/dolfinx/fem/CoordinateElement.cpp
Fix #2109.
Make behaviour of math::pinv consistent for all admissible matrix shapes and consistent with math::inv.
The behaviour of math::pinv is currently different depending on the shape of the input matrix:
3x1, 2x1: B_pinv = pinv(B)
3x2: B_pinv +=pinv(B)
> Fill output matrix with 0.0 in math::pinv

- cpp/dolfinx/fem/Form.h
- cpp/dolfinx/mesh/Topology.cpp
- python/test/unit/mesh/test_mesh.py
This PR fixes a bug in `compute_boundary_facets` for `GhostMode.none` meshes, where some facets would be incorrectly identified as boundary facets. It also addresses the same issue  as  https://github.com/FEniCS/dolfinx/pull/2120, and removes some duplicate code.
@jorgensd perhaps we could add a more general version of the test in https://github.com/FEniCS/dolfinx/pull/2120 to make sure this isn't accidentally broken again?
> Fix `compute_boundary_facets` for `GhostMode.none`

- cpp/dolfinx/fem/DirichletBC.h
- python/test/unit/fem/test_assembler.py
- python/test/unit/fem/test_bcs.py
As I see no way of easily fixing #2022, this PR adds a runtime error to make sure that people do not use the function when it is not working as intended. 
Fixes #2022.
> Throw runtime error for blocked mixed Dirichlet BC with Constant

- cpp/dolfinx/geometry/utils.cpp
Also remove some expensive xtensor computations, and avoid allocating intermediate arrays.
```python
import dolfinx.mesh
import ufl
from dolfinx import geometry
from dolfinx import common
from dolfinx import fem
comm = MPI.COMM_WORLD
mesh = dolfinx.mesh.create_unit_cube(comm, 50, 50, 50)
el = ufl.FiniteElement("Lagrange", mesh.ufl_cell(), 2)
V = fem.FunctionSpace(mesh, el)
x = V.tabulate_dof_coordinates()
tree = geometry.BoundingBoxTree(mesh, mesh.geometry.dim)
with common.Timer("compute_collisions") as t:
cell_candidates = geometry.compute_collisions(tree, x)
common.list_timings(comm, [common.TimingType.wall])
```
This branch:
``` 
compute_collisions                                                          |     1  1.582766  1.582766
```
main:
``` …
```
> Add non-recursive collision algorithm

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/common/IndexMap.h
- cpp/dolfinx/fem/DofMap.cpp
- cpp/dolfinx/la/MatrixCSR.h
- cpp/dolfinx/la/SparsityPattern.cpp
- cpp/dolfinx/refinement/utils.cpp
- python/dolfinx/common.py
- python/dolfinx/wrappers/common.cpp
- python/test/unit/common/test_index_map.py
- python/test/unit/la/test_vector_scatter.py
`IndexMap` previously return the global owning rank, and callers reverse-engineered this back to the neighbourhood rank. This change returns the rank on the neighbourhood communicator, which can we easily converted to the global rank, if needed.
> Return neighbourhood ranks with ghost owners from `IndexMap`

- python/dolfinx/fem/petsc.py
This fixes a potentially dangerous implicit behaviour, where None in list of forms for assemble_matrix_block ignores all DirichletBC applied there. Typical case: pin pressure in the Stokes problem.
> Raise on DirichletBC for None block

- cpp/dolfinx/CMakeLists.txt
- cpp/dolfinx/common/CMakeLists.txt
Configure `version.h.in` via CMake in the build directory rather than source directory. This preserves a clean separation between source and build code.
> Do not modify version header file source code in-place

- docker/Dockerfile
Update Gmsh, PETSc, SLEPc, HDF5 , xtensor snd MPICH versions.
> Bump Docker base to Ubuntu 22.04 and other package updates

- .github/workflows/spack.yml
Allow Spack repository and branch to be specified when manually triggering CI
> Spack CI updates and improvements

- docker/Dockerfile
With the release of Ubuntu 22.04, which defaults to Python 3.10, there are no official VTK release.
Adding workaround: https://github.com/pyvista/pyvista/discussions/2064
> Add unofficial vtk wheel for usage with pyvista to lab image

- docker/Dockerfile
- docker/complex-kernel.json
As the docker images uses python 3.10, the corresponding folders in the docker images should be renamed.
> Rename folder for dolfinx python installation in docker images.

- cpp/dolfinx/io/vtk_utils.cpp
Affects plotting of second order hexes with `VTKFile` and `VTXWriter`.
With the removal of this if test shows the correct figure in Paraview >=5.10
> Fix VTKFile and VTXWriter for Paraview's (>=5.10.0) plotting of second order hexahedra

- cpp/test/matrix.cpp
test compilation fails with `-Werror=pedantic`
> cpp/test: remove extra semicolon

- python/dolfinx/fem/__init__.py
- python/dolfinx/io.py
- python/dolfinx/nls/__init__.py
- python/test/unit/common/test_python_implemented.py
It appears that F822 won't be checked in `__init__.py`, see [here](https://github.com/PyCQA/pyflakes/issues/661). Here we check that the members specified in `__all__` in each module are implemented.
> Compensate for flake8 F822 to check members of `__all__` are implemented

- python/setup.py
Add cffi to setup.py (as suggested by @minrk), required to make sure we have `libffi` (https://fenicsproject.discourse.group/t/installation-fenicsx-with-conda-on-macos/8492/5)
> Add CFFI to setup.py

- cpp/dolfinx/refinement/utils.cpp
- cpp/dolfinx/refinement/utils.h
- Add asserts to make it possible to find missing connectivities in DEBUG mode.
- Move mesh to avoid it being copied in `MeshTags` constructor.
The last point would cause issues when refining the mesh, then refining the tag and trying to write it to file.
You cannot create the required connectivities on the refined mesh, but currently have to access the copy through the meshtag.
> Minor improvements to `transfer_cell/facet_meshtags`

- cpp/dolfinx/fem/Form.h
- cpp/dolfinx/fem/assemble_matrix_impl.h
- cpp/dolfinx/fem/assemble_scalar_impl.h
- cpp/dolfinx/fem/assemble_vector_impl.h
- cpp/dolfinx/fem/utils.h
- python/dolfinx/wrappers/fem.cpp
The current usage of `std::vector<std::int32_t>`, `std::vector<std::pair<std::int32_t, int>>`, `std::vector<std::tuple<std::int32_t, int,std::int32_t, int>` is overly complicated, when we always know the second dimension of the array when accessed.
Additionally, the second int (referring to the local entity index for a facet) can be an `std::int32_t` without adding any new assumptions to the code.
This pull request flattens the C++ layout of all these entities to `std::vector<std::int32_t>`.
The Python interface still reshapes the data to be 1,2 or 3 dimensional.
This change also makes it easier to pass integral entities down to C++ for exterior libraries, as all the entities in DOLFINx has the same type.
> Flatten integral domains in C++

- .github/workflows/ccpp.yml
- docker/Dockerfile
Docs are failing to build with sphinx 5.0.1. Build works again with 5.0.2.
This line can be removed once the docker image has Sphinx >= 5.0.2 isntalled
> Upgrade sphinx during CI run

- cpp/dolfinx/fem/sparsitybuild.cpp
- cpp/dolfinx/fem/sparsitybuild.h
- cpp/dolfinx/fem/utils.cpp
- cpp/dolfinx/fem/utils.h
This PR makes it possible to build a sparsity pattern from a list of integration entities i.e. cell indices for cell integrals, (cell, local_facet) pairs for exterior facet integrals etc. It also modifies `create_sparsity_pattern` so that it only adds entries for entities in the form's integration domains, rather than for all entities of a particular integration type.
This PR is a step towards allowing the user to specify integration domains by passing a list of integration entities to `Form`, which would allow, for example, one-sided integrals on the interior facets of the mesh. I plan to put in another PR soon to add this functionality.
> Allow sparsity pattern to be built from integration entities

- cpp/dolfinx/common/MPI.h
- cpp/dolfinx/common/sort.h
- cpp/dolfinx/fem/utils.h
- cpp/dolfinx/io/ADIOS2Writers.cpp
- cpp/dolfinx/io/VTKFile.cpp
- cpp/dolfinx/io/xdmf_function.cpp
See:
https://en.cppreference.com/w/cpp/types/is_same
https://en.cppreference.com/w/cpp/types/is_integral
https://en.cppreference.com/w/cpp/types/is_scalar
> Use helper template (from C++ 17 and onwards) for std::is_same<T>::value and std::is_integral<T>::value

- python/dolfinx/wrappers/common.cpp
- python/dolfinx/wrappers/fem.cpp
- python/dolfinx/wrappers/geometry.cpp
- python/dolfinx/wrappers/graph.cpp
- python/dolfinx/wrappers/io.cpp
- python/dolfinx/wrappers/la.cpp
- python/dolfinx/wrappers/log.cpp
- python/dolfinx/wrappers/mesh.cpp
- python/dolfinx/wrappers/nls.cpp
- python/dolfinx/wrappers/refinement.cpp
> Add missing function parameter names of pybind11 generated functions

- .github/workflows/pyvista.yml
- docker/Dockerfile
As https://github.com/pyvista/pyvista/issues/2859 has been closed with  https://github.com/pyvista/pyvista/pull/2912 and vtk has added a python3.10 compatible pypi wheel (https://pypi.org/project/vtk/9.2.0rc1/) the docker file has been simplified
> Bump pyvista version

- cpp/dolfinx/io/cells.cpp
- cpp/dolfinx/io/xdmf_meshtags.h
- python/demo/demo_gmsh.py
- python/dolfinx/io/gmshio.py
- python/dolfinx/mesh.py
- python/test/unit/mesh/test_higher_order_mesh.py
Add error handling for missing entity index map in outputting.
Add convenience functions reading meshes from gmsh models or directly from msh files.
The GMSH models are read in from file on a single process, to be distributed with the MPI communicator of the user's choice.
When read from the gmsh python interface, it is assumed that the gmsh model is generated on a single rank (or on every rank using comm self), and can then be distributed by supplying an appropriate communicator to `gmshio.model_to_mesh`.
This would greatly simplify more complex demos, such as #2237, as we do not need lengthy conversion/mpi-broadcast scripts to be repeated in every demo.
As in #2131, these convenience functions are only exposed to the user if the have the GMSH python bindings installed.
> Rewrite GMSH interface

- .github/workflows/ccpp.yml
- cpp/doc/source/graph.rst
`dolfinx::graph::create_adjacency_data` has been deprecated and is replaced by `dolfinx::graph::regular_adjacency_list` in the C++ demos
> Remove non-existent function from C++ docs

- cpp/dolfinx/fem/CoordinateElement.h
Currently we have an implicit assumption that the working memory contains zeros.
This PR zeros out the bit of the working memory used in the BA dot product.
> Zero work array in `fem::CoordinateElement::compute_jacobian_determinant`

- .github/workflows/ccpp.yml
- python/dolfinx/fem/function.py
The Basix CI runs mypy checks on dolfinx (to check that Basix changes don't break typing in dolfinx), so mypy errors in dolfinx cause failures (eg https://github.com/FEniCS/basix/runs/7538096916?check_suite_focus=true).
> Make mypy blocking and fix error

- docker/Dockerfile
To be able to use `meshio` for conversion of mesh files to `xdmf`, `h5py` requires that `hdf5` is built with `zlib`.
> Enable zlib for hdf5 in docker images

- python/setup.py
allows customization of the build. Required for cross-compilation [in conda packages](https://github.com/conda-forge/fenics-dolfinx-feedstock/blob/main/recipe/cmake-args-python.patch).
Also now respects $CMAKE_BUILD_PARALLEL_LEVEL (needed in conda-forge because ppc builds failed with out-of-memory during parallel builds)
> init cmake_args with $CMAKE_ARGS in Python build

- cpp/dolfinx/common/MPI.cpp
- cpp/dolfinx/common/MPI.h
> move algorithm header from MPI.cpp to MPI.h

- python/dolfinx/fem/function.py
Mimics what is already there for `dolfinx.fem.VectorFunctionSpace`, just a few lines above.
Got this while running `mypy` on one of my projects, not sure why `dolfinx` CI did not complain, as such case is used in the tests (e.g., `python/test/unit/io/test_vtk.py`)
> Add the case of a pair (str, int) to dolfinx.fem.TensorFunctionSpace type hints, second argument

- cpp/dolfinx/fem/CoordinateElement.h
In `compute_jacobian_inverse`, `gdim` and `tdim` are inconsistent with documentation for shape of `J` and `K`.
This fixes the inconsistency. Behaviour of code is unchanged.
> Fix minor inconsistency in `compute_jacobian_inverse`

- python/dolfinx/mesh.py
Hi,
I believe this was introduced yesterday in #2337.
pybind11 wrappers for `dolfinx.mesh.create_mesh_partitioner` with no input arguments have been removed,
compare
https://github.com/FEniCS/dolfinx/blame/main/python/dolfinx/wrappers/mesh.cpp#L369
to
https://github.com/FEniCS/dolfinx/blame/4a5d20a9577b73052667644611fc014cd17257c1/python/dolfinx/wrappers/mesh.cpp#L380
which on main, at least for my local installation, makes a simple code such as
```
import dolfinx.mesh
import mpi4py.MPI
dolfinx.mesh.create_interval(mpi4py.MPI.COMM_WORLD, 30, [1, 5])
```
fail with
```
Traceback (most recent call last):
File "test.py", line 3, in <module>
dolfinx.mesh.create_interval(mpi4py.MPI.COMM_WORLD, 30, [1, 5])
File "dolfinx/mesh.py", line 324, in create_interval
partitioner = …
```
> Fix regression introduced in #2337 for dolfinx.mesh.create_interval

- python/dolfinx/mesh.py
- python/test/unit/mesh/test_mesh.py
> Add test including create_interval()

- cpp/dolfinx/fem/FiniteElement.cpp
- python/test/unit/fem/test_interpolation.py
Adjusted how permutations inside mixed elements are handled, so that the dofmap for `MixedElement(Nedelec, Lagrange)` is created correctly.
Fixes #2343.
> Fix permuting of Lagrange spaces inside mixed elements

- cpp/dolfinx/mesh/Mesh.cpp
This PR fixes a bug where not all vertices in the submesh are added to the submesh vertex map on some processes. It arises because `entities` may or may not contain ghosts, but the submesh entity map will always contain ghost entities present in the submesh.
> Fix bug where not all required vertices are added to submesh vertex map

- python/dolfinx/io/__init__.py
This pull request 
- adds `from dolfinx.io import gmshio` in `python/dolfinx/io/__init__.py` so that `gmshio` is considered a module, making calls like the one below possible:
https://github.com/FEniCS/dolfinx/blob/ce832ec12bc6dbfff9e9f94eb06356e84e739f7f/python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py#L244
- removes an unnecessary `gmshio` string in the `has_adios2` conditional block.
> Add `from dolfinx.io import gmshio` in `io/__init__.py`

- .github/workflows/macos.yml
- cpp/CMakeLists.txt
- cpp/cmake/templates/DOLFINXConfig.cmake.in
- cpp/demo/hyperelasticity/main.cpp
- cpp/demo/interpolation-io/main.cpp
- cpp/demo/poisson/main.cpp
- cpp/demo/poisson_matrix_free/main.cpp
- cpp/dolfinx/CMakeLists.txt
- cpp/dolfinx/fem/DirichletBC.cpp
- cpp/dolfinx/fem/DirichletBC.h
- cpp/dolfinx/fem/Expression.h
- cpp/dolfinx/fem/Function.h
- cpp/dolfinx/mesh/utils.cpp
- cpp/dolfinx/mesh/utils.h
- cpp/test/matrix.cpp
- docker/Dockerfile
- docker/Dockerfile.redhat
- python/CMakeLists.txt
- python/doc/source/installation.rst
- python/dolfinx/wrappers/fem.cpp
- python/dolfinx/wrappers/mesh.cpp
This change removes xtensor. xtensor was used only in the C++ interface for mesh entity marking and user expressions. Other internal use was removed earlier.
Removing xtensor
- reduces the number of dependencies
- avoids ABI incompatibilities that can sneak in if `xsimd` is installed
- avoids potential C++20 compatibility issues (xtensor does not support C++20)
Closes #2350.
> Remove xtensor

- .github/workflows/redhat.yml
- .github/workflows/spack.yml
Run the Spack tests in a container (`ubuntu:latest`) rather than the Github actions VM image. The makes clear the minimum dependencies to build DOLFINx using Spack. The Github VM image comes with a range of libraries/tools, which obscures the minimum requirements.
> Run Spack CI in a bare container

- .github/workflows/ccpp.yml
- python/.isort.cfg
- python/demo/demo_gmsh.py
- python/demo/demo_poisson.py
- python/demo/demo_stokes.py
- python/doc/source/conf.py
- python/doc/source/jupytext_process.py
- python/dolfinx/io/gmshio.py
- python/test/unit/fem/test_assemble_domains.py
- python/test/unit/fem/test_element_integrals.py
- python/test/unit/fem/test_expression.py
- python/test/unit/fem/test_interpolation.py
- python/test/unit/io/test_adios2.py
- python/test/unit/mesh/test_mesh.py
This corrects an error in `python/.isort.cfg` which allows the CI and user call to `isort` to be simplified.
> Fix for isort configuration

- README.md
Some markdown viewers don't render fenced code blocks without blank lines around them correctly.
Although `github.com` renders it correctly, it recommends using blank lines to make the raw Markdown easier to read.
> Update readme - Add blank lines before fenced code blocks 

- .github/workflows/spack.yml
When installing a Spack package without specifying the version,
1. If any package is already installed, then no new version is installed
2. If a version is specified, then the specified version is installed unless the specified version has already been installed
The CI was not working as expected because it first installed the `@main` version (to test development version), and then installed without a specified version (with the intention of testing the default, latest release version). However, since after install the `@main` version, Spack detected and existing build and did not install the release version.
This change reverse the order of install in the CI, first installing the 'default' release version and then installing `@main`.
> Fix Spack CI order

- python/dolfinx/plot.py
- python/test/unit/io/test_vtk.py
> Fix pyvista data interface

- python/dolfinx/fem/function.py
- python/test/unit/fem/test_function_space.py
This PR fixes an issue where the UFL element of a vector function space has the wrong geometric dimension when the geometric dimension is higher than the topological dimension. It also adds a test that fails on main.
> Fix geometric dimension of `VectorFunctionSpace` element cell

- cpp/demo/interpolation-io/main.cpp
- cpp/dolfinx/fem/DirichletBC.h
- cpp/dolfinx/fem/Expression.h
- cpp/dolfinx/fem/Form.h
- cpp/dolfinx/fem/interpolate.h
- cpp/dolfinx/fem/utils.cpp
- cpp/dolfinx/fem/utils.h
- cpp/dolfinx/io/ADIOS2Writers.cpp
- cpp/dolfinx/io/ADIOS2Writers.h
- cpp/dolfinx/io/XDMFFile.cpp
- cpp/dolfinx/io/XDMFFile.h
- cpp/dolfinx/la/Vector.h
- cpp/dolfinx/mesh/Geometry.h
- cpp/dolfinx/mesh/Mesh.cpp
- cpp/dolfinx/mesh/MeshTags.h
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/Topology.h
- cpp/dolfinx/refinement/plaza.cpp
- python/dolfinx/wrappers/fem.cpp
- python/dolfinx/wrappers/io.cpp
- python/dolfinx/wrappers/la.cpp
- python/dolfinx/wrappers/mesh.cpp
In general, pass `std:span` by value rather than const reference.
Similarly for `std::shared_ptr`.
> Const consistency improvements

- python/dolfinx/fem/petsc.py
It has been my experience that the default PETSc LU solver can fail for many quite standard problems. This patch keeps the behaviour of using the PETSc defaults for KSP, but proposes in the example that users set `pc_factor_mat_solver_type` to be MUMPS if they switch to LU.
> Suggest that users try MUMPS for LU decomposition.

- python/dolfinx/fem/petsc.py
- python/test/unit/fem/test_custom_assembler.py
- python/test/unit/fem/test_dofmap.py
- python/test/unit/fem/test_expression.py
- python/test/unit/fem/test_function_space.py
This PR fixes a few bugs picked up by SonarCloud.
Because the code with the two `except OSError` was incorrect (an exception block can only pickup a single exception type at a time) and used in three places
I decided to refactor the PETSc shared library loader into its own function. I removed the call to find the PETSc library using ctypes, this is likely to create a conflict with the version that petsc4py was compiled against. It still works if the library is in e.g. `/usr/local/lib` as shown by the successful RockyLinux CI run.
> Fix bugs picked up by static analysis

- python/setup.py
Installing the python layer with Spack fails with `error: "VERSION_INFO" redefined`. This PR removes the line where `VERSION_INFO` is redefined.
> Remove redefinition of `VERSION_INFO`

- cpp/demo/CMakeLists.txt
- cpp/demo/interpolation_different_meshes/main.cpp
- Remove `xtensor` leftover calls
- Add  subdirectory to cmake 
- Make sure it runs on CI
> Fix  interpolation demo (C++)

- cpp/dolfinx/mesh/Mesh.cpp
The current implementation of `create_submesh` does not scale due to an `std::find` on a potentially large array in a tight loop. This PR precomputes the map to avoid this issue.
Performance results:
I ran the following code for different values of `n`:
```
msh = mesh.create_unit_cube(
MPI.COMM_WORLD, n, n, n, ghost_mode=mesh.GhostMode.none)
tdim = msh.topology.dim
entities = mesh.locate_entities(msh, tdim, lambda x: x[0] <= 0.5)
mesh.create_submesh(msh, tdim, entities)
```
The timings are as follows:
|  | `n = 8` | `n = 16` | `n = 32` |
| ------------- | ------------- | ------------- | ------------- |
| Main  | 0.0365 s  | 0.861 s  | 46.6 s |
| This branch  | 0.00904 s  | 0.0459 s  | 0.38 s  |
The difference in performance gets larger as the mesh size increases.
> Improve `create_submesh` performance

- cpp/dolfinx/fem/Form.h
Currently, `set_exterior_facet_domains` makes assumptions about the ghosting of the mesh. Looks like it was missed when https://github.com/FEniCS/dolfinx/pull/2337 was merged. This PR removes these assumptions. Unfortunately, it relies on an `std::lower_bound` in a loop, which is not ideal. However, I plan to replace this in https://github.com/FEniCS/dolfinx/pull/2269
> Fix `set_exterior_facet_domains` for arbitrary ghosting

- python/dolfinx/mesh.py
> State in the python interface too that MeshTags indices are expected to be sorted and unique

- cpp/dolfinx/fem/Form.h
- cpp/dolfinx/graph/partition.h
- cpp/dolfinx/la/MatrixCSR.h
- cpp/dolfinx/mesh/MeshTags.h
- cpp/dolfinx/refinement/utils.cpp
- python/dolfinx/mesh.py
- python/dolfinx/wrappers/la.cpp
> Fix incorrect use of std::span

- python/test/unit/fem/test_mixed_element.py
> Fix unused ElementType

- docker/Dockerfile
> Install latest doxygen in CI

- .github/workflows/macos.yml
Lacks adequate support for C++20.
> Remove macos-11 from CI

- python/dolfinx/fem/function.py
`expr.ufl_domain()` was deprecated with https://github.com/FEniCS/ufl/pull/131
This removes some of the deprecation warnings.
It seems ufl itself still uses this internally so not all deprecation warnings will disappear.
> Remove deprecated ufl function

- python/test/unit/common/test_public_api.py
Rename an ambiguously named test which checks for implementation of the public API via `__all__`.
Also add a comment stub explaining the test.
> Rename public API test to be more meaningful

- cpp/dolfinx/common/Scatterer.h
This PR prevents the following warning: `field '_dest' will be initialized after field '_remote_inds' [-Werror,-Wreorder-ctor]`
> Reorder `Scatterer` initialiser list

- docker/Dockerfile
See https://gitlab.com/petsc/petsc/-/issues/1288.
> Workaround in Dockerfile for PETSc gcc/clang issue in complex mode

- docker/Dockerfile
Need more time to sort out PETSc 3.18 with CI.
> Revert PETSc CI version to 3.17 series

- python/demo/demo_axis/demo_axis.py
- python/demo/demo_pml/demo_pml.py
- python/demo/demo_pml/efficiencies_pml_demo.py
- python/demo/demo_scattering_boundary_conditions/analytical_efficiencies_wire.py
- python/dolfinx/fem/function.py
- python/dolfinx/io/utils.py
- python/test/unit/fem/test_constant.py
- python/test/unit/io/test_vtk.py
Currently, for a few existing demos, the isort checks fail. The pipeline still runs successfully because the isort checks are non-blocking. However, the following annotations appear:
Log of the isort checks:
I changed the order of the imports to fix the isort checks.
> Fix isort checks for some demos

- cpp/CMakeLists.txt
since basix can be found without Python, only check for basix via Python if Python is found.
other uses of Python3_EXECUTABLE are already protected by Python3_Interpreter_FOUND, suggesting it is expected to be optional even though it's currently required.
> [cmake] make Python3 interpreter optional

- docker/Dockerfile
It's always a good idea to update pip before using it, but there are specific patches since 22.04 to fix compatibility with apt-installed Python, which are relevant to using the dev-env image (https://github.com/jorgensd/dolfinx_mpc/pull/42)
> make sure setuptools/pip are up-to-date before using them

- .circleci/config.yml
- .github/workflows/ccpp.yml
- python/demo/demo_lagrange_variants.py
- python/demo/demo_types.py
- python/dolfinx/fem/function.py
- python/dolfinx/geometry.py
- python/dolfinx/io/gmshio.py
- python/dolfinx/io/utils.py
- python/dolfinx/mesh.py
- python/dolfinx/plot.py
- python/test/unit/fem/test_custom_assembler.py
- python/test/unit/fem/test_custom_jit_kernels.py
- python/test/unit/fem/test_expression.py
- python/test/unit/fem/test_function_space.py
- python/test/unit/fem/test_interpolation.py
- python/test/unit/geometry/test_bounding_box_tree.py
- python/test/unit/io/test_adios2.py
- python/test/unit/io/test_xdmf_mesh.py
- python/test/unit/mesh/test_face.py
- python/test/unit/mesh/test_manifold_point_search.py
- python/test/unit/mesh/test_mesh.py
- python/test/unit/mesh/test_refinement.py
- python/test/unit/nls/test_newton.py
The difference between C++ and Python meshes is that Python meshes have `ufl_cell` and `ufl_domain` methods. The 'trick' used to handle mesh construction does not work with Python 3.11 (see https://github.com/FEniCS/dolfinx/issues/2423#issuecomment-1370847185).
This change wraps all `Mesh` instances in Python. This change is simple and fixes #2423, and will allow straightforward future support of different precision mesh geometry storage. It does, however, involve more hand-coding of methods and functions that operate of meshes. The design is similar to how `FunctionSpace` is handled on the Python side. The upside of the extra hand-coding is that docstring are easier to write.
> Wrap C++ `Mesh` from Python (fixes support for Python 3.11)

- cpp/dolfinx/fem/utils.h
This bug was introduced in https://github.com/FEniCS/dolfinx/pull/2522.
> Fix `create_form` to only integrate over owned entities

- python/dolfinx/io/__init__.py
`distribute_entity_data` now has its own Python-wrapper, and should be imported (and not the C++ function)
> Fix import of `distribute_entity_data`

- cpp/dolfinx/mesh/Geometry.h
- cpp/dolfinx/mesh/Mesh.h
- python/dolfinx/mesh.py
> Fix doc error in `mesh.create_mesh` for coordinate layout.

- .github/workflows/docker.yml
- python/demo/demo_axis/demo_axis.py
- python/demo/demo_pml/demo_pml.py
Build fails on smaller runner.
> Use larger arm Docker build runner (more memory)

- cpp/dolfinx/fem/assembler.h
- python/test/unit/fem/test_assembler.py
- python/test/unit/fem/test_nonlinear_assembler.py
Fixes #2558.
Also refactors block assembly tests to use more scoping.
> Fix extraction of mesh from array of forms in lifting

- cpp/dolfinx/fem/FiniteElement.cpp
- python/test/unit/fem/test_custom_basix_element.py
> Fix DOF transformations for custom elements

- python/demo/demo_axis/demo_axis.py
- python/demo/demo_cahn-hilliard.py
- python/demo/demo_mixed-poisson.py
- python/demo/demo_pml/demo_pml.py
- python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
- python/demo/demo_static-condensation.py
- python/demo/demo_stokes.py
- python/demo/demo_waveguide/demo_half_loaded_waveguide.py
- python/dolfinx/fem/function.py
- python/dolfinx/mesh.py
- python/test/unit/fem/test_assembler.py
- python/test/unit/fem/test_bcs.py
- python/test/unit/fem/test_complex_assembler.py
- python/test/unit/fem/test_discrete_operators.py
- python/test/unit/fem/test_dofmap.py
- python/test/unit/fem/test_function.py
- python/test/unit/fem/test_function_space.py
- python/test/unit/fem/test_interpolation.py
- python/test/unit/fem/test_mixed_element.py
- python/test/unit/fem/test_nonlinear_assembler.py
- python/test/unit/io/test_adios2.py
- python/test/unit/io/test_vtk.py
This allows us to use `msh.basix_cell()` when creating an element instead of having to pass in `msh.ufl_cell().cellname()`.
This removes the need for https://github.com/FEniCS/basix/issues/648 (and so is an alternative to https://github.com/FEniCS/basix/pull/649).
> Add `basix_cell` method to `Mesh`

- python/demo/demo_biharmonic.py
- python/demo/demo_elasticity.py
- python/demo/demo_interpolation-io.py
- python/demo/demo_lagrange_variants.py
- python/dolfinx/__init__.py
- python/dolfinx/fem/forms.py
- python/dolfinx/fem/function.py
- python/test/unit/fem/test_assemble_domains.py
Avoids directly importing petsc4py just to get a scalar type.
> Add default scalar type

- cpp/dolfinx/fem/petsc.h
> Remove inconsistent behaviour when building sparsity pattern from forms

- .github/workflows/macos.yml
- docker/Dockerfile
> Fix Cython version to temporarily fix issue with petsc4py includes

- python/dolfinx/fem/function.py
> Add `complex` to type hints for `Constant`

- cpp/dolfinx/fem/DofMap.cpp
It was also inconsistent use of the variable name, as it has already been used in the previous assertion.
> Variable only used in assert causing unused variable warnings on release

- .github/workflows/ccpp.yml
Easy to wonder if '32' in a label means `int32` or `float32`. Fix this ambiguity.
> Use more expressive Actions labels

- .github/workflows/docker-end-user.yml
- README.md
Fixes #2642. Should resume end-user docker workflow, which has been broken for a week.
> Remove "needs" from the first step of the end-user Docker images workflow, since now build images are prepared in a standalone workflow

- cpp/dolfinx/fem/Function.h
- cpp/dolfinx/fem/dofmapbuilder.cpp
- cpp/dolfinx/fem/petsc.h
- cpp/dolfinx/la/MatrixCSR.h
- cpp/dolfinx/la/SparsityPattern.cpp
- cpp/dolfinx/la/SparsityPattern.h
- cpp/dolfinx/la/Vector.h
- cpp/dolfinx/la/petsc.h
- cpp/test/matrix.cpp
- python/demo/demo_types.py
- python/dolfinx/fem/assemble.py
- python/dolfinx/la.py
- python/dolfinx/wrappers/assemble.cpp
- python/dolfinx/wrappers/la.cpp
- python/test/unit/fem/test_assembler.py
- python/test/unit/fem/test_custom_jit_kernels.py
- python/test/unit/fem/test_expression.py
- python/test/unit/la/test_matrix_vector.py
- python/test/unit/la/test_sparsity_pattern.py
- python/test/unit/la/test_vector_scatter.py
* use `squared_norm()` for both `Vector` and `MatrixCSR`
* Use `InsertMode` not `ScatterMode`
* Use `finalize` for both `MatrixCSR` and `SparsityPattern`
* `index_map()` not `map()` for `Vector` 
If any others seem obvious, we can add to this branch.
> Adjust API to be more consistent

- python/demo/demo_stokes.py
This function space is not the same as the collapsed one. Causes issue if you change the bc to be space-dependent
> Wrong function-space used in direct solver

- python/demo/demo_types.py
- python/dolfinx/fem/assemble.py
- python/dolfinx/fem/forms.py
- python/dolfinx/fem/function.py
- python/dolfinx/la.py
- python/dolfinx/wrappers/la.cpp
- python/test/unit/fem/test_custom_assembler.py
Demonstrates use of `MatrixCSR` for systems with a block size.
Also adds a matrix type (block size) option to the matrix assembly function.
> Add elasticity to 'types' demo

- cpp/demo/poisson/main.cpp
- cpp/dolfinx/io/ADIOS2Writers.cpp
- cpp/dolfinx/io/ADIOS2Writers.h
- python/dolfinx/io/utils.py
- python/setup.cfg
Fixes visitor pattern for extracting function names.
Fixes #2702 (I think).
> Fix extraction of `fem::Function` names in ADIOS2-based output

- cpp/dolfinx/io/ADIOS2Writers.h
Related to the discussion in https://github.com/FEniCS/dolfinx/pull/2679 , I think there still is a problem and that this commit fixes it.
> Correctly wrap FidesWriter constructor

- cpp/CMakeLists.txt
- cpp/dolfinx/CMakeLists.txt
- cpp/dolfinx/io/HDF5Interface.h
Reverts change that gets string version of the native HDF5 type for printing when a exception is raised.
The "HL" component is an extra dependency but brought little benefit.  Fixes Spack build failure.
> Avoid introducing HDF5-HL library

- cpp/dolfinx/la/matrix_csr_impl.h
- python/test/unit/la/test_matrix_csr.py
Currently, there is no runtime check that matrix entries are correctly added (exist in sparsity), except in Debug mode.
The overhead to doing so is negligible, so this PR adds that check.
> Perform checks on matrix insertion in `MatrixCSR`

- docker/Dockerfile.test-env
ADIOS2 python interface is currently not exposed in the docker images.
This is because ADIOS defaults the installation to: `/usr/local/lib/python3/dist-packages`
which is not in our Python path.
I initially thought I could set it to `/usr/local/lib/python3.10` which is on our path, but I couldn't find a nice way to determine the python version automatically and set the relevant env variable, ref: https://github.com/moby/moby/issues/29110
> Put adios2 python interface in usr/local/lib

- cpp/demo/hyperelasticity/main.cpp
- cpp/dolfinx/fem/Expression.h
- cpp/dolfinx/fem/Function.h
- cpp/dolfinx/fem/utils.h
- python/demo/demo_pyvista.py
- python/dolfinx/fem/forms.py
- python/dolfinx/fem/function.py
- python/dolfinx/fem/petsc.py
- python/dolfinx/io/gmshio.py
- python/dolfinx/jit.py
- python/dolfinx/wrappers/fem.cpp
- python/test/unit/fem/test_expression.py
- python/test/unit/mesh/test_ghost_mesh.py
C++ Expression no longer requires a mesh at construction, which supports fixing of #2363 and will avoid some unnecessary JIT. The mesh is now passed to the `Expression::eval` function.
Also remove `dict()` default parameters, use `None` instead.
> Simplify `fem::Expression`

- cpp/dolfinx/la/MatrixCSR.h
- cpp/test/matrix.cpp
- python/demo/demo_types.py
- python/dolfinx/la.py
- python/dolfinx/wrappers/la.cpp
- python/test/unit/fem/test_assemble_cppimport.py
- python/test/unit/fem/test_assemble_domains.py
- python/test/unit/fem/test_assemble_submesh.py
- python/test/unit/fem/test_assembler.py
- python/test/unit/fem/test_bcs.py
- python/test/unit/fem/test_custom_jit_kernels.py
- python/test/unit/fem/test_discrete_operators.py
- python/test/unit/fem/test_element_integrals.py
- python/test/unit/fem/test_expression.py
- python/test/unit/fem/test_ghost_mesh_assembly.py
- python/test/unit/fem/test_mixed_element.py
- python/test/unit/fem/test_symmetry.py
- python/test/unit/fem/test_vector_assemble.py
- python/test/unit/la/test_matrix_csr.py
Rename matrix csr finalize to scatter_rev.
Fixes #2710.
> Rename ‘MatrixCSR::finalize’ to ‘MatrixCSR::scatter_rev’

- python/demo/demo_elasticity.py
- python/demo/demo_gmsh.py
- python/demo/demo_tnt-elements.py
- python/dolfinx/io/gmshio.py
Refactor Gmsh demo into functions. Makes dependencies clearer.
Also makes it easier to extract core Gmsh steps for unit tests that need higher-order meshes.
> Refactor Gmsh demo

- cpp/dolfinx/fem/utils.cpp
Related to changes in `ufcx` interface for `entity_dofs`, see https://github.com/FEniCS/ffcx/pull/586, this uses a simplified interface, also fixing issues with pyramid/prism.
> Use new static data structures in ufcx for `entity_dofs`

- cpp/dolfinx/fem/utils.h
Update to interface with ufcx to with `form_integrals` `form_integral_offsets` and `form_integral_ids` instead of function calls to C.
> Get integral data from static data structures, not a function

- cpp/dolfinx/fem/interpolate.h
- python/test/unit/fem/test_function.py
- python/test/unit/fem/test_interpolation.py
Tests are added where mesh partitions will have no data to send nor receive; however, interpolation into non matching meshes is still valid.
Fixes #2747.
> Remove empty non matching mesh interpolation data exception

- python/demo/demo_biharmonic.py
- python/demo/demo_cahn-hilliard.py
- python/demo/demo_pml/demo_pml.py
- python/demo/demo_pml/efficiencies_pml_demo.py
- python/demo/demo_poisson.py
- python/demo/demo_scattering_boundary_conditions/analytical_efficiencies_wire.py
- python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
- python/demo/demo_waveguide/demo_half_loaded_waveguide.py
Line break of inline equation breaks jupytertext formatting. Put equation on one line.
Fixes #2752.
> Fix LaTeX text formatting issue

- python/demo/demo_axis/demo_axis.py
- python/demo/demo_biharmonic.py
- python/demo/demo_cahn-hilliard.py
- python/demo/demo_interpolation-io.py
- python/demo/demo_pml/demo_pml.py
- python/demo/demo_poisson.py
- python/demo/demo_pyvista.py
- python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
- python/demo/demo_types.py
- python/demo/demo_waveguide/demo_half_loaded_waveguide.py
- python/dolfinx/fem/function.py
- python/dolfinx/graph.py
- python/dolfinx/plot.py
- python/test/unit/fem/test_assembler.py
- python/test/unit/graph/test_adjacencylist.py
- python/test/unit/io/test_adios2.py
- python/test/unit/io/test_vtk.py
- python/test/unit/mesh/test_mesh.py
- python/test/unit/mesh/test_meshtags.py
Fixes #2760.
`plot.create_vtk_mesh` -> `plot.vtk_mesh`
`create_adjacencylist` -> `adjacencylist`
> Remove "create" prefix from some functions

- python/doc/source/api.rst
- python/dolfinx/io/gmshio.py
- python/dolfinx/mesh.py
- Makes documentation generation independent on whether or not gmsh can be imported
- Adds errors message if function that requires gmsh is called and gmsh is not available
- Required a small number of type hints for gmsh types to be removed
Supersedes #2771.
> Re-design gmsh import in `io.gmshio`

- python/demo/demo_biharmonic.py
- python/demo/demo_cahn-hilliard.py
- python/demo/demo_elasticity.py
- python/demo/demo_helmholtz.py
- python/demo/demo_mixed-poisson.py
- python/demo/demo_navier-stokes.py
- python/demo/demo_poisson.py
- python/demo/demo_static-condensation.py
- python/demo/demo_stokes.py
- python/dolfinx/__init__.py
- python/dolfinx/fem/petsc.py
- python/dolfinx/la.py
- python/dolfinx/nls/petsc.py
- python/test/unit/fem/test_assemble_cppimport.py
- python/test/unit/fem/test_complex_assembler.py
- python/test/unit/fem/test_custom_assembler.py
- python/test/unit/fem/test_fem_pipeline.py
- python/test/unit/fem/test_nonlinear_assembler.py
Somethig must have changed in PETSc.
> Disable mypy on petsc4py 3.20 types

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/common/MPI.cpp
- cpp/dolfinx/fem/petsc.cpp
- cpp/dolfinx/la/petsc.cpp
- python/test/unit/fem/test_nonlinear_assembler.py
Appears to be an issue between PETSc and OpenMPI on lifetime management of MPI communicators.
Re-enable test that was disabled to this issue.
Fixes #2800 (sort of).
> Re-factor a PETSc Vec creation function due to OpenMPI/PETSc interaction issue

- cpp/test/common/sort.cpp
needed for `std::bind`. Unclear under exactly what circumstances, but presumably it's sometimes implied by another dependency.
This is the compilation error with 0.7.0:
```
/home/conda/feedstock_root/build_artifacts/fenics-dolfinx-split_1696590289646/test_tmp/cpp/test/common/sort.cpp: In function 'void CATCH2_INTERNAL_TEMPLATE_TEST_0()':
/home/conda/feedstock_root/build_artifacts/fenics-dolfinx-split_1696590289646/test_tmp/cpp/test/common/sort.cpp:23:25: error: 'bind' is not a member of 'std'
23 |   auto generator = std::bind(distribution, engine);
|                         ^~~~
/home/conda/feedstock_root/build_artifacts/fenics-dolfinx-split_1696590289646/test_tmp/cpp/test/common/sort.cpp:12:1: note: 'std::bind' is defined in header '<functional>'; did you forget to '#include …
```
> TST: add missing include <functional>

- python/dolfinx/mesh.py
prevents failure to import dolfinx.mesh in Python 3.8 due to the use of `tuple[...]`, which requires Python 3.9. Since this is in an annotation, deferring annotation evaluation via the annotations `__future__` ought to work, as is done in some other files already.
This suggests that there aren't CI jobs to verify that dolfinx builds and then imports with Python 3.8, I think?
testing in https://github.com/conda-forge/fenics-dolfinx-feedstock/pull/47 if you want to wait for that to confirm this is sufficient.
> Missing from __future__ import annotations

- python/doc/source/jupytext_process.py
- python/dolfinx/wrappers/io.cpp
- Convert PathLib.Path so string, from Drew Parsons related to Debian packaging.
- Did not compile with pedantic warnings on GCC 10 series.
Will backport onto release and tag v0.7.0.post0.
Functionally identical to v0.7.0 so will not bump version numbers.
> Post-release fixes for 0.7.0

- .github/workflows/conda.yml
macos-13 runner does not have conda in default image.
> Add conda to macos-13 runner.

- docker/Dockerfile.redhat
- docker/Dockerfile.test-env
- python/dolfinx/__init__.py
Opening this to assess question #2835 on CI
Closes #2835
> Drop setting dl open flags in `dolfinx/__init__.py`

- cpp/dolfinx/io/xdmf_function.cpp
> Update computation of number of components for arbitrary value shape in `xdmf_function`

- .github/workflows/ccpp.yml
- .github/workflows/oneapi.yml
- .github/workflows/redhat.yml
- docker/Dockerfile.test-env
Turns out that most of this was already available in the docker files, but we did not trigger test/dev env workflow.
See https://github.com/FEniCS/dolfinx/actions/runs/6729006694
> Remove installation of build requirements from workflows, since they are already installed in the underlying docker images

- cpp/dolfinx/geometry/utils.h
- python/test/unit/geometry/test_bounding_box_tree.py
Reported by @nate-sime 
The following MWE produces the wrong collision for the global_bb_tree
```python
import dolfinx
mesh = dolfinx.mesh.create_unit_square(MPI.COMM_WORLD, 10, 10)
xp = np.array([[100.0, 100.0, 0.0]], dtype=np.double)
tree = dolfinx.geometry.bb_tree(mesh, mesh.topology.dim, padding=1e-4)
global_tree = tree.create_global_tree(mesh.comm)
def pprint(*msg):
print(f"[{mesh.comm.rank}]: " + " ".join(map(str, msg)), flush=True)
pprint(dolfinx.common.git_commit_hash)
pprint(dolfinx.geometry.compute_collisions_points(tree, xp))
pprint(dolfinx.geometry.compute_collisions_points(global_tree, xp))
```
giving the following in serial:
```bash
[0]: f488f4ecc687d0065315bc9a74939634b18e11ff
[0]: <AdjacencyList> with 1 nodes
0: []
[0]: …
```
> Fix bounding box leaf collision check

- python/dolfinx/wrappers/caster_petsc.h
Downstream libraries may need to define additional casters. For instance, in `multiphenicsx` I need to define a caster for `IS`.
> Clean up unused includes in PETSc nanobind casters, but leave the macro available

- python/test/unit/fem/test_function_space.py
Was disabled when `basix` was using `nanobind` and `dolfinx` was using `pybind11` instead. It may have not been working when the `nanobind` PR was merged because the version of `nanobind` used by `basix` was slightly different then the one installed during CI for `dolfinx`, but that is sorted now that both `basix` and `dolfinx` use the same `nanobind` from the docker image.
> Re-enable basix element test

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/common/IndexMap.h
- cpp/dolfinx/mesh/Geometry.h
- cpp/dolfinx/mesh/Topology.cpp
Reduces one step of communication to discover dest ranks (ranks that ghost indices owned by the caller.).
> Remove call to `compute_graph_edges` in `compute_owned_indices`

- python/CMakeLists.txt
With gcc, `-Os` (recommended by nanobind) can lead to significantly slower binaries than `-O2`. DOLFINx has considerable templated code, which gets compiled by the nanobind wrappers. This makes performance of the wrapper library sensitive to the compiler options.
This improves the run-time of #2891 to be better than in 0.7.1
> Change nanobind build options to remove `-Os`

- .github/workflows/docker-end-user.yml
- docker/Dockerfile.end-user
Related to the nightly timings #2891.
We still have a regression with the introduction of nanobind, but now we are down to a halving in performance.
> Correct CMAKE_BUILD_TYPE in end user Docker images

- python/CMakeLists.txt
Remove custom messing with CMake builds types. Messing about can affect tools that attempt to set the build type.
> Simplify CMake for Python interface build 

- .github/workflows/docker-end-user.yml
We are now back to https://github.com/FEniCS/dolfinx/issues/2846, see log in https://github.com/FEniCS/dolfinx/actions/runs/6917539955/job/18818837676
I'll temporarily increase back to 8 cores, which was the temporary fix in https://github.com/FEniCS/dolfinx/pull/2860
and re-open https://github.com/FEniCS/dolfinx/issues/2861 as a reminder to revert this change.
After test in https://github.com/FEniCS/dolfinx/actions/runs/6919475270 runs successfully, I'll merge this
> Increase again number of cores on ARM buildjet runners while building Docker end-user image

- .github/workflows/docker-update-stable.yml
- RELEASE.md
Installs regclient and links :stable to e.g. :v0.7.2. To be used after creating tagged test/development/end-user images using the other actions.
> Adds an action to quickly update stable image tag

- docker/Dockerfile.test-env
In preparation of a PR similar to https://github.com/FEniCS/basix/pull/748 for `dolfinx`.
> Add `ruff` to base test environment

- RELEASE.md
I renamed them in https://github.com/FEniCS/ffcx/pull/638 https://github.com/FEniCS/basix/pull/739
> Fix broken links to integration test workflows in `RELEASE.md`

- .github/workflows/ccpp.yml
Noticed this while I was investigating whether to prepare an equivalent of https://github.com/FEniCS/basix/pull/751 for `dolfinx`. At first glance I couldn't understand why there wasn't a push of the python part of the documentation: there was, but it was stored alongside the cpp in a commit message starting with `C++`.
> Fix misleading commit message when updating documentation repository

- python/dolfinx/fem/__init__.py
Adds `transpose_dofmap` to `dolfinx.fem` module properly, such that it is documented online.
> Expose `transpose_dofmap` in `dolfinx.fem`

- python/doc/source/api.rst
Nothing in this module, except its submodule `dolfinx.nls.petsc`.
> Remove `dolfinx.nls` from Python documentation

- python/doc/source/conf.py
Expose autosummary for __all__ variables: https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_ignore_module_all
> Improve overview of online documentation with autosummary

- .github/workflows/spack.yml
DOFLINx v0.7.2 and earlier use pybind11 with link-time optimisation (LTO). This uses a lot of RAM, and exhausts the Actions runner.
Future v0.8 uses nanobind in place of pybind11, which is lighter and doesn't require LTO. Release version testing can be added once 0.8 is released.
> Disable Spack CI 0.7.2 Python build

- python/test/unit/mesh/test_higher_order_mesh.py
Resolves #2938.
Follows guidance from: https://gmsh.info/doc/texinfo/gmsh.html
> // The default recombination algorithm might leave some triangles in the mesh,
// if recombining all the triangles leads to badly shaped quads. In such cases,
// to generate full-quad meshes, you can either subdivide the resulting hybrid
// mesh (with Mesh.SubdivisionAlgorithm = 1), or use the full-quad recombination
// algorithm, which will automatically perform a coarser mesh followed by
// recombination, smoothing and subdivision. Uncomment the following line to try
// the full-quad algorithm:
Tested locally with: `ghcr.io/fenics/dolfinx/dolfinx:v0.7.2-r1@sha256:29c96c06ceda98a234de0d5f1a2c94e839fe0335a065d62c2ed1f56b9df76b22`
> Update GMSH quadrilateral recombination options to force pure quadrilateral meshes

- cpp/dolfinx/common/IndexMap.cpp
**Issue**
Current check for a global value coming into `global_to_local`  has several issues
1. If the global value is lower than the lowest existing ghost on process
2. If the value is within the range of the smallest and largest ghost value, but not equal
**Fixes**
- Check for equality if not at end of ghost array
Resolves #2962
> Fix `IndexMap->global_to_local()`

- cpp/dolfinx/fem/FiniteElement.cpp
- cpp/dolfinx/fem/FiniteElement.h
> Allow for blocked elements with block size 1

- python/dolfinx/fem/function.py
- python/dolfinx/io/gmshio.py
Fixes to #2960 in addition to those already in #2967.
Should fix the runtime error 
```
E       TypeError: Cannot interpret 'typing.Union[numpy.dtype[typing.Any], NoneType, type[typing.Any], numpy._typing._dtype_like._SupportsDType[numpy.dtype[typing.Any]], str, tuple[typing.Any, int], tuple[typing.Any, typing.Union[typing.SupportsIndex, collections.abc.Sequence[typing.SupportsIndex]]], list[typing.Any], numpy._typing._dtype_like._DTypeDict, tuple[typing.Any, typing.Any]]' as a data type
```
that appears when calling `dolfinx.io.gmshio.ufl_mesh` e.g. in ngsPETSc by @UZerbinati at
https://github.com/NGSolve/ngsPETSc/actions/runs/7437684405/job/20235586388
(or at least, make it into the more meaningful error "from now on you must also pass dtype")
> Further typing fixes

- docker/Dockerfile.end-user
- python/README.md
This does not change the default stripping policy of scikit-build-core (true).
The docker end user images are built by default in release mode without binary stripping. This leads to small binaries as there are no debug symbols in release mode.
The README is updated to add a scikit-build-core config flag to not strip debug symbols, so that it is possible to debug!
Also removes the broken CMAKE_CXX_FLAGS stuff as pointed out by @mhabera.
Resolves #2948.
> Change binary stripping settings for scikit-build-core

- .github/workflows/docker-end-user.yml
> Remove default CMAKE_BUILD_TYPE from end-user action

- .github/workflows/sonarcloud.yml
Try bumping sonar-cloud and setup-java action
> Update sonar-scanner version in CI

- python/demo/demo_helmholtz.py
- python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
Delete an unused variable in demo_helmholtz.py
Add a description for clarity in demo_scattering_boundary_conditions.py
> Improvements to `demo_helmholtz.py` and  `demo_scattering_boundary_conditions.py`

- AUTHORS
- docker/Dockerfile.test-env
In preparation of `fenics-dev@googlegroups.com` shutting down.
> Drop `fenics-dev@googlegroups.com` in favor of `fenics-steering-council@googlegroups.com`

- cpp/demo/custom_kernel/main.cpp
- Fix typo and improve readability of timings.
- Generalise top description.
I noticed that explicit geometry typing was removed - I guess this was intentional to reduce complexity?
> Small tweaks to custom cell kernel demo

- python/demo/demo_axis/demo_axis.py
- python/demo/demo_biharmonic.py
- python/demo/demo_cahn-hilliard.py
- python/demo/demo_mixed-poisson.py
- python/demo/demo_navier-stokes.py
- python/demo/demo_pml/demo_pml.py
- python/demo/demo_poisson.py
- python/demo/demo_scattering_boundary_conditions/demo_scattering_boundary_conditions.py
- python/demo/demo_stokes.py
- python/demo/demo_tnt-elements.py
- python/demo/demo_waveguide/demo_half_loaded_waveguide.py
Reported at: https://fenicsproject.discourse.group/t/current-commet-may-lead-error-in-jupyter-notebook/13347?u=dokken
Especially multi-line mathematics with `&` for alignment needs to be wrapped with `\begin{align} .... \end{align}`
> Update all notebooks to render correctly on web page and in notebooks.

- README.md
Given Spack/HPC users need to do parallel IO we should probably hint at building with ADIOS2.
> ADIOS2 for Spack by default

- python/dolfinx/mesh.py
- python/test/unit/mesh/test_refinement.py
Reported at https://fenicsproject.discourse.group/t/input-for-mesh-refinement-with-refine-plaza/13426
It seems to me that the current python API is certainly wrong (the `option` argument is not used anywhere), but I can't understand how it is possible that tests on `main` are currently passing since:
* a required input argument to the `nanobind` wrapped function is not being passed in from python, but `nanobind` is not complaining.
* the only two tests that exercise `refine_plaza` were providing input arguments in the wrong order.
Opening this as draft because I have no experience with mesh refinement, so I'd need help from someone else if the fix is more involved than sorting out wrong order of input arguments.
> Fix input arguments to `dolfinx.mesh.refine_plaza`

- cpp/CMakeLists.txt
If a package is explicitly enabled via CMake, e.g. `-DDOLFINX_ENABLE_KAHIP`, and is not available or cannot be configured, this change causes a CMake error. This helps package maintainers (#3011) and users.
Resolves #3011.
> Ensure that explicitly requested packages are enabled by CMake (and otherwise fail)

- cpp/dolfinx/io/xdmf_utils.cpp
Add missing `MPI_Type_free`.
Resolves #2997.
> Fix leak for `MPI_Datatype`

- .flake8
Not needed now that we use ruff.
> Remove `.flake8` file

- python/dolfinx/fem/__init__.py
Reported at https://fenicsproject.discourse.group/t/attribute-error-while-calculating-l2-error-for-non-matching-meshes/13744/5?u=dokken
> Missing C++ accessor to mesh object in create nonmatching interpolation data

- cpp/dolfinx/common/IndexMap.cpp
For Functions on an MPI communicator of size 1, this change reduced the number of communicators that are created.
> Mark IndexMaps on communicators with size 1 as non-overlapped

- cpp/dolfinx/common/IndexMap.cpp
- cpp/dolfinx/common/IndexMap.h
- cpp/dolfinx/fem/DofMap.cpp
- cpp/dolfinx/mesh/Geometry.h
- cpp/dolfinx/mesh/Topology.cpp
- python/dolfinx/wrappers/common.cpp
- python/test/unit/fem/test_function_space.py
Resolves #2929 
New enum not yet exposed in Python.
> Add option to preserve sub-IndexMap ghost ordering

- cpp/dolfinx/fem/FiniteElement.h
- python/dolfinx/wrappers/fem.cpp
Makes this function useful from Python when you have a contiguous array relating to more than a single cell with a single permutation.
Resolves #3089.
Tested for multiple cells in: https://github.com/jorgensd/adios4dolfinx/actions/runs/8179344989/job/22365266424?pr=92
while the DOLFINx C++ interface now uses the one cell version (which throws errors in `test_assembly` if not done correctly).
> Let  `*_apply_dof_transformation` accept lists of cells in Python layer

- cpp/dolfinx/common/IndexMap.cpp
- python/test/unit/common/test_index_map.py
The method for computing submap destination ranks in `main` does not work in general (see [this](https://github.com/FEniCS/dolfinx/issues/3097) issue). This is because, when a index changes owner in the submap and there are multiple possible owners, the new owning process does not know to include the other processes as destination ranks.
This PR fixes the issue by using NBX to compute the submap destination ranks from the submap source ranks and adds a test that fails on `main`.
In a future PR, I will add an extra communication step to replace NBX, which should be cheaper.
> Fix sub index map destination rank computation

- python/dolfinx/fem/__init__.py
- python/test/unit/fem/test_interpolation.py
Reverting: https://github.com/FEniCS/dolfinx/pull/3078/ as it wasn't quite right.
Added test to catch the actual user interface.
> Revert change to Python interface of non-matching interpolation data

- cpp/dolfinx/la/Vector.h
- python/demo/demo_elasticity.py
- python/demo/demo_stokes.py
- python/dolfinx/la.py
- python/dolfinx/wrappers/la.cpp
- python/test/unit/fem/test_assemble_submesh.py
- python/test/unit/fem/test_assembler.py
- python/test/unit/fem/test_complex_assembler.py
- python/test/unit/fem/test_custom_jit_kernels.py
- python/test/unit/fem/test_function.py
- python/test/unit/fem/test_ghost_mesh_assembly.py
- python/test/unit/la/test_matrix_vector.py
- python/test/unit/la/test_vector_scatter.py
Closes #3103.
Refactor `la.Vector.norm` into a function to reflect the C++ layer.
Add implementation of integer types for `la.Vector`.
Redesign the `la.Vector` tests to parametrize over `dtype` as well as `xfail` on unsupported (or not yet implemented) norm types.
> Refactor `la.Vector.norm`

- python/test/unit/fem/test_assemble_domains.py
> Generalize bounds of bc for arbitrary partitioning in `test_assembly_domains.py`

- cpp/dolfinx/io/ADIOS2Writers.h
- python/test/unit/io/test_adios2.py
Resolve #2720. Works with Paraview 5.12.0.RC3.
I've decided to keep it such that only single function-space functions should be saved in a single bp file.
This could of course be changed now, to store a mixture of DG-0 and a single other element function.
This is up for discussion.
We could also discuss how to implement the VTX mesh sharing policy for DG-0 functions.
Another point we now could address is meshtags (at least celltags) for VTXWriter.
@massimiliano-leoni do you mind testing this as well?:)
> Support DG-0 functions in VTXWriter

- python/demo/demo_elasticity.py
- python/demo/demo_static-condensation.py
- python/demo/demo_stokes.py
- python/demo/demo_waveguide/demo_half_loaded_waveguide.py
- python/dolfinx/fem/function.py
- python/dolfinx/la.py
- python/dolfinx/nls/petsc.py
- python/test/unit/fem/test_custom_assembler.py
- python/test/unit/fem/test_custom_basix_element.py
- python/test/unit/fem/test_dof_coordinates.py
- python/test/unit/fem/test_fem_pipeline.py
- python/test/unit/fem/test_nonlinear_assembler.py
- python/test/unit/fem/test_petsc_discrete_operators.py
- python/test/unit/la/test_krylov_solver.py
- python/test/unit/nls/test_newton.py
This PR allows for a `dlx.la.Vector` (rather than a `dlx.fem.Function`) to manage the memory and the scope of the `petsc4py.PETSc.vec` object that wraps the underlying data.
The implementation of the property `dlx.fem.Function.vector` was also modified to delegate the creation of the wrapper to the underlying `dlx.la.Vector`.
All changes are backward compatible.
See also Issue #3061
@jorgensd 
@garth-wells
@jhale
> Let dlx.la.Vector manage the scope of the petsc4py wrapper (#1)

- python/dolfinx/fem/function.py
Use the full library name `dolfinx`, instead of the abbreviation `dlx` which isn't used anywhere else in the code and may confuse end users.
Fixes #3092.
> Fix deprecation warning introduced in #3092

- cpp/CMakeLists.txt
Partial implementation of #3124.
> Require MPI ADIOS2 build during configuration.

- .github/workflows/ccpp.yml
This partially preparation for adding a build step without PETSc.
> Split linting and build steps in CI

- cpp/CMakeLists.txt
- python/test/unit/io/test_adios2.py
We know we are not compatible with 2.10. Will do a minor DOLFINx release once ADIOS 2.10 is widely available.
> Make ADIOS tests compatible with 2.9 and 2.10

- .github/workflows/ccpp.yml
Also removes deprecated [skip ci] check.
> Don't run build steps if linting fails

- cpp/demo/hyperelasticity/hyperelasticity.py
- cpp/demo/hyperelasticity/main.cpp
> Re-activate commented lines in hyperelastic demo

- README.md
I would like to make an install recommendation for high performance computers that is distinct from Linux - I'm not convinced of the performance at scale of conda or the Debian/Ubuntu packages.
> Add specific HPC install recommendation

- .github/workflows/conda.yml
- cpp/dolfinx/refinement/plaza.cpp
- cpp/dolfinx/refinement/plaza.h
- cpp/dolfinx/refinement/utils.cpp
- cpp/dolfinx/refinement/utils.h
Resolves #43.
Returns statically allocated data plus the size.
> Remove dynamic memory allocation inside tight loops in the Plaza refinement code

- cpp/test/mesh/distributed_mesh.cpp
CHECK appears to be the way checks are done elsewhere, this was the only assert left in the file.
I assume assert is being optimized out, causing [compiler error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=922042&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=2252) with `-Werror=unused-variable`. cpp tests pass during conda build with this patch.
First try at #3174 was wrong, but it didn't let me reopen that PR after I figured it out because I updated the branch while it was closed.
> TST: avoid unused variable in assert

- .github/workflows/ccpp.yml
Use an Github Actions image rather the the (very large) FEniCS Docker image.
Shaves a full minute off linting time.
> Do CI linting in Actions image

- cpp/dolfinx/refinement/plaza.h
Some compilers require `typename` with `std::conditional<>::type`. This should fix that problem.
> Use `std::conditional_t` for better C++ compatibility

- docker/Dockerfile.end-user
- docker/complex-kernel.json
Since we are using ubuntu:24.04 as base now Python version is 3.12
> Bump Python version in complex kernel to 3.12

- cpp/dolfinx/mesh/permutationcomputation.cpp
Generalise face permutation computation to get ready for mixed topology meshes.
* reduce duplicated code in face permutation computation for tet, hex
* adds computation for prism, (should work for pyramid too)
> Permutation computation refactoring

- .github/workflows/ccpp.yml
- docker/Dockerfile.test-env
- python/build-requirements.txt
- python/pyproject.toml
Use a virtual env in the Dockerfile for installing dependencies. This is nicer than overwriting system Python packages when installing/updating. Will also allow advanced users to test Python package versions more freely.
> Docker simplify (phase 2)

- python/demo/conftest.py
mpiexec is part of the mpi standard, mpirun is not, so mpiexec seems like a more logical default.
Shouldn't make a difference just about anywhere, but e.g. intel mpi on windows doesn't provide mpirun.
> demo test: default mpiexec to mpiexec

- python/dolfinx/fem/forms.py
- python/test/unit/fem/test_assemble_domains.py
Resolves #3252.
We should really simplify how `ufl` tags all surfaces, as currently one can supply, an integer, a string or a tuple of strings and integers, where the whole integration domain is indicated with -1.
This means that extracting any sensible information from the form becomes rather tedious. 
In UFL we go from "everywhere" -> "otherwise" in: https://github.com/FEniCS/ufl/blob/ea144b0bd8304776818515ec2b2e6033c63c1d87/ufl/algorithms/domain_analysis.py#L175-L206
which to me indicates that things are overcomplicated at the source.
> Allow dx and dx(i) in same form

- python/pyproject.toml
Ref:  https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin
> Prepare for release of numpy 2.0 by using ruff ruleset

- cpp/demo/custom_kernel/main.cpp
- cpp/dolfinx/fem/Form.h
- cpp/dolfinx/fem/utils.h
- python/demo/demo_static-condensation.py
- python/dolfinx/wrappers/fem.cpp
- python/test/unit/fem/test_custom_jit_kernels.py
Pack only entities used in integral type:
MWE:
```python
import dolfinx
import ufl
mesh = dolfinx.mesh.create_unit_cube(MPI.COMM_WORLD, 50, 50, 50)
V = dolfinx.fem.functionspace(mesh, ("Lagrange", 3))
N = 50
us = [dolfinx.fem.Function(V) for _ in range(N)]
for i,u in enumerate(us):
u.x.array[:] = i + 1
u.name=f"u_{i}"
volume_form = us[0] * ufl.dx
surface_form = sum(us[i] * ufl.ds for i in range(N))
combined_form = volume_form + surface_form
compiled_form = dolfinx.fem.form(combined_form)
import time
start = time.perf_counter()
coeffs = dolfinx.fem.assemble.pack_coefficients(compiled_form._cpp_object)
end =time.perf_counter()
print(f"{dolfinx.common.git_commit_hash=} {end-start=:.5e}")
print(coeffs[(dolfinx.fem.IntegralType.cell, -1)])
```
On the main branch, all …
> Use `enabled_coefficients` to restrict packing of coefficients

- cpp/dolfinx/mesh/utils.cpp
Currently `exterior_facet_indices()` only checks that the facet index map exists, which is insufficient.
* add a check for facet->cell connectivity instead
> Improve check for facet->cell connectivity

- .github/workflows/macos.yml
- python/demo/test.py
- python/test/unit/mesh/test_ghost_mesh.py
Fixes for pyamg and petsc are now available.
> Remove workarounds following upstream updates for CI

- python/dolfinx/wrappers/common.cpp
In addition to https://github.com/FEniCS/dolfinx/pull/3246 - as pointed out by @jhale this contains the corresponding exports to the python module.
> Export missing compile time constants to python

- .github/workflows/ccpp.yml
- .github/workflows/redhat.yml
Runs a prior `apt-get update` call before running the installs. This is also the recommended setup by github https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/customizing-github-hosted-runners.
> Fix ubuntu CI

- cpp/CMakeLists.txt
This matches the behaviour of our other optional dependencies.
> Turns search for KaHiP on by default.

- .github/workflows/ccpp.yml
- .github/workflows/macos.yml
- .github/workflows/pyvista.yml
- .github/workflows/redhat.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/windows.yml
- docker/Dockerfile.test-env
- python/dolfinx/utils.py
- python/pyproject.toml
Not totally clear why but there is an issue with the static condensation demo, numba and a new version of cffi. @michalhabera you can reproduce this by branching and removing the `cffi<1.17` restriction from `pyproject.toml`.
This PR also tidies up all of the CI pipelines; I would like to ask again, please do not put `pip install x y z` into pipelines. Please use the optional dependencies feature within `pyproject.toml`.
I have also split apart cffi registering Numba's complex types and creating cffi PETSc wrappers - you can now use cffi with numba complex numbers without having PETSc installed. This was causing a test failure.
> General tidy and restrict cffi < 1.17 due to static condensation demo issue

- python/test/unit/io/test_xdmf_meshtags.py
The new release of `ruff` version `0.6.0` requires an adaptation to make the CI pass again.
> Fix ruff check

- cpp/dolfinx/la/SparsityPattern.cpp
- cpp/dolfinx/la/SparsityPattern.h
- cpp/test/matrix.cpp
- python/dolfinx/wrappers/la.cpp
- python/test/unit/la/test_matrix_csr.py
Introduces a new sparsity pattern insert functionality for a single entry - which is the method of choice used in multiple locations of the code base.
Additionally the documentation of the `insert(span<>, span<>)` call on a  sparsity pattern  is extended to make clear how the inputs work together, and now hints that the interpretation of a pairwise operation is not correct to the caller.
> Sparsity pattern insert

- cpp/dolfinx/fem/DofMap.cpp
- python/test/unit/fem/test_dofmap.py
Currently, collapsing a dofmap with no dofs on the process segfaults due to unsafe access of `dofs_view.back()`, as it might be empty.
This is unlikely to happen to "standard" meshes, but very likely to happen for sub-meshes.
Thanks to @RemDelaporteMathurin for providing me with a segfaulting code that I could distill down.
> Fix DofMap::collapse() on rank with no dofs

- python/dolfinx/mesh.py
Create new ufl mesh as ufl mesh carries ufl_cargo which references the e latest mesh added through the mesh constructor.
This might be relevant for you as well @schnellerhase.
> Fix refine constructor (currently overwriting ufl_cargo)

- cpp/dolfinx/la/MatrixCSR.h
- cpp/test/matrix.cpp
- python/dolfinx/wrappers/la.cpp
- python/test/unit/la/test_matrix_vector.py
The (debug) functionality `to_dense` of the CSR matrix is extended to support the usage in parallel scenarios.
Before it returned the local-local block of the matrix (which in sequential is the whole matrix), i.e. the interaction between local rows and local cols. 
In parallel runs, this drops quite a lot of information, especially we loose all interactions across processes. This is now changed, to `to_dense` returning the full/global dense rows that are owned by the process. This means the previous behavior is still reproducible by filtering for the columns of choice, but if needed the full parallel block is now available in a dense format.
This will be needed to allow for a PR regarding the transfer operators of a multigrid implementation - see …
> Extend `to_dense` for parallel use cases

- cpp/dolfinx/common/IndexMap.cpp
Current code in  `communicate_ghosts_to_owners`  pads `send_data` such that we always send `ghosts.size()` amount of data to all owners, irrespective of if `include_ghosts` has any `True` values in it. This is later discarded in an if test (removed in this PR).
The current assumption with `-1` entries was also not documented, and when used in `compute_submap_ghost_indices` all `include_ghosts` where set to 1, which would ensure one get no -1 back.
The current PR removes this padding, which simplifies the logic of `create_submap_indices` and possibly undefined behavior of `global_to_local` when `recv_indices<0`
> Reduce complexity of `create_submap_indices`

- cpp/dolfinx/fem/utils.h
- python/test/unit/fem/test_assemble_submesh.py
Continuation of https://github.com/FEniCS/dolfinx/pull/3260.
If one has multiple disjoint sub-meshes in a variational form, then restricting packing by `enabled_coefficients` per integral type is not sufficient.
Example follows:
Divide an interval mesh in three disjoint cell sets (left, center, right).
If we want to create a coupling from the right submesh to the parent mesh at the interface between center and right),
we can add an integral `(u_parent("+")-u_parent("-"))*v_right("+")*dS(interface_rc)` to our variational form.
Similarly we could do the same for the left integral: `(u_parent("+")-u_parent("-"))*v_left("+")*dS(interface_lc)`.
However, now both coefficient v_right and v_left will be packed for all facets marked with either interface_rc or interface_lc, which leads to …
> Skip negative cell indices when packing coefficients

- .github/workflows/windows.yml
Windows CI is failing at the moment. Can be re-enabled for PRs once issue is resolved.
> Windows CI on dispatch only

- cpp/dolfinx/fem/interpolate.h
Use element value size to create reference buffer.
At least partially resolves #3372
> Correct reference value size

- python/test/unit/fem/test_petsc_solver_wrappers.py
- python/test/unit/fem/test_solvers.py
Adds a lightweight test comparing LinearProblem to NonlinearProblem with Newton solver of the same problem.
Resolves: #3187
> Test PETSc solver wrappers

- cpp/dolfinx/io/xdmf_utils.cpp
> Add read option of prims/wedges through xdmffile

- python/test/unit/fem/test_quadrature_elements.py
- Parallelize existing test_vector_element_test for quadrature
- Extend to higher quadrature degree
- Add test for assembly of quadrature coefficient by comparing to spatial coordinate assembly
Resolves #2872
> Extend testing of quadrature element

- python/demo/demo_mixed-poisson.py
The mixed Poisson demo says it uses the Brezzi-Douglas-Fortin-Marini element in the docs, but it's actually using the BDMCF element, which is (as far as I'm aware) just a Brezzi-Douglas-Marini element defined on a quad (the CF stands for cubical face, not Fortin). This PR fixes the name.
@mscroggs please correct me if this is wrong.
> Fix element name in mixed Poisson demo

- python/dolfinx/wrappers/mesh.cpp
Duplicate binding returning the wrong dtype and a `list` is now changed to one returning a `numpy`-array.
> Fix nanobinding for interprocess facets

- .github/workflows/sonarcloud.yml
We get the following warning on the main branch:
```bash
Last analysis has warnings
Property 'sonar.cfamily.build-wrapper-output' is deprecated; build-wrapper now generates a compilation database.
Please use the property 'sonar.cfamily.compile-commands' instead to specify the path of the 'compile_commands.json' file generated inside the build-wrapper output directory.
Visit the documentation for more up-to-date information on analysis using build-wrapper https://docs.sonarsource.com/sonarcloud/advanced-setup/languages/c-family/prerequisites/
```
> Bumping sonar-scanner-cli and removing deprecated command

- cpp/dolfinx/refinement/CMakeLists.txt
- cpp/dolfinx/refinement/interval.h
- cpp/dolfinx/refinement/option.h
- cpp/dolfinx/refinement/plaza.h
- cpp/dolfinx/refinement/refine.h
- cpp/dolfinx/refinement/utils.h
- cpp/test/CMakeLists.txt
- cpp/test/refinement/interval.cpp
- cpp/test/refinement/option.cpp
- python/dolfinx/mesh.py
- python/dolfinx/wrappers/refinement.cpp
- python/test/unit/refinement/test_interval.py
- python/test/unit/refinement/test_refinement.py
This PR contains several changes to the refinement routines to facilitate a neater, simpler and combined API to the user.
1. The interface of the `plaza` routines now uses `std::optional`'s as input arguments and thus allows for a single code path. (Previously the cases of uniform and adaptive refinement were treated independently)
2. The plaza refinement options was centralized to the (more general) `refinement` namespace and now is also used for configuring the interval refinement.
3. The return values of parent facets and cells are now `std::optional` as well, to no longer need to rely on an ambiguous empty array check. 
4. The python export and interface with the new optional arguments is greatly simplified, no longer do we need to export multiple versions of the refinement routines, …
> Unify refine interface 

- python/dolfinx/wrappers/mesh.cpp
Resolve #2978.
Illustrative use-case:
```python
from dolfinx import cpp, mesh
msh = mesh.create_unit_square(MPI.COMM_WORLD, 10, 10, cpp.mesh.CellType.triangle)
dofmap = msh.geometry.dofmap.reshape(-1).copy()
igi = msh.geometry.input_global_indices.copy()
nodes =  msh.geometry.x.reshape(-1).copy()
new_geom = cpp.mesh.Geometry_float64(msh.geometry.index_map(), 
dofmap, msh.geometry.cmap,nodes, 2, igi)
```
> Expose geometry constructor in Python

- python/dolfinx/utils.py
Make `cffi` type registry also work when `pets4py` is not available.
> Fix cffi_utils for abscence of petsc4py

- python/dolfinx/io/gmshio.py
- python/dolfinx/io/utils.py
- python/test/unit/mesh/test_meshtags.py
Missed when added a Python interface of topology in #3406.
Appropriate test added.
> Fix Python wrapper of `distribute_entity_data`

- python/dolfinx/fem/forms.py
Relevant for block models, if one wants to use `ufl.MixedFunctionSpace`, where `ufl.extract_block(a, i, j)` can return None or an empty form.
https://github.com/FEniCS/ufl/blob/main/ufl/form.py#L311
> A form can be empty and should return None

- cpp/dolfinx/fem/Expression.h
- python/test/unit/fem/test_expression.py
Currently if an Expression gets a blocked test or trial function, we do not take into account this block size when accessing the underlying tabulate kernel.
The added test segfaults on the main branch
**Background**
A testfunction in a blocked space (say for instance bs=3) will be evaluated as
(v, 0, 0), (0,v,0), (0,0,v) in our expression kernels, where `v` is the basis function evaluated at a given point.
**Example**
```python
import dolfinx
import ufl
mesh = dolfinx.mesh.create_unit_square(MPI.COMM_SELF, 1, 1, cell_type=dolfinx.mesh.CellType.quadrilateral)
value_shape = (3,)
V = dolfinx.fem.functionspace(mesh, ("Lagrange", 2, value_shape))
v = ufl.TestFunction(V)
points = np.array([[0.513, 0.317]], dtype=mesh.geometry.x.dtype)
expr = …
```
> Fix argument block-size in Expressions

- python/doc/source/installation.rst
PETSc and petsc4py is now optional but recommended, pyamg now supported.
> Update Install instructions

- docker/Dockerfile.test-env
Fall back to NumPy version that is supported by Numba. Otherwise Numba uninstalls NumPy to then install an earlier version. This could breaks libraries, e.g. petsc4py, that are built with a non-compatible NumPy version.
Add notes in Dockerfile that NumPy version should be latest version that is compatible with Numba.
> Use earlier NumPy version in Dockerfile

- python/test/unit/fem/test_assemble_submesh.py
Arity order in this inner product was reversed, leading to failing complex tests
> Fix arity order of operators in test

- docker/Dockerfile.test-env
See e.g. https://github.com/FEniCS/dolfinx/actions/runs/11279818289
Usage of undefined variable `$PYTHONPATH` will be kept.
> Fix warnings from Docker build linter

- cpp/dolfinx/common/Timer.h
- python/dolfinx/common.py
- python/dolfinx/wrappers/common.cpp
- python/test/unit/common/test_timer.py
The logic behind the interaction between `Timer` and `TimeLogger` was messed up. This attempts to fix it without interface changes.
Improves and fixes tests.
> Fixes to `Timer` logic

- cpp/dolfinx/fem/Expression.h
- cpp/dolfinx/fem/utils.h
- python/dolfinx/geometry.py
- python/dolfinx/wrappers/array.h
- python/dolfinx/wrappers/assemble.cpp
- python/dolfinx/wrappers/common.cpp
- python/dolfinx/wrappers/fem.cpp
- python/dolfinx/wrappers/geometry.cpp
- python/dolfinx/wrappers/graph.cpp
- python/dolfinx/wrappers/la.cpp
- python/dolfinx/wrappers/mesh.cpp
`nanobind` [docs](https://nanobind.readthedocs.io/en/latest/ndarray.html) for `nanobind::ndarray` have improved lot recently, which has helped with these changes to simplify code.
> Simplify interface to `nanobind::ndarray`

- .github/workflows/ccpp.yml
- cpp/dolfinx/common/Scatterer.h
- cpp/dolfinx/io/xdmf_utils.cpp
- cpp/dolfinx/io/xdmf_utils.h
- cpp/dolfinx/la/MatrixCSR.h
- cpp/dolfinx/la/SparsityPattern.h
- cpp/dolfinx/mesh/Geometry.h
- cpp/dolfinx/mesh/Mesh.h
- cpp/dolfinx/mesh/topologycomputation.cpp
- cpp/dolfinx/mesh/topologycomputation.h
- cpp/dolfinx/refinement/dolfinx_refinement.h
- docker/Dockerfile.test-env
- python/demo/demo_axis.py
- python/demo/demo_cahn-hilliard.py
- python/demo/demo_half_loaded_waveguide.py
- python/demo/demo_pml.py
- python/demo/demo_pyvista.py
- python/demo/demo_stokes.py
- python/dolfinx/fem/petsc.py
- python/dolfinx/wrappers/io.cpp
- python/test/unit/fem/test_petsc_solver_wrappers.py
MUMPS and SuperLU_dist can be shaky for less common types, i.e. other than `float64` and `int32`. This change picks a solver that works for each of the combinations tested on the CI.
> Demo updates for LU solver bugs

- cpp/dolfinx/fem/FiniteElement.cpp
- cpp/dolfinx/fem/FiniteElement.h
- python/dolfinx/wrappers/fem.cpp
- python/test/unit/fem/test_dofmap.py
- python/test/unit/fem/test_mixed_element.py
`fem::FiniteElement` and `fem::FunctionSpace` are in a bit of a mess with respect to block size, value_shape and mixed elements. It's all a bit muddled. This is a first step of several to straighten things out. This change makes `fem::FiniteElement::_reference_value_shape` optional - it takes on a value only when it makes sense and when needed, i.e. not for mixed elements.
> Start simplification and consistency fixes for `fem::FiniteElement`

- python/dolfinx/wrappers/mesh.cpp
To be able to make a valid geometry from Python (without using create_topology, as one wants to avoid re-distribution of data), one has to expose the `original_cell_index` attribute to Python.
As we have used this as a public variable in C++, I've gone down the route of creating a setter function in the Python binding, rather than exposing a "list-of-lists" to Python, as we would rather like it to be numpy based.
> Expose set original cell index to python

- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/nls/test_newton.py
Thanks to @jonas-heinzmann for clearly identifying and explaining this issue and @michalhabera for help creating this fix.
When using a linesearch routine SNES needs to calculate (multiple times) the norm of the residual evaluated at a vector `w` equal to the current solution plus some proposed scaling factor times the Newton increment. To do this SNES calls the user-defined residual evaluation routine passing `w`. Our current implementation of the residual evaluation routine overwrites the residual form state `u` with `w` but does not *replace* `u` with the current solution `x` before returning. This leads to a failure of the linesearch.
This patch fixes this behaviour by preserving the internal state of the residual.
> Fix SNES NonlinearPDE class when using line search

- python/dolfinx/fem/petsc.py
Continuation of: https://github.com/FEniCS/dolfinx/pull/3329
Uncovered in: https://github.com/FEniCS/dolfinx/issues/3522#issuecomment-2488679142
> Add more PETSc destruction notes to assembly functionality that creates PETSc.Mat/Vec objects

- cpp/dolfinx/mesh/Topology.cpp
- python/test/unit/mesh/test_mesh.py
Entity_offsets got too big for `tdim=0`, causing wrong `tdim` and segfaults.
> Fix topological dimension of vertex-meshes

- .github/workflows/macos.yml
Homebrew OpenMPI requires `mpiexec` when executing an MPI binary otherwise it prints a scary-looking warning
> Remove error/warning when running macOS with OpenMPI

- .github/workflows/macos.yml
Reverts https://github.com/FEniCS/dolfinx/pull/3530 since the `macos-14-arm64` has now been updated, see https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20241125.556.
> Remove brew unlink

- cpp/dolfinx/geometry/BoundingBoxTree.h
- python/dolfinx/geometry.py
- python/dolfinx/wrappers/geometry.cpp
Reported by @adeebkor.
The constructor:
```c++
/// Constructor
/// @param[in] mesh The mesh for building the bounding box tree
/// @param[in] tdim The topological dimension of the mesh entities to
/// build the bounding box tree for
/// @param[in] padding Value to pad (extend) the the bounding box of
/// each entity by.
BoundingBoxTree(const mesh::Mesh<T>& mesh, int tdim, T padding = 0)
: BoundingBoxTree::BoundingBoxTree(
mesh, tdim, range(mesh.topology_mutable(), tdim), padding)
{
```
does not work at the moment (and is never tested), as `range` takes in a reference, not a shared pointer.
To fix this, and follow the rest of DOLFINx, I've unified the constructors using `std::optional`.
This also removes the None-conversion in the Python layer.
> Unify and fix BoundingBoxtree constructor (C++)

- python/demo/demo_axis.py
- python/demo/demo_elasticity.py
- python/dolfinx/fem/element.py
- python/dolfinx/wrappers/fem.cpp
- python/test/unit/fem/test_discrete_operators.py
- python/test/unit/fem/test_dof_permuting.py
- python/test/unit/fem/test_dofmap.py
- python/test/unit/fem/test_expression.py
- python/test/unit/fem/test_function_space.py
- python/test/unit/fem/test_interpolation.py
- python/test/unit/fem/test_petsc_discrete_operators.py
Wrapping of `dolfinx::fem::FiniteElement<T>::signature` is not correct with the new Python wrappers.
Currently returning a C++ method: https://github.com/FEniCS/dolfinx/blob/debd46e92abcf9e2c026d6e7a24f5804b74e88e0/python/dolfinx/fem/element.py#L262
> Further fixes to FiniteElement Python wrapper

- python/demo/demo_axis.py
- python/demo/demo_gmsh.py
- python/demo/demo_pml.py
- python/demo/demo_scattering_boundary_conditions.py
- python/dolfinx/io/gmshio.py
Fix https://github.com/FEniCS/dolfinx/issues/3482
Extract `edge_tags` and `vertex_tags` from gmsh if exists and return a `NamedTuple` with mesh and meshtags rather than a regular tuple. 
Another thing I also find very useful is to the extract the physical groups from gmsh. This can be done as follows
```python
if comm.rank == rank:
gmsh.initialize()
gmsh.model.add("Mesh from file")
gmsh.merge(str(msh_file))
mesh, ct, ft, et, vt = model_to_mesh(gmsh.model, comm, 0)
markers = {
gmsh.model.getPhysicalName(*v): tuple(reversed(v))
for v in gmsh.model.getPhysicalGroups()
}
gmsh.finalize()
else:
mesh, ct, ft, et, vt = model_to_mesh(gmsh.model, comm, 0)
markers = {}
markers = comm.bcast(markers, root=rank)
```
However, since we here return a `NamedTuple` we could also add these markers as another …
> Extract edge tags and vertex tags from gmsh and return a NamedTuple

- cpp/dolfinx/fem/dofmapbuilder.cpp
When a mesh contains cells with different facet types, e.g. tetrahedra and pyramids, cells try to loop over all facet types, (in this case triangle and quadrilateral). However, tets do not have any quadrilateral facets, so it will fail.
This only comes up with higher order dofmaps (since facets are not required at P1).
> Fix for mixed topology when mixing cells with different facet types

- python/demo/demo_helmholtz.py
This is a minimal change addressing the issue raised in https://github.com/FEniCS/dolfinx/issues/3557
> Modify demo_helmholtz.py to solve for plane wave solution in complex mode

- cpp/dolfinx/refinement/interval.h
- cpp/test/mesh/generation.cpp
- cpp/test/mesh/refinement/interval.cpp
The interval refinement routine falsely ignores the `std::optional` data type of the underlying checked object, causing undefined behavior in the case of it being unassigned. 
Introduces a fix to the assertion and a (previously failing) test case. 
Fixes https://github.com/FEniCS/dolfinx/issues/3583
> Fix: interval refinement assertion ignores optional type

- python/dolfinx/fem/forms.py
- python/test/unit/fem/test_assemble_mesh_independent_form.py
Initially reported at: https://fenicsproject.discourse.group/t/issue-fem-create-form-with-dg0-function-and-ufl-derivative/16718?u=dokken
When constants and/or coefficients are eliminated from a ufl-form due to differentiation, this was not taken into account when creating the maps for coefficients/constants.
This PR corrects this behavior, ensuring that all remaining coefficients in the form are provided, as well as mapping them to the correct index.
> Fix mapping of coefficients and constants for form independent compilation.

- cpp/dolfinx/fem/assemble_vector_impl.h
- python/demo/demo_mixed-topology.py
- python/dolfinx/fem/assemble.py
- python/dolfinx/fem/function.py
- python/dolfinx/wrappers/fem.cpp
This PR adds support for the assembly of linear forms with cell integrals on mixed-topology meshes.
There is still a lot of work to be done to allow, for example, other integral types and the application of boundary conditions etc.
> Support assembly of linear forms with cell integrals on mixed-topology meshes

- python/dolfinx/fem/petsc.py
Some minor tweaks to allow PETSc vector in dolfinx to support the mixed topology meshes.
> Update PETSc vector for mixed topology

- python/build-requirements.txt
- python/pyproject.toml
Needed due to #3617. Otherwise the user may get odd errors like
```
#23 127.3       CMake Error at /usr/local/lib/python3.12/site-packages/nanobind/cmake/nanobind-config.cmake:316 (add_library):
#23 127.3         Cannot find source file:
#23 127.3       
#23 127.3           NB_SUPPRESS_WARNINGS
#23 127.3       Call Stack (most recent call first):
#23 127.3         CMakeLists.txt:34 (nanobind_add_module)
#23 127.3       
#23 127.3       
#23 127.3       CMake Error at /usr/local/lib/python3.12/site-packages/nanobind/cmake/nanobind-config.cmake:316 (add_library):
#23 127.3         No SOURCES given to target: cpp
#23 127.3       Call Stack (most recent call first):
#23 127.3         CMakeLists.txt:34 (nanobind_add_module)
#23 127.3       
#23 127.3       
#23 127.3       CMake Generate step …
```
> Require `nanobind>=2.5.0`

- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/Topology.h
- python/dolfinx/wrappers/mesh.cpp
- python/test/unit/mesh/test_mixed_topology.py
Adds a utility to compute the lists of pairs of cells for `dS` integrals, in the mixed-topology case.
`mesh::compute_mixed_cell_pairs(const Topology& topology, mesh::CellType facet_type)`
returns a list for each possible combination of cells, containing the cell indices and local facet indices for each pair.
> Mixed topology: find dS cells

- python/conda-oneapi-test-env.yml
- python/demo/demo_static-condensation.py
- python/pyproject.toml
- python/test/unit/fem/test_custom_assembler.py
The CFFI version was pinned to <1.17 due to the bug https://github.com/python-cffi/cffi/issues/110, which hasn't made its way into a CFFI release. However, older CFFI releases do not support Python 3.13.
This changes removes the CFFI version pin, and for CFFI version 1.17.0/1 adds skips to tests that fail due to the CFFI bug. 
Resolves #3340.
> Unpin cffi version (fixes tests for Python 3.13)

- cpp/demo/custom_kernel/main.cpp
- cpp/dolfinx/fem/assemble_matrix_impl.h
- cpp/dolfinx/fem/assemble_scalar_impl.h
- cpp/dolfinx/fem/assemble_vector_impl.h
- cpp/dolfinx/fem/assembler.h
- python/dolfinx/wrappers/dolfinx_wrappers/pycoeff.h
- python/test/unit/fem/test_expression.py
Use `mdspan` for multi-dimensional arrays in the (private) assembler implementations. `mdspan` has crept into the interface in other places, so we might as well use it where it makes things simpler. This change:
- Reduces the number of arguments to assembly interfaces, which improves readability. 
- Exposed an error in the Python interface for wrapping 2D arrays
- Removes code lint where data was passed that was not used.
- Has documentation improvements (still more to do).
- In simplifying the code exposed sub-performant code, which has been fixed (#3645).
> Simplify assembler implementation interfaces

- python/pyproject.toml
This was pinned pending an update to Breathe. A new Breathe version has since been released.
> Unpin Sphinx version.

- cpp/demo/hyperelasticity/main.cpp
- cpp/demo/interpolation_different_meshes/main.cpp
- cpp/demo/mixed_poisson/main.cpp
- cpp/dolfinx/common/math.h
- cpp/dolfinx/fem/CoordinateElement.cpp
- cpp/dolfinx/fem/CoordinateElement.h
- cpp/dolfinx/fem/DirichletBC.h
- cpp/dolfinx/fem/DofMap.cpp
- cpp/dolfinx/fem/DofMap.h
- cpp/dolfinx/fem/Function.h
- cpp/dolfinx/fem/FunctionSpace.h
- cpp/dolfinx/fem/assemble_expression_impl.h
- cpp/dolfinx/fem/assembler.h
- cpp/dolfinx/fem/interpolate.h
- cpp/dolfinx/fem/traits.h
- cpp/dolfinx/geometry/utils.h
- cpp/dolfinx/io/XDMFFile.cpp
- cpp/dolfinx/io/vtk_utils.cpp
- cpp/dolfinx/io/vtk_utils.h
- cpp/dolfinx/io/xdmf_function.cpp
- cpp/dolfinx/io/xdmf_mesh.cpp
- cpp/dolfinx/io/xdmf_utils.cpp
- cpp/dolfinx/io/xdmf_utils.h
- cpp/dolfinx/mesh/Geometry.h
- cpp/dolfinx/mesh/utils.h
- cpp/dolfinx/refinement/plaza.h
- cpp/dolfinx/refinement/utils.h
- cpp/test/matrix.cpp
- python/dolfinx/wrappers/fem.cpp
- python/dolfinx/wrappers/io.cpp
Following changes in https://github.com/FEniCS/dolfinx/pull/3642 we can remove the usage of `MDSPAN_IMPL_STANDARD_NAMESPACE`, besides the one time definition in `types.h`. Resulting in notably easier to read type declarations.
> Simplify: `MDSPAN_IMPL_STANDARD_NAMESPACE` -> `md`

- cpp/dolfinx/mesh/utils.h
I wasn't sure whether to also allow this to be passed to all of the built-in mesh functions or not. It could also be exposed to Python. Let me know what is preferred.
> Allow a custom cell reorder function to be passed to `create_mesh`

- cpp/dolfinx/io/cells.cpp
- cpp/dolfinx/io/xdmf_utils.cpp
- python/dolfinx/io/utils.py
Adds the missing pieces for being able to use S2 (serendipity 2) elements as coordinate elements, and read the meshes to and from XDMF.
MWE 
```python
import dolfinx
import basix.ufl
filename = "serendipity.xdmf"
if MPI.COMM_WORLD.rank == 0:
mesh = dolfinx.mesh.create_unit_square(MPI.COMM_SELF, 10, 12, cell_type=dolfinx.cpp.mesh.CellType.quadrilateral)
#mesh = dolfinx.mesh.create_unit_cube(MPI.COMM_SELF, 3, 4,5  , cell_type=dolfinx.cpp.mesh.CellType.hexahedron)
num_cells = mesh.topology.index_map(mesh.topology.dim).size_local
mesh.topology.create_connectivity(1, mesh.topology.dim)
edge_map = mesh.topology.index_map(1)
num_edges_local = edge_map.size_local
midpoints = dolfinx.mesh.compute_midpoints(mesh, 1, np.arange(num_edges_local, …
```
> Add support for Serendipity (order 2) coordinate elements

- cpp/dolfinx/fem/petsc.h
- cpp/dolfinx/la/petsc.cpp
- cpp/dolfinx/la/petsc.h
- python/demo/demo_stokes.py
- python/dolfinx/fem/petsc.py
- python/dolfinx/wrappers/petsc.cpp
- python/test/unit/fem/test_assembler.py
- python/test/unit/fem/test_petsc_nonlinear_assembler.py
Stemming from discussions in #3648, here is an attempt at unifying the PETSc matrix and vector constructors.
It avoids docs duplication, and very small wrapper function mapping Python <-> C++ one to one.
> Unify PETSc matrix and vector factory functions

- .github/workflows/ccpp.yml
- cpp/demo/custom_kernel/main.cpp
- cpp/dolfinx/common/Scatterer.h
- cpp/dolfinx/common/types.h
- cpp/dolfinx/fem/DirichletBC.h
- cpp/dolfinx/fem/Expression.h
- cpp/dolfinx/fem/Function.h
- cpp/dolfinx/fem/assembler.h
- cpp/dolfinx/fem/discreteoperators.h
- cpp/dolfinx/fem/traits.h
- cpp/dolfinx/fem/utils.h
- cpp/dolfinx/la/Vector.h
- cpp/dolfinx/mesh/Topology.h
- cpp/test/mesh/read_named_meshtags.cpp
- python/dolfinx/wrappers/fem.cpp
This change requires `clang-format` checks to pass for CI to be green . `clang-format`  checks were previously 'non-blocking', which didn't really help anything.
> Require `clang-format` CI checks to pass

- docker/Dockerfile.test-env
The Ubuntu packaged version of spdlog/fmt cannot be built by CUDA compilers. This builds spdlog from source.﻿ The outcome of this is that our containers can easily be used for CUDA development.
> Build spdlog from source in Dockerfile.test-env

- python/dolfinx/fem/petsc.py
- python/test/unit/fem/test_assembler.py
Patch for #3668.
Also generalizes the assembly checks to different kinds of matrices.
> Correct usage of input coefficients for `apply_lifting` of blocked operators.

- python/dolfinx/fem/petsc.py
- python/test/unit/fem/test_assembler.py
Corner-case that happens for instance for solving singular Poisson using the real function space:
- There is no diagonal block in the blocked `A` matrix.
- There are no DirichletBCs
Currently the code then tries to iterate a `None`-object, instead of going through the C++ wrapped list that is empty.
Uncovered in: https://github.com/scientificcomputing/scifem/pull/106
> Block assembly with no DirichletBC and None on diagonal

- python/dolfinx/fem/forms.py
- python/dolfinx/jit.py
https://github.com/FEniCS/ffcx/pull/757 exposes two typing issues in DOLFINx (https://github.com/FEniCS/basix/actions/runs/14327628553/job/40156132123)
1. Typing of scalar type from options
2. Call to non-existing function `compile_coordinate_maps`, that was removed with https://github.com/FEniCS/ffcx/pull/327
> Fixes for mypy

- .github/workflows/spack.yml
- README.md
PETSc is now optional for `fenics-dolfinx` in spack, so we need to specify it `+petsc`.
> Update spack specification for PETSc optional

- python/test/unit/io/test_vtkhdf.py
Fixing failing Basix CI.
eg in https://github.com/FEniCS/basix/pull/918, CI is failing with DOLFINx main (https://github.com/FEniCS/basix/actions/runs/14664578518/job/41156277652) and pass with this DOLFINx branch (https://github.com/FEniCS/basix/actions/runs/14665033516/job/41158949036).
> Use dtype in vtkhdf test

- .github/workflows/oneapi.yml
The presence of both `llvm-openmp` and `intel-openmp` causes an error in the intel CI - warning for possible performance implications.
We can not avoid this presence of both: `llvm-openmp` will be pulled in in by the `llvm` tooling which `numba` builds on and `intel-openmp` is what we would like to use for testing here.
Deactivates the warning by setting `KMP_DUPLICATE_LIB_OK`.
> Fix oneapi CI

- cpp/dolfinx/common/sort.h
- cpp/test/common/sort.cpp
Fixes bug in `radix_sort`, reported by @jorgensd,  for signed integers where bitwise comparison failed and resulted in either infinite loops or unsorted result.
Fixes it by radix sort only working on unsigned ints internally and inputs with signed getting shifted to corresponding unsigned int ranges.
> Fix signed version of radix_sort

- python/demo/demo_axis.py
- python/demo/demo_gmsh.py
- python/dolfinx/io/gmshio.py
- Simplifies the data-structures within `model_to_mesh`.
- All tagged groups are treated in the same way, looping through all sub-entities
- Correct name for codimensional entities (peak, ridge, edge, facet, cell).
- Add various documentation
> Refactor gmshio to use correct naming of subentities

- python/test/unit/fem/test_assembler.py
The blocked assembly routines have previously only been tested for first order non vector elements. Introduce an additional test case for `P2^2xP1`. 
Changes the equality checks for block and nest from norm based to element wise. 
Left over from debugging https://github.com/FEniCS/dolfinx/issues/3698.
> Extend blocked/nest/monolithic assembly test with a higher order vector example

- python/pyproject.toml
As discussed we want to support Python 3.9 until EoL. This deactivates the necessary ruff check, which deprecates the usage of `typing.Optional`. After EoL of 3.9 this can be reverted (fixed) with https://github.com/FEniCS/dolfinx/pull/3755.
> Deactivate ruff 3.9 deprecation

- .github/workflows/redhat.yml
- docker/Dockerfile.redhat
- mpi4py suddenly switched to a binary wheel and it could not find libmpi*.
- It turns out MPI/HDF5/PETSc libs were being installed to `/usr/local/lib` which is not correct on RedHat`/usr/local/lib64`.
- In addition, new RedHat doesn't even place `/usr/local/lib*` on the dynamic linkers search paths.
This PR
- Installs MPI/HDF5 libs into `/usr/local/lib64`.
- Preemptively tries to use PETSc's build system put libs in `/usr/local/lib64` but that doens't yet work , see https://gitlab.com/petsc/petsc/-/issues/1154.
- Puts `/usr/local/lib*` on the dynamic linkers search path (properly, not a hack).
> Install custom built libraries to proper locations on RedHat image

- python/dolfinx/fem/petsc.py
Possibly introduced during a merge. Those three functions are already present on lines 1036 and following.
> Remove duplicate lines from `fem/petsc.py`

- python/dolfinx/fem/petsc.py
Follow up to https://github.com/FEniCS/dolfinx/pull/3785.
Passing an empty `petsc_options_prefix` string breaks. This is composed of PETSc's optional type handling  of `getOptionsPrefix` and input of `setOptionsPrefix` not aligning, and the internal empty c-string being encoded  as "\0" instead of "". 
As an empty prefix is not desirable, we just raise to avoid this.
Debugged with @jhale.
> Check PETSc options prefix is not empty

- python/demo/demo_axis.py
- python/demo/demo_biharmonic.py
- python/demo/demo_cahn-hilliard.py
- python/demo/demo_helmholtz.py
- python/demo/demo_mixed-poisson.py
- python/demo/demo_pml.py
- python/demo/demo_poisson.py
- python/demo/demo_pyamg.py
- python/demo/demo_scattering_boundary_conditions.py
- python/demo/demo_stokes.py
- python/demo/demo_tnt-elements.py
- python/dolfinx/fem/petsc.py
- python/test/unit/fem/test_petsc_nonlinear_assembler.py
- python/test/unit/fem/test_petsc_solver_wrappers.py
- Users are encouraged to use PETSc native interface to getConvergedReason throughout all demos and tests.
- Consistent return of DOLFINx native function(s) for LinearProblem and NonlinearProblem.
Will tidy up documentation next.
> Simplify PETSc wrapper solve return type

- .github/workflows/clang-tidy.yml
- cpp/dolfinx/fem/CoordinateElement.h
- cpp/dolfinx/fem/DirichletBC.h
- cpp/dolfinx/fem/petsc.h
- cpp/dolfinx/graph/partition.cpp
- cpp/dolfinx/la/SparsityPattern.cpp
- cpp/dolfinx/la/SparsityPattern.h
- cpp/dolfinx/mesh/MeshTags.h
- cpp/dolfinx/mesh/Topology.cpp
- cpp/dolfinx/mesh/Topology.h
- cpp/dolfinx/mesh/generation.h
- python/dolfinx/wrappers/assemble.cpp
- python/dolfinx/wrappers/common.cpp
- python/dolfinx/wrappers/fem.cpp
- python/dolfinx/wrappers/geometry.cpp
- python/dolfinx/wrappers/graph.cpp
- python/dolfinx/wrappers/io.cpp
- python/dolfinx/wrappers/la.cpp
- python/dolfinx/wrappers/mesh.cpp
- python/dolfinx/wrappers/petsc.cpp
- python/dolfinx/wrappers/refinement.cpp
Revert changes that should not have been made.
C++ is too complicated for tools that changes the semantic of code.
> Revert some clang-tidy changes

- python/CMakeLists.txt
PR  #3756 added `C` as a language in  `python/CMakeLists.txt`. Change breaks Spack builds - build doesn't depend on C so Spack doesn't make a C compiler available.
Change in `python/CMakeLists.txt` seems unrelated to the PR and no text in the PR explaining change.
> Revert `python/CMakeLists.txt` change made in #3756

- cpp/dolfinx/io/xdmf_function.cpp
Time info in function name should not be part of the attributes, only the data item's name needs to be differentiated between the different time steps by name.
This caused time step data for a function `u` to not be named `u/0`, `u/1`, ... - which broke paraviews time step visualisation. 
Fixes https://github.com/FEniCS/dolfinx/issues/3828
> Fix XDMF time series

- .github/workflows/macos.yml
- cpp/test/main.cpp
Catch2 [`>=3.9.0`](https://github.com/catchorg/Catch2/releases/tag/v3.9.0) changes execution order to random by default. This needs to be deactivated for MPI parallel testing.
> Force non random order of execution for C++ tests

- .github/workflows/ccpp.yml
- .github/workflows/ci-spack.yml
- .github/workflows/macos.yml
- cpp/CMakeLists.txt
- cpp/test/CMakeLists.txt
Includes the c++ tests into the root cmake project with the standard `CMake` testing functionality.
- Standard flag [`BUILD_TESTING`](https://cmake.org/cmake/help/latest/variable/BUILD_TESTING.html) enables/disables build of tests
- All compile time flags, settings etc are inherited now from the central project setup and do not require to be reconfigured.
- Test build/execution do not require a prior installation.
- Parallel test cases are run through `ctetst` automatically (Removing the need to rerun with different parallelisation settings
- New option `DOLFINX_TEST_MPI_PROCESSES` encodes the process counts to run during the test phase
This is motivated by
1. Development experience on the C++ end, the install + change directory + compile/run tests setup simplifies to
```bash
ninja && …
```
> Integrate C++ tests into project cmake

- .github/workflows/ccpp.yml
- .github/workflows/ci-spack.yml
- .github/workflows/macos.yml
- cpp/CMakeLists.txt
- cpp/test/CMakeLists.txt
Exporting a test target is nice but the fixed `mpiexec` hits walls quickly - we have no idea what downstream consumers need to use.
> Remove `mpiexec` in cmake test target

- .github/workflows/ccpp.yml
- cpp/test/CMakeLists.txt
Allows to also use the c++ tests as a standalone project. Building on top of an already installed dolfinx version.
Also fixes a bad linkage against `Catch2::Catch2WithMain` - since we provide our own `main` - we need to link against `Catch2::Catch2`.
> Make tests work as standalone project

- cpp/dolfinx/la/MatrixCSR.h
Enables a "copy constructor" for `la::MatrixCSR` to a different storage type (typically `thrust::device_vector`) allowing a CPU-based matrix to be simply copied to GPU.
> Allow copy of MatrixCSR to different storage (GPU support)

- .github/workflows/conda.yml
- python/dolfinx/common.py
- python/dolfinx/fem/assemble.py
- python/dolfinx/fem/bcs.py
- python/dolfinx/fem/element.py
- python/dolfinx/fem/forms.py
- python/dolfinx/fem/function.py
- python/dolfinx/fem/petsc.py
- python/dolfinx/geometry.py
- python/dolfinx/graph.py
- python/dolfinx/io/gmsh.py
- python/dolfinx/io/utils.py
- python/dolfinx/jit.py
- python/dolfinx/mesh.py
- python/dolfinx/plot.py
- python/pyproject.toml
- python/test/unit/fem/test_function_space.py
- sonar-project.properties
Python 3.9 reaches EoL at 2025-10.
Together with
- https://github.com/FEniCS/ufl/pull/414 
- https://github.com/FEniCS/ffcx/pull/782
- https://github.com/FEniCS/basix/pull/954
raises min. Python version across FEniCS to 3.10.
Fixes https://github.com/FEniCS/dolfinx/issues/3758
> Drop Python 3.9 support

- .github/workflows/ccpp.yml
- .github/workflows/ci-spack.yml
- .github/workflows/macos.yml
- python/dolfinx/graph.py
- python/dolfinx/io/__init__.py
- python/dolfinx/io/gmshio.py
- python/dolfinx/utils.py
- python/test/unit/fem/test_expression.py
- python/test/unit/fem/test_petsc_solver_wrappers.py
- python/test/unit/nls/test_newton.py
Ensures and fixes warning propagation to caller. 
Triggered by: `import dolfinx` triggered now a deprecation warning after deprecation of `gmshio` in https://github.com/FEniCS/dolfinx/pull/3881. This is caused by including this module by default. Removes this include and passes `-W error` to the pytest calls in the CI which should catch such problems in the future.
Removes `gmshio`.
> Ensure `dolfinx` does not expose warning to user

- cpp/dolfinx/mesh/graphbuild.cpp
- python/test/unit/mesh/test_mesh.py
Minimal reproducible example (fails on `main`):
```python
import basix
import ufl
from dolfinx.mesh import create_mesh
comm = MPI.COMM_WORLD
if comm.rank == 0:
cells = np.zeros((0, 2), dtype=np.int32)
x = np.zeros((0, 3), dtype=np.float64)
else:
cells = np.array([[0, 1], [1, 2], [2, 0]], dtype=np.int32)
x = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0]], dtype=np.float64)
element = ufl.Mesh(basix.ufl.element("Lagrange", "interval", 1, shape=(3,)))
mesh = create_mesh(MPI.COMM_WORLD, cells, element, x)
```
Problem arises in the cases where the dual graph is already the global one, thus no facets are available on one process and the default assigned value breaks the parallel reduction of the size/range.
> Bugfix: mesh construction from mesh data on single process

- cpp/dolfinx/fem/DirichletBC.h
- python/test/unit/fem/test_bcs.py
For blocked function spaces, `locate_dofs_topological` and `DirichletBC` assumes blocked indices.
However, the private functions `num_owned` assumes that the dofs are unrolled, which makes the number of owned indices returned by `DirichletBC::dof_indices` wrong.
> `DirichletBC.dof_indices()` are wrong for blocked spaces

- docker/Dockerfile.end-user
- python/demo/demo_axis.py
- python/demo/demo_biharmonic.py
- python/demo/demo_cahn-hilliard.py
- python/demo/demo_half_loaded_waveguide.py
- python/demo/demo_interpolation-io.py
- python/demo/demo_pml.py
- python/demo/demo_poisson.py
- python/demo/demo_pyvista.py
- python/demo/demo_scattering_boundary_conditions.py
- python/demo/demo_types.py
XVFB (The virtual frame buffer) is a pain. It only works on linux, and causes all kinds of weird behavior.
With later versions of vtk (>=9.4.0) (https://docs.vtk.org/en/latest/advanced/available_python_wheels.html) they are shipped with omesa support.
Additionally, pyvista is deprecating xvfb (https://github.com/pyvista/pyvista/blob/aabfb3db2b0d4980de9e94e66272240efba4ed95/pyvista/plotting/utilities/xvfb.py#L48-L52) so we really need to move on.
In this PR I've:
1. Removed xvfb from all demos. Visualization still works with both PYVISTA_OFF_SCREEN=True or PYVISTA_OFF_SCREEN=False.
2. Create output folder for all output. We had an inconsistent usage of folders for output and placing figures/files directly in the demos folder.
Side-note:
I've also implemented this in the DOLFINx tutorial, …
> Clean up demo postprocessing
